/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagPalauProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagPalauRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE5NCA0SDIuMTgwNTdDMC45NzYyNzUgNCAwIDQuOTY5MzUgMCA2LjE2NTExVjE3LjgzNDlDMCAxOS4wMzA2IDAuOTc2Mjc1IDIwIDIuMTgwNTcgMjBIMjEuODE5NEMyMy4wMjM3IDIwIDI0IDE5LjAzMDYgMjQgMTcuODM0OVY2LjE2NTExQzI0IDQuOTY5MzUgMjMuMDIzNyA0IDIxLjgxOTQgNFoiIGZpbGw9IiMzQkFGREEiIC8+PHBhdGggZD0iTTEyLjAwMDEgMTYuNDI1NUMxNC40NjE3IDE2LjQyNTUgMTYuNDU3MyAxNC40NDQxIDE2LjQ1NzMgMTJDMTYuNDU3MyA5LjU1NTg0IDE0LjQ2MTcgNy41NzQ0NiAxMi4wMDAxIDcuNTc0NDZDOS41Mzg1IDcuNTc0NDYgNy41NDI5NyA5LjU1NTg0IDcuNTQyOTcgMTJDNy41NDI5NyAxNC40NDQxIDkuNTM4NSAxNi40MjU1IDEyLjAwMDEgMTYuNDI1NVoiIGZpbGw9IiNGNkQ2NjAiIC8+PC9zdmc+) */
const FlagPalau = React.forwardRef<FlagPalauRef, FlagPalauProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Palau" ref={ref}><path d="M21.8194 4H2.18057C0.976275 4 0 4.96935 0 6.16511V17.8349C0 19.0306 0.976275 20 2.18057 20H21.8194C23.0237 20 24 19.0306 24 17.8349V6.16511C24 4.96935 23.0237 4 21.8194 4Z" fill="#3BAFDA" /><path d="M12.0001 16.4255C14.4617 16.4255 16.4573 14.4441 16.4573 12C16.4573 9.55584 14.4617 7.57446 12.0001 7.57446C9.5385 7.57446 7.54297 9.55584 7.54297 12C7.54297 14.4441 9.5385 16.4255 12.0001 16.4255Z" fill="#F6D660" /></IconBase>)
FlagPalau.displayName = definePortfolioDisplayName("FlagPalau")

export { FlagPalau }