/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagParaguayProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagParaguayRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI2MDkxVjkuMzI1MzlIMjRWNi4yNjA5MUMyNCA1LjAxMjI0IDIyLjk4MDcgNCAyMS43MjM0IDRIMi4yOEMxLjY3NTYyIDMuOTk5MSAxLjA5NTY5IDQuMjM2OSAwLjY2ODAwNCA0LjY2MUMwLjI0MDMyMiA1LjA4NTEgLTYuODUzOTdlLTA3IDUuNjYwNjkgMCA2LjI2MDkxWiIgZmlsbD0iI0VENTU2NSIgLz48cGF0aCBkPSJNMCAxNC42NzEzSDI0VjkuMzM1NjlIMFYxNC42NzEzWiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTAgMTcuNzM5QzAgMTguOTg3NyAxLjAxOTI2IDE5Ljk5OTkgMi4yNzY1NyAxOS45OTk5SDIxLjcyMzRDMjIuOTgwNyAxOS45OTk5IDI0IDE4Ljk4NzcgMjQgMTcuNzM5VjE0LjY3NDZIMFYxNy43MzlaIiBmaWxsPSIjNEE4OURDIiAvPjxwYXRoIGQ9Ik0xMi4wMDMzIDEzLjcwMDlDMTIuOTUwMSAxMy43MDA5IDEzLjcxNzYgMTIuOTM4NiAxMy43MTc2IDExLjk5ODRDMTMuNzE3NiAxMS4wNTgxIDEyLjk1MDEgMTAuMjk1OSAxMi4wMDMzIDEwLjI5NTlDMTEuMDU2NiAxMC4yOTU5IDEwLjI4OTEgMTEuMDU4MSAxMC4yODkxIDExLjk5ODRDMTAuMjg5MSAxMi45Mzg2IDExLjA1NjYgMTMuNzAwOSAxMi4wMDMzIDEzLjcwMDlaIiBmaWxsPSJ3aGl0ZSIgc3Ryb2tlPSIjRUQ1NTY1IiBzdHJva2Utd2lkdGg9IjIiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const FlagParaguay = React.forwardRef<FlagParaguayRef, FlagParaguayProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Paraguay" ref={ref}><path d="M0 6.26091V9.32539H24V6.26091C24 5.01224 22.9807 4 21.7234 4H2.28C1.67562 3.9991 1.09569 4.2369 0.668004 4.661C0.240322 5.0851 -6.85397e-07 5.66069 0 6.26091Z" fill="#ED5565" /><path d="M0 14.6713H24V9.33569H0V14.6713Z" fill="white" /><path d="M0 17.739C0 18.9877 1.01926 19.9999 2.27657 19.9999H21.7234C22.9807 19.9999 24 18.9877 24 17.739V14.6746H0V17.739Z" fill="#4A89DC" /><path d="M12.0033 13.7009C12.9501 13.7009 13.7176 12.9386 13.7176 11.9984C13.7176 11.0581 12.9501 10.2959 12.0033 10.2959C11.0566 10.2959 10.2891 11.0581 10.2891 11.9984C10.2891 12.9386 11.0566 13.7009 12.0033 13.7009Z" fill="white" stroke="#ED5565" strokeWidth="2" strokeLinejoin="round" /></IconBase>)
FlagParaguay.displayName = definePortfolioDisplayName("FlagParaguay")

export { FlagParaguay }