/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagNigeriaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagNigeriaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMi4xODA4OCA0QzAuOTc2NDE0IDQgMCA0Ljk2OTM1IDAgNi4xNjUxMVYxNy44MzQ5QzAgMTkuMDMwNiAwLjk3NjQxNCAyMCAyLjE4MDg4IDIwSDguMDEwMjlDOC4wMTAyOSAxNC42NjY3IDguMDEwMjkgOS4zMzMzMyA4LjAxMDI5IDRIMi4xODA4OFoiIGZpbGw9IiM1N0E4NjMiIC8+PHBhdGggZD0iTTggNEM4IDkuMzMzMzMgOCAxNC42NjY3IDggMjBIMTYuMDA2OUMxNi4wMDY5IDE0LjY2NjcgMTYuMDA2OSA5LjMzMzMzIDE2LjAwNjkgNEg4WiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTIxLjgxOTEgNEgxNi4wMDY4QzE2LjAwNjggOS4zMzMzMyAxNi4wMDY4IDE0LjY2NjcgMTYuMDA2OCAyMEgyMS44MTkxQzIzLjAyMzYgMjAgMjQgMTkuMDMwNiAyNCAxNy44MzQ5VjYuMTY1MTFDMjQgNC45NjkzNSAyMy4wMjM2IDQgMjEuODE5MSA0WiIgZmlsbD0iIzU3QTg2MyIgLz48L3N2Zz4=) */
const FlagNigeria = React.forwardRef<FlagNigeriaRef, FlagNigeriaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Nigeria" ref={ref}><path d="M2.18088 4C0.976414 4 0 4.96935 0 6.16511V17.8349C0 19.0306 0.976414 20 2.18088 20H8.01029C8.01029 14.6667 8.01029 9.33333 8.01029 4H2.18088Z" fill="#57A863" /><path d="M8 4C8 9.33333 8 14.6667 8 20H16.0069C16.0069 14.6667 16.0069 9.33333 16.0069 4H8Z" fill="white" /><path d="M21.8191 4H16.0068C16.0068 9.33333 16.0068 14.6667 16.0068 20H21.8191C23.0236 20 24 19.0306 24 17.8349V6.16511C24 4.96935 23.0236 4 21.8191 4Z" fill="#57A863" /></IconBase>)
FlagNigeria.displayName = definePortfolioDisplayName("FlagNigeria")

export { FlagNigeria }