/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagCoteDeIcoireProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagCoteDeIcoireRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMi4xODA4OCA0LjAwMzRDMC45NzY0MTUgNC4wMDM0IDAgNC45NzI1NSAwIDYuMTY4MDVWMTcuODMyQzAgMTguNDA2MSAwLjIyOTc3MSAxOC45NTY2IDAuNjM4NzY2IDE5LjM2MjZDMS4wNDc3NiAxOS43Njg1IDEuNjAyNDggMTkuOTk2NiAyLjE4MDg4IDE5Ljk5NjZIOC4wMTAyOUM4LjAxMDI5IDE0LjY2NDQgOC4wMTAyOSA5LjMzMjIgOC4wMTAyOSA0TDIuMTgwODggNC4wMDM0WiIgZmlsbD0iI0ZGQUQ1NCIgLz48cGF0aCBkPSJNOC4wMDM5MSA0LjAwMzQyQzguMDAzOTEgOS4zMzU2MiA4LjAwMzkxIDE0LjY2NzggOC4wMDM5MSAyMEgxNi4wMTA4QzE2LjAxMDggMTQuNjY3OCAxNi4wMTA4IDkuMzM1NjIgMTYuMDEwOCA0LjAwMzQySDguMDAzOTFaIiBmaWxsPSJ3aGl0ZSIgLz48cGF0aCBkPSJNMjEuODE5MSA0LjAwMzQySDE2LjAwNjhDMTYuMDA2OCA5LjMzNTYyIDE2LjAwNjggMTQuNjY3OCAxNi4wMDY4IDIwSDIxLjgxOTFDMjMuMDIzNiAyMCAyNCAxOS4wMzA5IDI0IDE3LjgzNTRWNi4xNjgwNkMyNCA0Ljk3MjU2IDIzLjAyMzYgNC4wMDM0MiAyMS44MTkxIDQuMDAzNDJaIiBmaWxsPSIjNTJDMTYyIiAvPjwvc3ZnPg==) */
const FlagCoteDeIcoire = React.forwardRef<FlagCoteDeIcoireRef, FlagCoteDeIcoireProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Cote-de-Icoire" ref={ref}><path d="M2.18088 4.0034C0.976415 4.0034 0 4.97255 0 6.16805V17.832C0 18.4061 0.229771 18.9566 0.638766 19.3626C1.04776 19.7685 1.60248 19.9966 2.18088 19.9966H8.01029C8.01029 14.6644 8.01029 9.3322 8.01029 4L2.18088 4.0034Z" fill="#FFAD54" /><path d="M8.00391 4.00342C8.00391 9.33562 8.00391 14.6678 8.00391 20H16.0108C16.0108 14.6678 16.0108 9.33562 16.0108 4.00342H8.00391Z" fill="white" /><path d="M21.8191 4.00342H16.0068C16.0068 9.33562 16.0068 14.6678 16.0068 20H21.8191C23.0236 20 24 19.0309 24 17.8354V6.16806C24 4.97256 23.0236 4.00342 21.8191 4.00342Z" fill="#52C162" /></IconBase>)
FlagCoteDeIcoire.displayName = definePortfolioDisplayName("FlagCoteDeIcoire")

export { FlagCoteDeIcoire }