/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagItalyProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagItalyRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMi4xODA4OSA0LjAwMzRDMC45NzY0MTggNC4wMDM0IDAgNC45NzI1NCAwIDYuMTY4MDNWMTcuODMxOEMwIDE5LjAyNzMgMC45NzY0MTggMTkuOTk2NSAyLjE4MDg5IDE5Ljk5NjVIOC4wMTAzMkM4LjAxMDMyIDE0LjY2NDMgOC4wMTAzMiA5LjMzMjE1IDguMDEwMzIgNEwyLjE4MDg5IDQuMDAzNFoiIGZpbGw9IiM1N0E4NjMiIC8+PHBhdGggZD0iTTguMDAzOTEgNC4wMDM0MkM4LjAwMzkxIDkuMzM1NTcgOC4wMDM5MSAxNC42Njc3IDguMDAzOTEgMTkuOTk5OUgxNi4wMTc3QzE2LjAxNzcgMTQuNjY3NyAxNi4wMTc3IDkuMzM1NTcgMTYuMDE3NyA0LjAwMzQySDguMDAzOTFaIiBmaWxsPSJ3aGl0ZSIgLz48cGF0aCBkPSJNMjEuODE4NiA0LjAwMzQySDE2LjAxNjZDMTYuMDE2NiA5LjMzNTU3IDE2LjAxNjYgMTQuNjY3NyAxNi4wMTY2IDE5Ljk5OTlIMjEuODE4NkMyMy4wMjMxIDE5Ljk5OTkgMjMuOTk5NSAxOS4wMzA3IDIzLjk5OTUgMTcuODM1MlY2LjE2ODA0QzIzLjk5OTUgNC45NzI1NSAyMy4wMjMxIDQuMDAzNDIgMjEuODE4NiA0LjAwMzQyWiIgZmlsbD0iI0VENTU2NSIgLz48L3N2Zz4=) */
const FlagItaly = React.forwardRef<FlagItalyRef, FlagItalyProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Italy" ref={ref}><path d="M2.18089 4.0034C0.976418 4.0034 0 4.97254 0 6.16803V17.8318C0 19.0273 0.976418 19.9965 2.18089 19.9965H8.01032C8.01032 14.6643 8.01032 9.33215 8.01032 4L2.18089 4.0034Z" fill="#57A863" /><path d="M8.00391 4.00342C8.00391 9.33557 8.00391 14.6677 8.00391 19.9999H16.0177C16.0177 14.6677 16.0177 9.33557 16.0177 4.00342H8.00391Z" fill="white" /><path d="M21.8186 4.00342H16.0166C16.0166 9.33557 16.0166 14.6677 16.0166 19.9999H21.8186C23.0231 19.9999 23.9995 19.0307 23.9995 17.8352V6.16804C23.9995 4.97255 23.0231 4.00342 21.8186 4.00342Z" fill="#ED5565" /></IconBase>)
FlagItaly.displayName = definePortfolioDisplayName("FlagItaly")

export { FlagItaly }