/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagBeninProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagBeninRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE1OSA0LjAwMzQyTDguMjI4NTIgNC4wMDM0MlYxMS44MzE1SDIzLjk5OTlWNi4xNjgwN0MyMy45OTk5IDUuNTkzMzggMjMuNzY5NyA1LjA0MjI3IDIzLjM2MDEgNC42MzYyM0MyMi45NTA0IDQuMjMwMTggMjIuMzk0OSA0LjAwMjUyIDIxLjgxNTkgNC4wMDM0MloiIGZpbGw9IiNGNkQ2NjAiIC8+PHBhdGggZD0iTTguMjI4NTcgNC4wMDM0SDIuMTgwNTdDMC45NzYyNzUgNC4wMDM0IDAgNC45NzI1NSAwIDYuMTY4MDVWMTcuODMyQzAgMTkuMDI3NSAwLjk3NjI3NSAxOS45OTY2IDIuMTgwNTcgMTkuOTk2Nkg4LjIyODU3VjRWNC4wMDM0WiIgZmlsbD0iIzU3QTg2MyIgLz48cGF0aCBkPSJNOC4yMjg1MiAyMEgyMS44MTk0QzIzLjAyMzcgMjAgMjMuOTk5OSAxOS4wMzA5IDIzLjk5OTkgMTcuODM1NFYxMS44MzE1SDguMjI4NTJWMjBaIiBmaWxsPSIjRUQ1NTY1IiAvPjwvc3ZnPg==) */
const FlagBenin = React.forwardRef<FlagBeninRef, FlagBeninProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Benin" ref={ref}><path d="M21.8159 4.00342L8.22852 4.00342V11.8315H23.9999V6.16807C23.9999 5.59338 23.7697 5.04227 23.3601 4.63623C22.9504 4.23018 22.3949 4.00252 21.8159 4.00342Z" fill="#F6D660" /><path d="M8.22857 4.0034H2.18057C0.976275 4.0034 0 4.97255 0 6.16805V17.832C0 19.0275 0.976275 19.9966 2.18057 19.9966H8.22857V4V4.0034Z" fill="#57A863" /><path d="M8.22852 20H21.8194C23.0237 20 23.9999 19.0309 23.9999 17.8354V11.8315H8.22852V20Z" fill="#ED5565" /></IconBase>)
FlagBenin.displayName = definePortfolioDisplayName("FlagBenin")

export { FlagBenin }