/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagSwitzerlandProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagSwitzerlandRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE5NCA0SDIuMTgwNTdDMC45NzYyNzUgNCAwIDQuOTY5MzUgMCA2LjE2NTExVjE3LjgzNDlDMCAxOS4wMzA2IDAuOTc2Mjc1IDIwIDIuMTgwNTcgMjBIMjEuODE5NEMyMy4wMjM3IDIwIDI0IDE5LjAzMDYgMjQgMTcuODM0OVY2LjE2NTExQzI0IDQuOTY5MzUgMjMuMDIzNyA0IDIxLjgxOTQgNFoiIGZpbGw9IiNFRDU1NjUiIC8+PHBhdGggZD0iTTE1LjQyODYgMTAuNjM4MkgxMy4zNzE1VjguNTk1NjVDMTMuMzcxNSA4LjIxOTYyIDEzLjA2NDUgNy45MTQ3OSAxMi42ODU3IDcuOTE0NzlIMTEuMzE0M0MxMC45MzU2IDcuOTE0NzkgMTAuNjI4NiA4LjIxOTYyIDEwLjYyODYgOC41OTU2NVYxMC42MzgySDguNTcxNDZDOC4xOTI3NSAxMC42MzgyIDcuODg1NzQgMTAuOTQzIDcuODg1NzQgMTEuMzE5VjEyLjY4MDhDNy44ODU3NCAxMy4wNTY4IDguMTkyNzUgMTMuMzYxNiA4LjU3MTQ2IDEzLjM2MTZIMTAuNjI4NlYxNS40MDQyQzEwLjYyODYgMTUuNzgwMiAxMC45MzU2IDE2LjA4NSAxMS4zMTQzIDE2LjA4NUgxMi42ODU3QzEzLjA2NDUgMTYuMDg1IDEzLjM3MTUgMTUuNzgwMiAxMy4zNzE1IDE1LjQwNDJWMTMuMzYxNkgxNS40Mjg2QzE1LjgwNzMgMTMuMzYxNiAxNi4xMTQzIDEzLjA1NjggMTYuMTE0MyAxMi42ODA4VjExLjMxOUMxNi4xMTQzIDEwLjk0MyAxNS44MDczIDEwLjYzODIgMTUuNDI4NiAxMC42MzgyWiIgZmlsbD0id2hpdGUiIC8+PC9zdmc+) */
const FlagSwitzerland = React.forwardRef<FlagSwitzerlandRef, FlagSwitzerlandProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Switzerland" ref={ref}><path d="M21.8194 4H2.18057C0.976275 4 0 4.96935 0 6.16511V17.8349C0 19.0306 0.976275 20 2.18057 20H21.8194C23.0237 20 24 19.0306 24 17.8349V6.16511C24 4.96935 23.0237 4 21.8194 4Z" fill="#ED5565" /><path d="M15.4286 10.6382H13.3715V8.59565C13.3715 8.21962 13.0645 7.91479 12.6857 7.91479H11.3143C10.9356 7.91479 10.6286 8.21962 10.6286 8.59565V10.6382H8.57146C8.19275 10.6382 7.88574 10.943 7.88574 11.319V12.6808C7.88574 13.0568 8.19275 13.3616 8.57146 13.3616H10.6286V15.4042C10.6286 15.7802 10.9356 16.085 11.3143 16.085H12.6857C13.0645 16.085 13.3715 15.7802 13.3715 15.4042V13.3616H15.4286C15.8073 13.3616 16.1143 13.0568 16.1143 12.6808V11.319C16.1143 10.943 15.8073 10.6382 15.4286 10.6382Z" fill="white" /></IconBase>)
FlagSwitzerland.displayName = definePortfolioDisplayName("FlagSwitzerland")

export { FlagSwitzerland }