/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagBahamasProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagBahamasRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMC4wMTA3NDIyIDYuMjYwOTFWOS4zMjUzOUgyNC4wMDA1VjYuMjYwOTFDMjQuMDAwNSA1LjAxMjI0IDIyLjk4MTYgNCAyMS43MjQ5IDRIMi4yODk3N0MxLjY4NTY1IDMuOTk5MSAxLjEwNTk2IDQuMjM2OSAwLjY3ODQ2IDQuNjYxQzAuMjUwOTYyIDUuMDg1MSAwLjAxMDc0MTUgNS42NjA2OSAwLjAxMDc0MjIgNi4yNjA5MVoiIGZpbGw9IiMzQkFGREEiIC8+PHBhdGggZD0iTTAuMDA5NzY1NjIgMTQuNjcxMUgyMy45OTk1VjkuMzM1NDVIMC4wMDk3NjU2MlYxNC42NzExWiIgZmlsbD0iI0ZGQ0U1NCIgLz48cGF0aCBkPSJNMC4wMDk3NjU2MiAxNy43MzlDMC4wMDk3NjU2MiAxOC45ODc3IDEuMDI4NTggMTkuOTk5OSAyLjI4NTM2IDE5Ljk5OTlIMjEuNzIzOUMyMi45ODA3IDE5Ljk5OTkgMjMuOTk5NSAxOC45ODc3IDIzLjk5OTUgMTcuNzM5VjE0LjY3NDZIMC4wMDk3NjU2MlYxNy43MzlaIiBmaWxsPSIjM0JBRkRBIiAvPjxwYXRoIGQ9Ik0wLjcyOTk3MyA0LjU1MTUxQzAuMjY1NzE5IDQuOTYxMTYgNC4wMjg5NGUtMDUgNS41NDg1NyAwIDYuMTY1NDdWMTcuODM0M0M0LjAyODk0ZS0wNSAxOC40NTEyIDAuMjY1NzE5IDE5LjAzODcgMC43Mjk5NzMgMTkuNDQ4M0w5LjU5NTg5IDExLjk5ODJMMC43Mjk5NzMgNC41NTE1MVoiIGZpbGw9IiM0MzRBNTQiIC8+PC9zdmc+) */
const FlagBahamas = React.forwardRef<FlagBahamasRef, FlagBahamasProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Bahamas" ref={ref}><path d="M0.0107422 6.26091V9.32539H24.0005V6.26091C24.0005 5.01224 22.9816 4 21.7249 4H2.28977C1.68565 3.9991 1.10596 4.2369 0.67846 4.661C0.250962 5.0851 0.0107415 5.66069 0.0107422 6.26091Z" fill="#3BAFDA" /><path d="M0.00976562 14.6711H23.9995V9.33545H0.00976562V14.6711Z" fill="#FFCE54" /><path d="M0.00976562 17.739C0.00976562 18.9877 1.02858 19.9999 2.28536 19.9999H21.7239C22.9807 19.9999 23.9995 18.9877 23.9995 17.739V14.6746H0.00976562V17.739Z" fill="#3BAFDA" /><path d="M0.729973 4.55151C0.265719 4.96116 4.02894e-05 5.54857 0 6.16547V17.8343C4.02894e-05 18.4512 0.265719 19.0387 0.729973 19.4483L9.59589 11.9982L0.729973 4.55151Z" fill="#434A54" /></IconBase>)
FlagBahamas.displayName = definePortfolioDisplayName("FlagBahamas")

export { FlagBahamas }