/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagEquatorialGuineaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagEquatorialGuineaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI2MDQzVjkuMzI0MjZIMjRWNi4yNjA0M0MyNCA1LjAxMjAzIDIyLjk4MDcgNCAyMS43MjM0IDRIMi4yOEMxLjY3NTYyIDMuOTk5MSAxLjA5NTY5IDQuMjM2ODUgMC42NjgwMDQgNC42NjA4NkMwLjI0MDMyMiA1LjA4NDg3IC02Ljg1MzdlLTA3IDUuNjYwMzQgMCA2LjI2MDQzWiIgZmlsbD0iIzUyQzE2MiIgLz48cGF0aCBkPSJNMCAxNC42NzI0SDI0VjkuMzM3ODlIMFYxNC42NzI0WiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTAgMTcuNzM5NkMwIDE4Ljk4OCAxLjAxOTI2IDIwIDIuMjc2NTcgMjBIMjEuNzIzNEMyMi45ODA3IDIwIDI0IDE4Ljk4OCAyNCAxNy43Mzk2VjE0LjY3NThIMFYxNy43Mzk2WiIgZmlsbD0iI0VENTU2NSIgLz48cGF0aCBkPSJNMC43MzAyODYgNC41NTQ5M0MwLjI2NTgzMyA0Ljk2NDQ5IDQuMDMwNjZlLTA1IDUuNTUxNzggMCA2LjE2ODU1VjE3LjgzNDlDNC4wMzA2NmUtMDUgMTguNDUxNyAwLjI2NTgzMyAxOS4wMzkgMC43MzAyODYgMTkuNDQ4NUw5LjYgMTJMMC43MzAyODYgNC41NTQ5M1oiIGZpbGw9IiM0QTg5REMiIC8+PC9zdmc+) */
const FlagEquatorialGuinea = React.forwardRef<FlagEquatorialGuineaRef, FlagEquatorialGuineaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Equatorial-Guinea" ref={ref}><path d="M0 6.26043V9.32426H24V6.26043C24 5.01203 22.9807 4 21.7234 4H2.28C1.67562 3.9991 1.09569 4.23685 0.668004 4.66086C0.240322 5.08487 -6.8537e-07 5.66034 0 6.26043Z" fill="#52C162" /><path d="M0 14.6724H24V9.33789H0V14.6724Z" fill="white" /><path d="M0 17.7396C0 18.988 1.01926 20 2.27657 20H21.7234C22.9807 20 24 18.988 24 17.7396V14.6758H0V17.7396Z" fill="#ED5565" /><path d="M0.730286 4.55493C0.265833 4.96449 4.03066e-05 5.55178 0 6.16855V17.8349C4.03066e-05 18.4517 0.265833 19.039 0.730286 19.4485L9.6 12L0.730286 4.55493Z" fill="#4A89DC" /></IconBase>)
FlagEquatorialGuinea.displayName = definePortfolioDisplayName("FlagEquatorialGuinea")

export { FlagEquatorialGuinea }