/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagSerbiaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagSerbiaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI2MDkxVjkuMzI1MzlIMjRWNi4yNjA5MUMyNCA1LjAxMjI0IDIyLjk4MDcgNCAyMS43MjM0IDRIMi4yNzY1N0MxLjAxOTI2IDQgMCA1LjAxMjI0IDAgNi4yNjA5MVoiIGZpbGw9IiNFRDU1NjUiIC8+PHBhdGggZD0iTTAgMTQuNjcxM0gyNFY5LjMzNTY5SDBWMTQuNjcxM1oiIGZpbGw9IiM0NzU4QTkiIC8+PHBhdGggZD0iTTAgMTcuNzM5QzAgMTguOTg3NyAxLjAxOTI2IDE5Ljk5OTkgMi4yNzY1NyAxOS45OTk5SDIxLjcyMzRDMjIuOTgwNyAxOS45OTk5IDI0IDE4Ljk4NzcgMjQgMTcuNzM5VjE0LjY3NDZIMFYxNy43MzlaIiBmaWxsPSJ3aGl0ZSIgLz48cGF0aCBkPSJNOC45NDIwMiA5Ljk5MjgxTDguNjg4MzEgOC40NjA1N0g5LjU5Njg4TDkuMDI3NzQgNy42MDI1Mkw4LjY4NDg4IDcuNDA1MDNINy4zMTY4OEw2Ljg4ODMxIDkuOTkyODFINi4xNDQzMUw1LjcxMjMxIDcuNDA1MDNINC4zNDc3NEw0LjAwMTQ1IDcuNjAyNTJMMy40MzIzMSA4LjQ2MDU3SDQuMzQ0MzFMNC4wOTA1OSA5Ljk5MjgxSDIuNzQzMTZMNC45NDQzMSAxNS41NzM2SDguMDgxNDVMMTAuMjg5NCA5Ljk5MjgxSDguOTQyMDJaIiBmaWxsPSIjRkZDRTU0IiAvPjwvc3ZnPg==) */
const FlagSerbia = React.forwardRef<FlagSerbiaRef, FlagSerbiaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Serbia" ref={ref}><path d="M0 6.26091V9.32539H24V6.26091C24 5.01224 22.9807 4 21.7234 4H2.27657C1.01926 4 0 5.01224 0 6.26091Z" fill="#ED5565" /><path d="M0 14.6713H24V9.33569H0V14.6713Z" fill="#4758A9" /><path d="M0 17.739C0 18.9877 1.01926 19.9999 2.27657 19.9999H21.7234C22.9807 19.9999 24 18.9877 24 17.739V14.6746H0V17.739Z" fill="white" /><path d="M8.94202 9.99281L8.68831 8.46057H9.59688L9.02774 7.60252L8.68488 7.40503H7.31688L6.88831 9.99281H6.14431L5.71231 7.40503H4.34774L4.00145 7.60252L3.43231 8.46057H4.34431L4.09059 9.99281H2.74316L4.94431 15.5736H8.08145L10.2894 9.99281H8.94202Z" fill="#FFCE54" /></IconBase>)
FlagSerbia.displayName = definePortfolioDisplayName("FlagSerbia")

export { FlagSerbia }