/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagFaroeIslandsProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagFaroeIslandsRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCAxNC4xNzg3VjE3LjczOTZDMCAxOC45ODggMS4wMTkyNiAyMCAyLjI3NjU3IDIwSDYuNTQxNzFWMTQuMTc4N0gwWiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTYuNTQxNzEgNEgyLjI3NjU3QzEuMDE5MjYgNCAwIDUuMDEyMDMgMCA2LjI2MDQzVjkuODIxMjhINi41NDE3MVY0WiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTEwLjkzMzYgMjBIMjEuNzIzM0MyMi45ODA2IDIwIDIzLjk5OTkgMTguOTg4IDIzLjk5OTkgMTcuNzM5NlYxNC4xNzg3SDEwLjkzMzZWMjBaIiBmaWxsPSJ3aGl0ZSIgLz48cGF0aCBkPSJNMjMuOTk5OSA5LjgyMTI4VjYuMjYwNDNDMjMuOTk5OSA1LjAxMjAzIDIyLjk4MDYgNCAyMS43MjMzIDRIMTAuOTMzNlY5LjgyMTI4SDIzLjk5OTlaIiBmaWxsPSJ3aGl0ZSIgLz48cGF0aCBkPSJNOS44MzMwMSAxMC45MTA2SDIzLjk5OTlWOS44MjEyOEgxMC45MzAyVjRIOS44MzMwMVYxMC45MTA2WiIgZmlsbD0iIzQ2NThBOSIgLz48cGF0aCBkPSJNOS44MzMwMSAxMy4wODk0VjIwSDEwLjkzMDJWMTQuMTc4N0gyMy45OTk5VjEzLjA4OTRIOS44MzMwMVoiIGZpbGw9IiM0NjU4QTkiIC8+PHBhdGggZD0iTTcuNjM4ODYgMTAuOTEwNlY0SDYuNTQ1MTRWOS44MjEyOEgwVjEwLjkxMDZINy42Mzg4NloiIGZpbGw9IiM0NjU4QTkiIC8+PHBhdGggZD0iTTcuNjM4ODYgMTMuMDg5NEgwVjE0LjE3ODdINi41NDUxNFYyMEg3LjYzODg2VjEzLjA4OTRaIiBmaWxsPSIjNDY1OEE5IiAvPjxwYXRoIGQ9Ik05LjgzMzE0IDRINy42Mzg4NlYxMC45MTA2SDBWMTMuMDg5NEg3LjYzODg2VjIwSDkuODMzMTRWMTMuMDg5NEgyNFYxMC45MTA2SDkuODMzMTRWNFoiIGZpbGw9IiNFQzU1NjUiIC8+PC9zdmc+) */
const FlagFaroeIslands = React.forwardRef<FlagFaroeIslandsRef, FlagFaroeIslandsProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Faroe-Islands" ref={ref}><path d="M0 14.1787V17.7396C0 18.988 1.01926 20 2.27657 20H6.54171V14.1787H0Z" fill="white" /><path d="M6.54171 4H2.27657C1.01926 4 0 5.01203 0 6.26043V9.82128H6.54171V4Z" fill="white" /><path d="M10.9336 20H21.7233C22.9806 20 23.9999 18.988 23.9999 17.7396V14.1787H10.9336V20Z" fill="white" /><path d="M23.9999 9.82128V6.26043C23.9999 5.01203 22.9806 4 21.7233 4H10.9336V9.82128H23.9999Z" fill="white" /><path d="M9.83301 10.9106H23.9999V9.82128H10.9302V4H9.83301V10.9106Z" fill="#4658A9" /><path d="M9.83301 13.0894V20H10.9302V14.1787H23.9999V13.0894H9.83301Z" fill="#4658A9" /><path d="M7.63886 10.9106V4H6.54514V9.82128H0V10.9106H7.63886Z" fill="#4658A9" /><path d="M7.63886 13.0894H0V14.1787H6.54514V20H7.63886V13.0894Z" fill="#4658A9" /><path d="M9.83314 4H7.63886V10.9106H0V13.0894H7.63886V20H9.83314V13.0894H24V10.9106H9.83314V4Z" fill="#EC5565" /></IconBase>)
FlagFaroeIslands.displayName = definePortfolioDisplayName("FlagFaroeIslands")

export { FlagFaroeIslands }