/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagGambiaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagGambiaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCAxNy44MzMyQzAgMTkuMDMgMC45NzYxMzkgMjAuMDAwMiAyLjE4MDI3IDIwLjAwMDJIMjEuODE2NEMyMy4wMjA1IDIwLjAwMDIgMjMuOTk2NyAxOS4wMyAyMy45OTY3IDE3LjgzMzJWMTQuOTAzMUgwVjE3LjgzMzJaIiBmaWxsPSIjNTJDMTYyIiAvPjxwYXRoIGQ9Ik0yMy45OTY3IDE0LjIyMTdIMFYxNC45MDMxSDIzLjk5NjdWMTQuMjIxN1oiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0yMy45OTY3IDkuNzkyMjRIMFYxNC4yMjE1SDIzLjk5NjdWOS43OTIyNFoiIGZpbGw9IiM0NzU4QTkiIC8+PHBhdGggZD0iTTIxLjgzMzYgNC4wNDAwNEgyLjE5ODE1QzAuOTkzODUzIDQuMDQwMDQgMC4wMTc1NzgxIDUuMDUyNDcgMC4wMTc1NzgxIDYuMzAxMzdWOS4zNzMzN0gyNC4wMTc2VjYuMzAxMzdDMjQuMDE3NiA1LjcwMTAyIDIzLjc4NzQgNS4xMjUzIDIzLjM3NzcgNC43MDExMUMyMi45NjggNC4yNzY5MyAyMi40MTI1IDQuMDM5MSAyMS44MzM2IDQuMDQwMDRaIiBmaWxsPSIjRUQ1NTY1IiAvPjxwYXRoIGQ9Ik0yMy45OTY3IDkuMjA2NzlIMFY5Ljg3MTE4SDIzLjk5NjdWOS4yMDY3OVoiIGZpbGw9IndoaXRlIiAvPjwvc3ZnPg==) */
const FlagGambia = React.forwardRef<FlagGambiaRef, FlagGambiaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Gambia" ref={ref}><path d="M0 17.8332C0 19.03 0.976139 20.0002 2.18027 20.0002H21.8164C23.0205 20.0002 23.9967 19.03 23.9967 17.8332V14.9031H0V17.8332Z" fill="#52C162" /><path d="M23.9967 14.2217H0V14.9031H23.9967V14.2217Z" fill="white" /><path d="M23.9967 9.79224H0V14.2215H23.9967V9.79224Z" fill="#4758A9" /><path d="M21.8336 4.04004H2.19815C0.993853 4.04004 0.0175781 5.05247 0.0175781 6.30137V9.37337H24.0176V6.30137C24.0176 5.70102 23.7874 5.1253 23.3777 4.70111C22.968 4.27693 22.4125 4.0391 21.8336 4.04004Z" fill="#ED5565" /><path d="M23.9967 9.20679H0V9.87118H23.9967V9.20679Z" fill="white" /></IconBase>)
FlagGambia.displayName = definePortfolioDisplayName("FlagGambia")

export { FlagGambia }