/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagLesothoProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagLesothoRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMC4wMDI5Mjk2OSA2LjI2MDkxVjkuMzI1MzlIMjMuOTk5NVY2LjI2MDkxQzIzLjk5OTUgNS4wMTIyNCAyMi45ODA0IDQgMjEuNzIzMyA0SDIuMjc5MThDMS42NzU0OCA0IDEuMDk2NTEgNC4yMzgyIDAuNjY5NjI3IDQuNjYyMkMwLjI0Mjc0OCA1LjA4NjIxIDAuMDAyOTI5NjkgNS42NjEyOCAwLjAwMjkyOTY5IDYuMjYwOTFaIiBmaWxsPSIjNDc1OEE5IiAvPjxwYXRoIGQ9Ik0wLjAwMzkwNjI1IDE0LjY3MTNIMjQuMDAwNVY5LjMzNTY5SDAuMDAzOTA2MjVWMTQuNjcxM1oiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0wLjAwMzQyODA4IDE3LjczOUMwLjAwMzQyODA4IDE4LjMzODcgMC4yNDMyNDYgMTguOTEzNyAwLjY3MDEyNSAxOS4zMzc3QzEuMDk3IDE5Ljc2MTcgMS42NzU5OCAxOS45OTk5IDIuMjc5NjcgMTkuOTk5OUgyMS43MjAzQzIyLjMyNCAxOS45OTk5IDIyLjkwMyAxOS43NjE3IDIzLjMyOTkgMTkuMzM3N0MyMy43NTY4IDE4LjkxMzcgMjMuOTk2NiAxOC4zMzg3IDIzLjk5NjYgMTcuNzM5VjE0LjY3NDZIMEwwLjAwMzQyODA4IDE3LjczOVoiIGZpbGw9IiM1N0E4NjMiIC8+PHBhdGggZD0iTTkuNzczNDQgMTMuMzYzNkwxMi4wNDk3IDEwLjYzOTZMMTQuMjI5OSAxMy4zNjM2SDkuNzczNDRaIiBmaWxsPSIjNDM0QTU0IiAvPjwvc3ZnPg==) */
const FlagLesotho = React.forwardRef<FlagLesothoRef, FlagLesothoProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Lesotho" ref={ref}><path d="M0.00292969 6.26091V9.32539H23.9995V6.26091C23.9995 5.01224 22.9804 4 21.7233 4H2.27918C1.67548 4 1.09651 4.2382 0.669627 4.6622C0.242748 5.08621 0.00292969 5.66128 0.00292969 6.26091Z" fill="#4758A9" /><path d="M0.00390625 14.6713H24.0005V9.33569H0.00390625V14.6713Z" fill="white" /><path d="M0.00342808 17.739C0.00342808 18.3387 0.243246 18.9137 0.670125 19.3377C1.097 19.7617 1.67598 19.9999 2.27967 19.9999H21.7203C22.324 19.9999 22.903 19.7617 23.3299 19.3377C23.7568 18.9137 23.9966 18.3387 23.9966 17.739V14.6746H0L0.00342808 17.739Z" fill="#57A863" /><path d="M9.77344 13.3636L12.0497 10.6396L14.2299 13.3636H9.77344Z" fill="#434A54" /></IconBase>)
FlagLesotho.displayName = definePortfolioDisplayName("FlagLesotho")

export { FlagLesotho }