/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagLithuaniaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagLithuaniaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI1OTQ3VjkuMzIxOTlIMjRWNi4yNTk0N0MyNCA1LjY2MDIyIDIzLjc2MDEgNS4wODU1MiAyMy4zMzMyIDQuNjYxNzhDMjIuOTA2MyA0LjIzODA1IDIyLjMyNzIgNCAyMS43MjM0IDRIMi4yOEMxLjY3NTYyIDMuOTk5MSAxLjA5NTY5IDQuMjM2NzUgMC42NjgwMDQgNC42NjA1OEMwLjI0MDMyMiA1LjA4NDQxIC02Ljg1MzdlLTA3IDUuNjU5NjMgMCA2LjI1OTQ3WiIgZmlsbD0iI0Y2QkI0MiIgLz48cGF0aCBkPSJNMCAxNC42NzQ1SDI0VjkuMzQyMjlIMFYxNC42NzQ1WiIgZmlsbD0iIzU3QTg2MyIgLz48cGF0aCBkPSJNMCAxNy43NDA1QzAgMTguOTg4NCAxLjAxOTI2IDIwIDIuMjc2NTcgMjBIMjEuNzIzNEMyMi45ODA3IDIwIDI0IDE4Ljk4ODQgMjQgMTcuNzQwNVYxNC42NzhIMFYxNy43NDA1WiIgZmlsbD0iI0VENTU2NSIgLz48L3N2Zz4=) */
const FlagLithuania = React.forwardRef<FlagLithuaniaRef, FlagLithuaniaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Lithuania" ref={ref}><path d="M0 6.25947V9.32199H24V6.25947C24 5.66022 23.7601 5.08552 23.3332 4.66178C22.9063 4.23805 22.3272 4 21.7234 4H2.28C1.67562 3.9991 1.09569 4.23675 0.668004 4.66058C0.240322 5.08441 -6.8537e-07 5.65963 0 6.25947Z" fill="#F6BB42" /><path d="M0 14.6745H24V9.34229H0V14.6745Z" fill="#57A863" /><path d="M0 17.7405C0 18.9884 1.01926 20 2.27657 20H21.7234C22.9807 20 24 18.9884 24 17.7405V14.678H0V17.7405Z" fill="#ED5565" /></IconBase>)
FlagLithuania.displayName = definePortfolioDisplayName("FlagLithuania")

export { FlagLithuania }