/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagRomaniaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagRomaniaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMi4xODA4OCA0LjAwMzRDMC45NzY0MTUgNC4wMDM0IDAgNC45NzI1NSAwIDYuMTY4MDVWMTcuODMyQzAgMTkuMDI3NSAwLjk3NjQxNSAxOS45OTY2IDIuMTgwODggMTkuOTk2Nkg4LjAxMDI5QzguMDEwMjkgMTQuNjY0NCA4LjAxMDI5IDkuMzMyMiA4LjAxMDI5IDRMMi4xODA4OCA0LjAwMzRaIiBmaWxsPSIjNEE4OURDIiAvPjxwYXRoIGQ9Ik04LjAxMDc0IDQuMDAzNDJDOC4wMTA3NCA5LjMzNTYyIDguMDEwNzQgMTQuNjY3OCA4LjAxMDc0IDIwSDE2LjAxNzZDMTYuMDE3NiAxNC42Njc4IDE2LjAxNzYgOS4zMzU2MiAxNi4wMTc2IDQuMDAzNDJIOC4wMTA3NFoiIGZpbGw9IiNGRkNFNTQiIC8+PHBhdGggZD0iTTIxLjgxOTEgNC4wMDM0MkgxNi4wMDY4QzE2LjAwNjggOS4zMzU2MiAxNi4wMDY4IDE0LjY2NzggMTYuMDA2OCAyMEgyMS44MTkxQzIzLjAyMzYgMjAgMjQgMTkuMDMwOSAyNCAxNy44MzU0VjYuMTcxNDdDMjQuMDAwOSA1LjU5Njc4IDIzLjc3MTUgNS4wNDUzMiAyMy4zNjI0IDQuNjM4NjNDMjIuOTUzMyA0LjIzMTk0IDIyLjM5ODEgNC4wMDM0MiAyMS44MTkxIDQuMDAzNDJaIiBmaWxsPSIjRUQ1NTY1IiAvPjwvc3ZnPg==) */
const FlagRomania = React.forwardRef<FlagRomaniaRef, FlagRomaniaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Romania" ref={ref}><path d="M2.18088 4.0034C0.976415 4.0034 0 4.97255 0 6.16805V17.832C0 19.0275 0.976415 19.9966 2.18088 19.9966H8.01029C8.01029 14.6644 8.01029 9.3322 8.01029 4L2.18088 4.0034Z" fill="#4A89DC" /><path d="M8.01074 4.00342C8.01074 9.33562 8.01074 14.6678 8.01074 20H16.0176C16.0176 14.6678 16.0176 9.33562 16.0176 4.00342H8.01074Z" fill="#FFCE54" /><path d="M21.8191 4.00342H16.0068C16.0068 9.33562 16.0068 14.6678 16.0068 20H21.8191C23.0236 20 24 19.0309 24 17.8354V6.17147C24.0009 5.59678 23.7715 5.04532 23.3624 4.63863C22.9533 4.23194 22.3981 4.00342 21.8191 4.00342Z" fill="#ED5565" /></IconBase>)
FlagRomania.displayName = definePortfolioDisplayName("FlagRomania")

export { FlagRomania }