/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagNetherlandsProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagNetherlandsRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMS4yMTE1ZS0xMCA2LjI2MDkxVjkuMzI1MzlIMjRWNi4yNjA5MUMyNCA1LjAxMjI0IDIyLjk4MDcgNCAyMS43MjM0IDRIMi4yNjYyOUMxLjAxMjk5IDQuMDA1NjIgLTEuMjc5MTllLTA1IDUuMDE2MjIgMS4yMTE1ZS0xMCA2LjI2MDkxWiIgZmlsbD0iI0VENTU2NSIgLz48cGF0aCBkPSJNMCAxNC42NzEzSDI0VjkuMzM1NjlIMFYxNC42NzEzWiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTAgMTcuNzM5QzAgMTguOTg3NyAxLjAxOTI2IDE5Ljk5OTkgMi4yNzY1NyAxOS45OTk5SDIxLjcyMzRDMjIuOTgwNyAxOS45OTk5IDI0IDE4Ljk4NzcgMjQgMTcuNzM5VjE0LjY3NDZIMFYxNy43MzlaIiBmaWxsPSIjNEE4OURDIiAvPjwvc3ZnPg==) */
const FlagNetherlands = React.forwardRef<FlagNetherlandsRef, FlagNetherlandsProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Netherlands" ref={ref}><path d="M1.2115e-10 6.26091V9.32539H24V6.26091C24 5.01224 22.9807 4 21.7234 4H2.26629C1.01299 4.00562 -1.27919e-05 5.01622 1.2115e-10 6.26091Z" fill="#ED5565" /><path d="M0 14.6713H24V9.33569H0V14.6713Z" fill="white" /><path d="M0 17.739C0 18.9877 1.01926 19.9999 2.27657 19.9999H21.7234C22.9807 19.9999 24 18.9877 24 17.739V14.6746H0V17.739Z" fill="#4A89DC" /></IconBase>)
FlagNetherlands.displayName = definePortfolioDisplayName("FlagNetherlands")

export { FlagNetherlands }