/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagArmeniaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagArmeniaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI2MDkxVjkuMzI1MzlIMjRWNi4yNjA5MUMyNCA1LjAxMjI0IDIyLjk4MDcgNCAyMS43MjM0IDRIMi4yOEMxLjY3NTYyIDMuOTk5MSAxLjA5NTY5IDQuMjM2OSAwLjY2ODAwNCA0LjY2MUMwLjI0MDMyMiA1LjA4NTEgLTYuODUzN2UtMDcgNS42NjA2OSAwIDYuMjYwOTFaIiBmaWxsPSIjRUQ1NTY1IiAvPjxwYXRoIGQ9Ik0wIDE0LjY3MTNIMjRWOS4zNDkzN0gwVjE0LjY3MTNaIiBmaWxsPSIjNDc1OEE5IiAvPjxwYXRoIGQ9Ik0wIDE3LjczOUMwIDE4Ljk4NzcgMS4wMTkyNiAxOS45OTk5IDIuMjc2NTcgMTkuOTk5OUgyMS43MjM0QzIyLjk4MDcgMTkuOTk5OSAyNCAxOC45ODc3IDI0IDE3LjczOVYxNC42NzQ2SDBWMTcuNzM5WiIgZmlsbD0iI0ZGQ0U1NCIgLz48L3N2Zz4=) */
const FlagArmenia = React.forwardRef<FlagArmeniaRef, FlagArmeniaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Armenia" ref={ref}><path d="M0 6.26091V9.32539H24V6.26091C24 5.01224 22.9807 4 21.7234 4H2.28C1.67562 3.9991 1.09569 4.2369 0.668004 4.661C0.240322 5.0851 -6.8537e-07 5.66069 0 6.26091Z" fill="#ED5565" /><path d="M0 14.6713H24V9.34937H0V14.6713Z" fill="#4758A9" /><path d="M0 17.739C0 18.9877 1.01926 19.9999 2.27657 19.9999H21.7234C22.9807 19.9999 24 18.9877 24 17.739V14.6746H0V17.739Z" fill="#FFCE54" /></IconBase>)
FlagArmenia.displayName = definePortfolioDisplayName("FlagArmenia")

export { FlagArmenia }