/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagChechRepublicProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagChechRepublicRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE1OSA0SDIuMTgzMkMwLjk3OTA2OSA0IDAuMDAyOTI5NjkgNC45Njk1NiAwLjAwMjkyOTY5IDYuMTY1NTZWMTIuMTcxOUgyMy45OTk2VjYuMTY1NTZDMjMuOTk5NiA1LjU5MDYzIDIzLjc2OTQgNS4wMzkzIDIzLjM1OTggNC42MzMwOEMyMi45NTAyIDQuMjI2ODYgMjIuMzk0NyAzLjk5OTEgMjEuODE1OSA0WiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTAgMTcuODM0M0MwIDE5LjAzMDQgMC45NzYxMzkgMTkuOTk5OSAyLjE4MDI3IDE5Ljk5OTlIMjEuODE2NEMyMy4wMjA1IDE5Ljk5OTkgMjMuOTk2NyAxOS4wMzA0IDIzLjk5NjcgMTcuODM0M1YxMi4xNzE5SDBWMTcuODM0M1oiIGZpbGw9IiNFRDU1NjUiIC8+PHBhdGggZD0iTTAuNjU1MjUgNC42MjMwNUMwLjIzNzQyMiA1LjAzMDE5IDAuMDAyNTkzNDEgNS41ODc1MyAwLjAwMzkxMTc3IDYuMTY4OVYxNy44Mzc3QzAuMDA0MzA1NjcgMTguNDI1MiAwLjI0NTY5NCAxOC45ODcxIDAuNjcyMzkgMTkuMzkzOEw4LjU3NDE1IDEyLjE3MTlMMC42NTUyNSA0LjYyMzA1WiIgZmlsbD0iIzQ3NThBOSIgLz48L3N2Zz4=) */
const FlagChechRepublic = React.forwardRef<FlagChechRepublicRef, FlagChechRepublicProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Chech-republic" ref={ref}><path d="M21.8159 4H2.1832C0.979069 4 0.00292969 4.96956 0.00292969 6.16556V12.1719H23.9996V6.16556C23.9996 5.59063 23.7694 5.0393 23.3598 4.63308C22.9502 4.22686 22.3947 3.9991 21.8159 4Z" fill="white" /><path d="M0 17.8343C0 19.0304 0.976139 19.9999 2.18027 19.9999H21.8164C23.0205 19.9999 23.9967 19.0304 23.9967 17.8343V12.1719H0V17.8343Z" fill="#ED5565" /><path d="M0.65525 4.62305C0.237422 5.03019 0.00259341 5.58753 0.00391177 6.1689V17.8377C0.00430567 18.4252 0.245694 18.9871 0.67239 19.3938L8.57415 12.1719L0.65525 4.62305Z" fill="#4758A9" /></IconBase>)
FlagChechRepublic.displayName = definePortfolioDisplayName("FlagChechRepublic")

export { FlagChechRepublic }