/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagUnitedArabEmiratesProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagUnitedArabEmiratesRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI2NjNWOS4zMjg4M0gyNFY2LjI2NjNDMjQgNS4wMTg0MyAyMi45ODA3IDQuMDA2ODQgMjEuNzIzNCA0LjAwNjg0SDIuMjc2NTdDMS4wMTkyNiA0LjAwNjg0IDAgNS4wMTg0MyAwIDYuMjY2M1oiIGZpbGw9IiM1MkMxNjIiIC8+PHBhdGggZD0iTTAgMTQuNjc4MUgyNFY5LjMzOTExSDBWMTQuNjc4MVoiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0wIDE3Ljc0MDdDMCAxOC45ODg2IDEuMDE5MjYgMjAuMDAwMiAyLjI3NjU3IDIwLjAwMDJIMjEuNzIzNEMyMi45ODA3IDIwLjAwMDIgMjQgMTguOTg4NiAyNCAxNy43NDA3VjE0LjY3ODJIMFYxNy43NDA3WiIgZmlsbD0iIzQzNEE1NCIgLz48cGF0aCBkPSJNMi4xODA1NyA0LjAwMzRDMC45NzYyNzUgNC4wMDM0IDAgNC45NzIzNCAwIDYuMTY3NTlWMTcuODI5QzAgMTkuMDI0MyAwLjk3NjI3NSAxOS45OTMyIDIuMTgwNTcgMTkuOTkzMkg2LjE3MTQzVjRMMi4xODA1NyA0LjAwMzRaIiBmaWxsPSIjRUQ1NTY1IiAvPjwvc3ZnPg==) */
const FlagUnitedArabEmirates = React.forwardRef<FlagUnitedArabEmiratesRef, FlagUnitedArabEmiratesProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/United-Arab-Emirates" ref={ref}><path d="M0 6.2663V9.32883H24V6.2663C24 5.01843 22.9807 4.00684 21.7234 4.00684H2.27657C1.01926 4.00684 0 5.01843 0 6.2663Z" fill="#52C162" /><path d="M0 14.6781H24V9.33911H0V14.6781Z" fill="white" /><path d="M0 17.7407C0 18.9886 1.01926 20.0002 2.27657 20.0002H21.7234C22.9807 20.0002 24 18.9886 24 17.7407V14.6782H0V17.7407Z" fill="#434A54" /><path d="M2.18057 4.0034C0.976275 4.0034 0 4.97234 0 6.16759V17.829C0 19.0243 0.976275 19.9932 2.18057 19.9932H6.17143V4L2.18057 4.0034Z" fill="#ED5565" /></IconBase>)
FlagUnitedArabEmirates.displayName = definePortfolioDisplayName("FlagUnitedArabEmirates")

export { FlagUnitedArabEmirates }