/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagYemenProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagYemenRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI2MDQzVjkuMzI0MjZIMjRWNi4yNjA0M0MyNCA1LjAxMjAzIDIyLjk4MDcgNCAyMS43MjM0IDRIMi4yOEMxLjY3NTYyIDMuOTk5MSAxLjA5NTY5IDQuMjM2ODUgMC42NjgwMDQgNC42NjA4NkMwLjI0MDMyMiA1LjA4NDg3IC02Ljg1Mzk3ZS0wNyA1LjY2MDM0IDAgNi4yNjA0M1oiIGZpbGw9IiNFRDU1NjUiIC8+PHBhdGggZD0iTTAgMTQuNjY4OUgyNFY5LjMzNDQ3SDBWMTQuNjY4OVoiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0wIDE3LjczOTZDMCAxOC45ODggMS4wMTkyNiAyMCAyLjI3NjU3IDIwSDIxLjcyMzRDMjIuOTgwNyAyMCAyNCAxOC45ODggMjQgMTcuNzM5NlYxNC42NzU4SDBWMTcuNzM5NloiIGZpbGw9IiM0MzRBNTQiIC8+PC9zdmc+) */
const FlagYemen = React.forwardRef<FlagYemenRef, FlagYemenProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Yemen" ref={ref}><path d="M0 6.26043V9.32426H24V6.26043C24 5.01203 22.9807 4 21.7234 4H2.28C1.67562 3.9991 1.09569 4.23685 0.668004 4.66086C0.240322 5.08487 -6.85397e-07 5.66034 0 6.26043Z" fill="#ED5565" /><path d="M0 14.6689H24V9.33447H0V14.6689Z" fill="white" /><path d="M0 17.7396C0 18.988 1.01926 20 2.27657 20H21.7234C22.9807 20 24 18.988 24 17.7396V14.6758H0V17.7396Z" fill="#434A54" /></IconBase>)
FlagYemen.displayName = definePortfolioDisplayName("FlagYemen")

export { FlagYemen }