/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagMontenegroProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagMontenegroRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE5NCA0SDIuMTgwNTdDMC45NzYyNzUgNCAwIDQuOTY5MzUgMCA2LjE2NTExVjE3LjgzNDlDMCAxOS4wMzA2IDAuOTc2Mjc1IDIwIDIuMTgwNTcgMjBIMjEuODE5NEMyMy4wMjM3IDIwIDI0IDE5LjAzMDYgMjQgMTcuODM0OVY2LjE2NTExQzI0IDQuOTY5MzUgMjMuMDIzNyA0IDIxLjgxOTQgNFoiIGZpbGw9IiNGRkNFNTQiIC8+PHBhdGggZD0iTTIxLjgxOTEgNS4zNjE4MkMyMi4yNjUyIDUuMzYzNjggMjIuNjI2NCA1LjcyMjI5IDIyLjYyODIgNi4xNjUyMlYxNy44MzVDMjIuNjI2NCAxOC4yNzc5IDIyLjI2NTIgMTguNjM2NSAyMS44MTkxIDE4LjYzODRIMi4xODAyNEMxLjczNDE0IDE4LjYzNjUgMS4zNzI5NyAxOC4yNzc5IDEuMzcxMDkgMTcuODM1VjYuMTY1MjJDMS4zNzI5NyA1LjcyMjI5IDEuNzM0MTQgNS4zNjM2OCAyLjE4MDI0IDUuMzYxODJIMjEuODE1NyIgZmlsbD0iI0VENTU2NSIgLz48cGF0aCBkPSJNMTQuNDI3NCAxMC41MDU0TDE0LjE3MzcgOC45NzAxM0gxNS4wODIyTDE0LjUxMzEgOC4xMTIyNkwxNC4xNjY4IDcuOTE4MjFIMTIuODAyMkwxMi4zNzAyIDEwLjUwNTRIMTEuNjI5N0wxMS4xOTc3IDcuOTE4MjFIOS44MzMwOUw5LjQ4NjggOC4xMTIyNkw4LjkxNzY2IDguOTcwMTNIOS44MjYyM0w5LjU3MjUyIDEwLjUwNTRIOC4yMjg1MkwxMC40Mjk3IDE2LjA4MTZIMTMuNTYzNEwxNS43NzE0IDEwLjUwNTRIMTQuNDI3NFoiIGZpbGw9IiNGRkNFNTQiIC8+PC9zdmc+) */
const FlagMontenegro = React.forwardRef<FlagMontenegroRef, FlagMontenegroProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Montenegro" ref={ref}><path d="M21.8194 4H2.18057C0.976275 4 0 4.96935 0 6.16511V17.8349C0 19.0306 0.976275 20 2.18057 20H21.8194C23.0237 20 24 19.0306 24 17.8349V6.16511C24 4.96935 23.0237 4 21.8194 4Z" fill="#FFCE54" /><path d="M21.8191 5.36182C22.2652 5.36368 22.6264 5.72229 22.6282 6.16522V17.835C22.6264 18.2779 22.2652 18.6365 21.8191 18.6384H2.18024C1.73414 18.6365 1.37297 18.2779 1.37109 17.835V6.16522C1.37297 5.72229 1.73414 5.36368 2.18024 5.36182H21.8157" fill="#ED5565" /><path d="M14.4274 10.5054L14.1737 8.97013H15.0822L14.5131 8.11226L14.1668 7.91821H12.8022L12.3702 10.5054H11.6297L11.1977 7.91821H9.83309L9.4868 8.11226L8.91766 8.97013H9.82623L9.57252 10.5054H8.22852L10.4297 16.0816H13.5634L15.7714 10.5054H14.4274Z" fill="#FFCE54" /></IconBase>)
FlagMontenegro.displayName = definePortfolioDisplayName("FlagMontenegro")

export { FlagMontenegro }