/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagNorwayProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagNorwayRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE5NCA0SDIuMTgwNTdDMC45NzYyNzUgNCAwIDQuOTY5MzUgMCA2LjE2NTExVjE3LjgzNDlDMCAxOS4wMzA2IDAuOTc2Mjc1IDIwIDIuMTgwNTcgMjBIMjEuODE5NEMyMy4wMjM3IDIwIDI0IDE5LjAzMDYgMjQgMTcuODM0OVY2LjE2NTExQzI0IDQuOTY5MzUgMjMuMDIzNyA0IDIxLjgxOTQgNFoiIGZpbGw9IiNFRDU1NjUiIC8+PHBhdGggZD0iTTguMjI5MTkgNEg1LjQ4NjMzVjIwSDguMjI5MTlWNFoiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0wIDEzLjUzMlYxMC44MDg2SDI0VjEzLjUzMkgwWiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTcuMjAwMzYgNEg2LjUxNDY1VjIwSDcuMjAwMzZWNFoiIGZpbGw9IiM0NzU4QTkiIC8+PHBhdGggZD0iTTAgMTIuNTEwN1YxMS44Mjk4SDI0VjEyLjUxMDdIMFoiIGZpbGw9IiM0NzU4QTkiIC8+PC9zdmc+) */
const FlagNorway = React.forwardRef<FlagNorwayRef, FlagNorwayProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Norway" ref={ref}><path d="M21.8194 4H2.18057C0.976275 4 0 4.96935 0 6.16511V17.8349C0 19.0306 0.976275 20 2.18057 20H21.8194C23.0237 20 24 19.0306 24 17.8349V6.16511C24 4.96935 23.0237 4 21.8194 4Z" fill="#ED5565" /><path d="M8.22919 4H5.48633V20H8.22919V4Z" fill="white" /><path d="M0 13.532V10.8086H24V13.532H0Z" fill="white" /><path d="M7.20036 4H6.51465V20H7.20036V4Z" fill="#4758A9" /><path d="M0 12.5107V11.8298H24V12.5107H0Z" fill="#4758A9" /></IconBase>)
FlagNorway.displayName = definePortfolioDisplayName("FlagNorway")

export { FlagNorway }