/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagColombiaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagColombiaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE2OCA0SDIuMTg0MTdDMC45ODAwNDEgNCAwLjAwMzkwNjI1IDQuOTY5MzUgMC4wMDM5MDYyNSA2LjE2NTExVjExLjgyOThIMjQuMDAwNVY2LjE2MTdDMjMuOTk5NiA1LjU4NzQ4IDIzLjc2OSA1LjAzNzE0IDIzLjM1OTUgNC42MzE3NEMyMi45NDk5IDQuMjI2MzQgMjIuMzk1IDMuOTk5MSAyMS44MTY4IDRaIiBmaWxsPSIjRjZCQjQyIiAvPjxwYXRoIGQ9Ik0yMy45OTY2IDExLjgyM0gwVjE1LjkwODFIMjMuOTk2NlYxMS44MjNaIiBmaWxsPSIjNDc1OEE5IiAvPjxwYXRoIGQ9Ik0xLjA4MDQyZS0wNSAxNy44MjhDLTAuMDAxODEzOSAxOC40MDQgMC4yMjc1NTcgMTguOTU2OSAwLjYzNzM3NCAxOS4zNjQ2QzEuMDQ3MTkgMTkuNzcyMiAxLjYwMzY3IDIwLjAwMDggMi4xODM3IDE5Ljk5OTlIMjEuODE2M0MyMy4wMjA0IDE5Ljk5OTkgMjMuOTk2NiAxOS4wMzA1IDIzLjk5NjYgMTcuODM0OFYxNS45MTQ4SDEuNTU1NDllLTA4TDEuMDgwNDJlLTA1IDE3LjgyOFoiIGZpbGw9IiNFRDU1NjUiIC8+PC9zdmc+) */
const FlagColombia = React.forwardRef<FlagColombiaRef, FlagColombiaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Colombia" ref={ref}><path d="M21.8168 4H2.18417C0.980041 4 0.00390625 4.96935 0.00390625 6.16511V11.8298H24.0005V6.1617C23.9996 5.58748 23.769 5.03714 23.3595 4.63174C22.9499 4.22634 22.395 3.9991 21.8168 4Z" fill="#F6BB42" /><path d="M23.9966 11.823H0V15.9081H23.9966V11.823Z" fill="#4758A9" /><path d="M1.08042e-05 17.828C-0.0018139 18.404 0.227557 18.9569 0.637374 19.3646C1.04719 19.7722 1.60367 20.0008 2.1837 19.9999H21.8163C23.0204 19.9999 23.9966 19.0305 23.9966 17.8348V15.9148H1.55549e-08L1.08042e-05 17.828Z" fill="#ED5565" /></IconBase>)
FlagColombia.displayName = definePortfolioDisplayName("FlagColombia")

export { FlagColombia }