/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagFranceProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagFranceRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMi4xODA4OCA0LjAwMzRDMC45NzY0MTUgNC4wMDM0IDAgNC45NzI1NSAwIDYuMTY4MDVWMTcuODMxOUMwIDE5LjAyNzQgMC45NzY0MTUgMTkuOTk2NiAyLjE4MDg4IDE5Ljk5NjZIOC4wMTAyOUM4LjAxMDI5IDE0LjY2NDQgOC4wMTAyOSA5LjMzMjE5IDguMDEwMjkgNEwyLjE4MDg4IDQuMDAzNFoiIGZpbGw9IiM0NzU4QTkiIC8+PHBhdGggZD0iTTguMDAzOTEgNC4wMDM0MkM4LjAwMzkxIDkuMzM1NjEgOC4wMDM5MSAxNC42Njc4IDguMDAzOTEgMjBIMTYuMDEwOEMxNi4wMTA4IDE0LjY2NzggMTYuMDEwOCA5LjMzNTYxIDE2LjAxMDggNC4wMDM0Mkg4LjAwMzkxWiIgZmlsbD0id2hpdGUiIC8+PHBhdGggZD0iTTIxLjgxOTEgNC4wMDM0MkgxNi4wMDY4QzE2LjAwNjggOS4zMzU2MSAxNi4wMDY4IDE0LjY2NzggMTYuMDA2OCAyMEgyMS44MTkxQzIzLjAyMzYgMjAgMjQgMTkuMDMwOCAyNCAxNy44MzUzVjYuMTcxNDZDMjQuMDAwOSA1LjU5Njc4IDIzLjc3MTUgNS4wNDUzMiAyMy4zNjI0IDQuNjM4NjNDMjIuOTUzMyA0LjIzMTk0IDIyLjM5ODEgNC4wMDM0MiAyMS44MTkxIDQuMDAzNDJaIiBmaWxsPSIjRUQ1NTY1IiAvPjwvc3ZnPg==) */
const FlagFrance = React.forwardRef<FlagFranceRef, FlagFranceProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/France" ref={ref}><path d="M2.18088 4.0034C0.976415 4.0034 0 4.97255 0 6.16805V17.8319C0 19.0274 0.976415 19.9966 2.18088 19.9966H8.01029C8.01029 14.6644 8.01029 9.33219 8.01029 4L2.18088 4.0034Z" fill="#4758A9" /><path d="M8.00391 4.00342C8.00391 9.33561 8.00391 14.6678 8.00391 20H16.0108C16.0108 14.6678 16.0108 9.33561 16.0108 4.00342H8.00391Z" fill="white" /><path d="M21.8191 4.00342H16.0068C16.0068 9.33561 16.0068 14.6678 16.0068 20H21.8191C23.0236 20 24 19.0308 24 17.8353V6.17146C24.0009 5.59678 23.7715 5.04532 23.3624 4.63863C22.9533 4.23194 22.3981 4.00342 21.8191 4.00342Z" fill="#ED5565" /></IconBase>)
FlagFrance.displayName = definePortfolioDisplayName("FlagFrance")

export { FlagFrance }