/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagMozambiqueProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagMozambiqueRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMC4wMDI5Mjk2OSA2LjI2MDkxVjkuMzI1MzlIMjMuOTk5NVY2LjI2MDkxQzIzLjk5OTUgNS4wMTIyNCAyMi45ODA0IDQgMjEuNzIzMyA0SDIuMjY4ODlDMS4wMTU3NyA0LjAwNTYyIDAuMDAyOTE2OSA1LjAxNjIyIDAuMDAyOTI5NjkgNi4yNjA5MVoiIGZpbGw9IiM1N0E4NjMiIC8+PHBhdGggZD0iTTAuMDAzOTA2MjUgMTQuNjcxMUgyNC4wMDA1VjkuMzQ5MTJIMC4wMDM5MDYyNVYxNC42NzExWiIgZmlsbD0iIzQzNEE1NCIgLz48cGF0aCBkPSJNMC4wMDM5MDYyNSAxNy43MzlDMC4wMDM5MDYyNSAxOC45ODc3IDEuMDIzMDIgMTkuOTk5OSAyLjI4MDE1IDE5Ljk5OTlIMjEuNzI0MkMyMi45ODE0IDE5Ljk5OTkgMjQuMDAwNSAxOC45ODc3IDI0LjAwMDUgMTcuNzM5VjE0LjY3NDZIMC4wMDM5MDYyNVYxNy43MzlaIiBmaWxsPSIjRjZENjYwIiAvPjxwYXRoIGQ9Ik0yNC4wMDA1IDE0LjUwMUgwLjAwMzkwNjI1VjE0Ljg0MTVIMjQuMDAwNVYxNC41MDFaIiBmaWxsPSJ3aGl0ZSIgLz48cGF0aCBkPSJNMjQuMDAwNSA5LjUwNTc4SDAuMDAzOTA2MjVWOS4xNjUyOEgyNC4wMDA1VjkuNTA1NzhaIiBmaWxsPSJ3aGl0ZSIgLz48cGF0aCBkPSJNMC43MzAxODEgNC41NTE3NkMwLjI2NTc5NSA0Ljk2MTQgNC4wMzAwOWUtMDUgNS41NDg4MiAwIDYuMTY1NzJWMTcuODM0NkM0LjAzMDA5ZS0wNSAxOC40NTE1IDAuMjY1Nzk1IDE5LjAzODkgMC43MzAxODEgMTkuNDQ4NUw5LjU5ODYzIDExLjk5ODRMMC43MzAxODEgNC41NTE3NloiIGZpbGw9IiNFRDU1NjUiIC8+PC9zdmc+) */
const FlagMozambique = React.forwardRef<FlagMozambiqueRef, FlagMozambiqueProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Mozambique" ref={ref}><path d="M0.00292969 6.26091V9.32539H23.9995V6.26091C23.9995 5.01224 22.9804 4 21.7233 4H2.26889C1.01577 4.00562 0.0029169 5.01622 0.00292969 6.26091Z" fill="#57A863" /><path d="M0.00390625 14.6711H24.0005V9.34912H0.00390625V14.6711Z" fill="#434A54" /><path d="M0.00390625 17.739C0.00390625 18.9877 1.02302 19.9999 2.28015 19.9999H21.7242C22.9814 19.9999 24.0005 18.9877 24.0005 17.739V14.6746H0.00390625V17.739Z" fill="#F6D660" /><path d="M24.0005 14.501H0.00390625V14.8415H24.0005V14.501Z" fill="white" /><path d="M24.0005 9.50578H0.00390625V9.16528H24.0005V9.50578Z" fill="white" /><path d="M0.730181 4.55176C0.265795 4.9614 4.03009e-05 5.54882 0 6.16572V17.8346C4.03009e-05 18.4515 0.265795 19.0389 0.730181 19.4485L9.59863 11.9984L0.730181 4.55176Z" fill="#ED5565" /></IconBase>)
FlagMozambique.displayName = definePortfolioDisplayName("FlagMozambique")

export { FlagMozambique }