/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagNigerProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagNigerRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI2MDQzVjkuMzI0MjZIMjRWNi4yNjA0M0MyNCA1LjAxMjAzIDIyLjk4MDcgNCAyMS43MjM0IDRIMi4yNzY1N0MxLjAxOTI2IDQgMCA1LjAxMjAzIDAgNi4yNjA0M1oiIGZpbGw9IiNGQzZFNTEiIC8+PHBhdGggZD0iTTAgMTQuNjcyM0gyNFY5LjMzNDQ3SDBWMTQuNjcyM1oiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0wIDE3LjczOTZDMCAxOC45ODggMS4wMTkyNiAyMCAyLjI3NjU3IDIwSDIxLjcyMzRDMjIuOTgwNyAyMCAyNCAxOC45ODggMjQgMTcuNzM5NlYxNC42NzU4SDBWMTcuNzM5NloiIGZpbGw9IiM1N0E4NjMiIC8+PHBhdGggZD0iTTExLjk5OTQgMTMuMzYxNkMxMi43NTY4IDEzLjM2MTYgMTMuMzcwOCAxMi43NTE5IDEzLjM3MDggMTEuOTk5OUMxMy4zNzA4IDExLjI0NzggMTIuNzU2OCAxMC42MzgyIDExLjk5OTQgMTAuNjM4MkMxMS4yNDE5IDEwLjYzODIgMTAuNjI3OSAxMS4yNDc4IDEwLjYyNzkgMTEuOTk5OUMxMC42Mjc5IDEyLjc1MTkgMTEuMjQxOSAxMy4zNjE2IDExLjk5OTQgMTMuMzYxNloiIGZpbGw9IiNGQzZFNTEiIC8+PC9zdmc+) */
const FlagNiger = React.forwardRef<FlagNigerRef, FlagNigerProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Niger" ref={ref}><path d="M0 6.26043V9.32426H24V6.26043C24 5.01203 22.9807 4 21.7234 4H2.27657C1.01926 4 0 5.01203 0 6.26043Z" fill="#FC6E51" /><path d="M0 14.6723H24V9.33447H0V14.6723Z" fill="white" /><path d="M0 17.7396C0 18.988 1.01926 20 2.27657 20H21.7234C22.9807 20 24 18.988 24 17.7396V14.6758H0V17.7396Z" fill="#57A863" /><path d="M11.9994 13.3616C12.7568 13.3616 13.3708 12.7519 13.3708 11.9999C13.3708 11.2478 12.7568 10.6382 11.9994 10.6382C11.2419 10.6382 10.6279 11.2478 10.6279 11.9999C10.6279 12.7519 11.2419 13.3616 11.9994 13.3616Z" fill="#FC6E51" /></IconBase>)
FlagNiger.displayName = definePortfolioDisplayName("FlagNiger")

export { FlagNiger }