/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagJapanProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagJapanRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE5NCA0SDIuMTgwNTdDMC45NzYyNzUgNCAwIDQuOTY5MzUgMCA2LjE2NTExVjE3LjgzNDlDMCAxOS4wMzA2IDAuOTc2Mjc1IDIwIDIuMTgwNTcgMjBIMjEuODE5NEMyMy4wMjM3IDIwIDI0IDE5LjAzMDYgMjQgMTcuODM0OVY2LjE2NTExQzI0IDQuOTY5MzUgMjMuMDIzNyA0IDIxLjgxOTQgNFoiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0xMi4wMDAzIDE1LjIzNEMxMy43OTkyIDE1LjIzNCAxNS4yNTc0IDEzLjc4NiAxNS4yNTc0IDExLjk5OTlDMTUuMjU3NCAxMC4yMTM4IDEzLjc5OTIgOC43NjU4NyAxMi4wMDAzIDguNzY1ODdDMTAuMjAxNCA4Ljc2NTg3IDguNzQzMTYgMTAuMjEzOCA4Ljc0MzE2IDExLjk5OTlDOC43NDMxNiAxMy43ODYgMTAuMjAxNCAxNS4yMzQgMTIuMDAwMyAxNS4yMzRaIiBmaWxsPSIjRUQ1NTY1IiAvPjwvc3ZnPg==) */
const FlagJapan = React.forwardRef<FlagJapanRef, FlagJapanProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Japan" ref={ref}><path d="M21.8194 4H2.18057C0.976275 4 0 4.96935 0 6.16511V17.8349C0 19.0306 0.976275 20 2.18057 20H21.8194C23.0237 20 24 19.0306 24 17.8349V6.16511C24 4.96935 23.0237 4 21.8194 4Z" fill="white" /><path d="M12.0003 15.234C13.7992 15.234 15.2574 13.786 15.2574 11.9999C15.2574 10.2138 13.7992 8.76587 12.0003 8.76587C10.2014 8.76587 8.74316 10.2138 8.74316 11.9999C8.74316 13.786 10.2014 15.234 12.0003 15.234Z" fill="#ED5565" /></IconBase>)
FlagJapan.displayName = definePortfolioDisplayName("FlagJapan")

export { FlagJapan }