/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagSudanProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagSudanRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI2MDkxVjkuMzI1MzlIMjRWNi4yNjA5MUMyNCA1LjAxMjI0IDIyLjk4MDcgNCAyMS43MjM0IDRIMi4yNzY1N0MxLjAxOTI2IDQgMCA1LjAxMjI0IDAgNi4yNjA5MVoiIGZpbGw9IiNFRDU1NjUiIC8+PHBhdGggZD0iTTAgMTQuNjcxM0gyNFY5LjMzNTY5SDBWMTQuNjcxM1oiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0wIDE3LjczOUMwIDE4Ljk4NzcgMS4wMTkyNiAxOS45OTk5IDIuMjc2NTcgMTkuOTk5OUgyMS43MjM0QzIyLjk4MDcgMTkuOTk5OSAyNCAxOC45ODc3IDI0IDE3LjczOVYxNC42NzQ2SDBWMTcuNzM5WiIgZmlsbD0iIzQzNEE1NCIgLz48cGF0aCBkPSJNMC43NjExNDMgNC41NzU0NEMwLjI3NjYzNyA1LjAwMzQ4IC0wLjAwMDM3NjY0OCA1LjYxNjkgMy44NDM3M2UtMDcgNi4yNjA5VjE3Ljc0MjVDLTAuMDAwMzc2NjQ4IDE4LjM4NjUgMC4yNzY2MzcgMTguOTk5OSAwLjc2MTE0MyAxOS40MjhMMTEuMzE0MyAxMS45OTQ5TDAuNzYxMTQzIDQuNTc1NDRaIiBmaWxsPSIjNTdBODYzIiAvPjwvc3ZnPg==) */
const FlagSudan = React.forwardRef<FlagSudanRef, FlagSudanProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Sudan" ref={ref}><path d="M0 6.26091V9.32539H24V6.26091C24 5.01224 22.9807 4 21.7234 4H2.27657C1.01926 4 0 5.01224 0 6.26091Z" fill="#ED5565" /><path d="M0 14.6713H24V9.33569H0V14.6713Z" fill="white" /><path d="M0 17.739C0 18.9877 1.01926 19.9999 2.27657 19.9999H21.7234C22.9807 19.9999 24 18.9877 24 17.739V14.6746H0V17.739Z" fill="#434A54" /><path d="M0.761143 4.57544C0.276637 5.00348 -0.000376648 5.6169 3.84373e-07 6.2609V17.7425C-0.000376648 18.3865 0.276637 18.9999 0.761143 19.428L11.3143 11.9949L0.761143 4.57544Z" fill="#57A863" /></IconBase>)
FlagSudan.displayName = definePortfolioDisplayName("FlagSudan")

export { FlagSudan }