/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagZamibiaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagZamibiaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE5MyA0SDIuMTgwNTZDMC45NzYyNzEgNCAwIDQuOTY5MzUgMCA2LjE2NTExVjE3LjgzNDlDMCAxOS4wMzA2IDAuOTc2MjcxIDIwIDIuMTgwNTYgMjBIMjEuODE5M0MyMy4wMjM2IDIwIDIzLjk5OTkgMTkuMDMwNiAyMy45OTk5IDE3LjgzNDlWNi4xNjUxMUMyMy45OTk5IDQuOTY5MzUgMjMuMDIzNiA0IDIxLjgxOTMgNFoiIGZpbGw9IiM1MkMxNjIiIC8+PHBhdGggZD0iTTIwLjU3MTMgMjAuMDAwMUgyMS44MTkzQzIyLjM5NzYgMjAuMDAwMSAyMi45NTIyIDE5Ljc3MiAyMy4zNjEyIDE5LjM2NTlDMjMuNzcwMSAxOC45NTk5IDIzLjk5OTggMTguNDA5MiAyMy45OTk4IDE3LjgzNVYxMC44MDg2SDIwLjU3MTNWMjAuMDAwMVoiIGZpbGw9IiNGNkQ2NjAiIC8+PHBhdGggZD0iTTE3LjE0MjYgMjAuMDAwMVYxMC44MDg2SDIwLjU3MTFWMjAuMDAwMUgxNy4xNDI2WiIgZmlsbD0iIzQzNEE1NCIgLz48cGF0aCBkPSJNMTMuNzEzOSAyMC4wMDAxVjEwLjgwODZIMTcuMTQyNFYyMC4wMDAxSDEzLjcxMzlaIiBmaWxsPSIjRUQ1NTY1IiAvPjxwYXRoIGQ9Ik0xNi40NjM5IDcuMDE5NjFMMTcuMTczNiA1Ljk0NzI3QzE3LjI3NDggNS44MDc1OCAxNy40MzI4IDUuNzE5MTkgMTcuNjA1NiA1LjcwNTU3SDE5LjMxOTlMMTkuODg5IDkuMTA5ODJIMTcuMjU5M0wxNy42MDIxIDcuMDE5NjFIMTYuNDY3M0gxNi40NjM5WiIgZmlsbD0iI0Y2RDY2MCIgLz48L3N2Zz4=) */
const FlagZamibia = React.forwardRef<FlagZamibiaRef, FlagZamibiaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Zamibia" ref={ref}><path d="M21.8193 4H2.18056C0.976271 4 0 4.96935 0 6.16511V17.8349C0 19.0306 0.976271 20 2.18056 20H21.8193C23.0236 20 23.9999 19.0306 23.9999 17.8349V6.16511C23.9999 4.96935 23.0236 4 21.8193 4Z" fill="#52C162" /><path d="M20.5713 20.0001H21.8193C22.3976 20.0001 22.9522 19.772 23.3612 19.3659C23.7701 18.9599 23.9998 18.4092 23.9998 17.835V10.8086H20.5713V20.0001Z" fill="#F6D660" /><path d="M17.1426 20.0001V10.8086H20.5711V20.0001H17.1426Z" fill="#434A54" /><path d="M13.7139 20.0001V10.8086H17.1424V20.0001H13.7139Z" fill="#ED5565" /><path d="M16.4639 7.01961L17.1736 5.94727C17.2748 5.80758 17.4328 5.71919 17.6056 5.70557H19.3199L19.889 9.10982H17.2593L17.6021 7.01961H16.4673H16.4639Z" fill="#F6D660" /></IconBase>)
FlagZamibia.displayName = definePortfolioDisplayName("FlagZamibia")

export { FlagZamibia }