/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagBangladeshProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagBangladeshRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE5NCA0SDIuMTgwNTdDMC45NzYyNzUgNCAwIDQuOTY5MzUgMCA2LjE2NTExVjE3LjgzNDlDMCAxOS4wMzA2IDAuOTc2Mjc1IDIwIDIuMTgwNTcgMjBIMjEuODE5NEMyMy4wMjM3IDIwIDI0IDE5LjAzMDYgMjQgMTcuODM0OVY2LjE2NTExQzI0IDQuOTY5MzUgMjMuMDIzNyA0IDIxLjgxOTQgNFoiIGZpbGw9IiM1N0E4NjMiIC8+PHBhdGggZD0iTTEyLjE3MTUgMTYuMjU1M0MxNC41Mzg0IDE2LjI1NTMgMTYuNDU3MiAxNC4zNTAxIDE2LjQ1NzIgMTEuOTk5OUMxNi40NTcyIDkuNjQ5OCAxNC41Mzg0IDcuNzQ0NjMgMTIuMTcxNSA3Ljc0NDYzQzkuODA0NTIgNy43NDQ2MyA3Ljg4NTc0IDkuNjQ5OCA3Ljg4NTc0IDExLjk5OTlDNy44ODU3NCAxNC4zNTAxIDkuODA0NTIgMTYuMjU1MyAxMi4xNzE1IDE2LjI1NTNaIiBmaWxsPSIjRUQ1NTY1IiAvPjwvc3ZnPg==) */
const FlagBangladesh = React.forwardRef<FlagBangladeshRef, FlagBangladeshProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Bangladesh" ref={ref}><path d="M21.8194 4H2.18057C0.976275 4 0 4.96935 0 6.16511V17.8349C0 19.0306 0.976275 20 2.18057 20H21.8194C23.0237 20 24 19.0306 24 17.8349V6.16511C24 4.96935 23.0237 4 21.8194 4Z" fill="#57A863" /><path d="M12.1715 16.2553C14.5384 16.2553 16.4572 14.3501 16.4572 11.9999C16.4572 9.6498 14.5384 7.74463 12.1715 7.74463C9.80452 7.74463 7.88574 9.6498 7.88574 11.9999C7.88574 14.3501 9.80452 16.2553 12.1715 16.2553Z" fill="#ED5565" /></IconBase>)
FlagBangladesh.displayName = definePortfolioDisplayName("FlagBangladesh")

export { FlagBangladesh }