/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagRussiaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagRussiaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMCA2LjI1ODVWOS4zMTk3M0gyNFY2LjI1ODVDMjQgNS4wMTExNyAyMi45ODA3IDQgMjEuNzIzNCA0SDIuMjc2NTdDMS4wMTkyNiA0IDAgNS4wMTExNyAwIDYuMjU4NVoiIGZpbGw9IndoaXRlIiAvPjxwYXRoIGQ9Ik0wIDE0LjY3MzRIMjRWOS4zNDM1MUgwVjE0LjY3MzRaIiBmaWxsPSIjNEE4OURDIiAvPjxwYXRoIGQ9Ik0wIDE3Ljc0MTZDMCAxOC45ODkgMS4wMTkyNiAyMC4wMDAxIDIuMjc2NTcgMjAuMDAwMUgyMS43MjM0QzIyLjk4MDcgMjAuMDAwMSAyNCAxOC45ODkgMjQgMTcuNzQxNlYxNC42ODA0SDBWMTcuNzQxNloiIGZpbGw9IiNFRDU1NjUiIC8+PC9zdmc+) */
const FlagRussia = React.forwardRef<FlagRussiaRef, FlagRussiaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Russia" ref={ref}><path d="M0 6.2585V9.31973H24V6.2585C24 5.01117 22.9807 4 21.7234 4H2.27657C1.01926 4 0 5.01117 0 6.2585Z" fill="white" /><path d="M0 14.6734H24V9.34351H0V14.6734Z" fill="#4A89DC" /><path d="M0 17.7416C0 18.989 1.01926 20.0001 2.27657 20.0001H21.7234C22.9807 20.0001 24 18.989 24 17.7416V14.6804H0V17.7416Z" fill="#ED5565" /></IconBase>)
FlagRussia.displayName = definePortfolioDisplayName("FlagRussia")

export { FlagRussia }