/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type FlagMadagascarProps = React.ComponentPropsWithoutRef<typeof IconBase>
type FlagMadagascarRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODE5NCA0LjAxMDI2SDIuMTg0QzAuOTgxMDM5IDQuMDA4MzcgMC4wMDM3ODE0MSA0Ljk3MzUxIDAgNi4xNjcxOFYxMi4xNjg1SDI0VjYuMTY3MThDMjMuOTk2MiA0Ljk3NDg0IDIzLjAyMTEgNC4wMTAyNSAyMS44MTk0IDQuMDEwMjZaIiBmaWxsPSIjRUQ1NTY1IiAvPjxwYXRoIGQ9Ik0wIDE3LjgzNjRDMCAxOS4wMzE0IDAuOTc2Mjc1IDIwLjAwMDEgMi4xODA1NyAyMC4wMDAxSDIxLjgxOTRDMjMuMDIzNyAyMC4wMDAxIDI0IDE5LjAzMTQgMjQgMTcuODM2NFYxMi4xNzUzSDBWMTcuODM2NFoiIGZpbGw9IiM1MkMxNjIiIC8+PHBhdGggZD0iTTIuMTg0IDQuMDEwMjFDMC45ODEwMzkgNC4wMDgzMiAwLjAwMzc4MTQxIDQuOTczNDYgMCA2LjE2NzEzVjE3LjgyNjFDMCAxOS4wMjExIDAuOTc2Mjc1IDE5Ljk4OTggMi4xODA1NyAxOS45ODk4SDcuODg1NzFWNEwyLjE4NCA0LjAxMDIxWiIgZmlsbD0id2hpdGUiIC8+PC9zdmc+) */
const FlagMadagascar = React.forwardRef<FlagMadagascarRef, FlagMadagascarProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="Full Color/Flag/Madagascar" ref={ref}><path d="M21.8194 4.01026H2.184C0.981039 4.00837 0.00378141 4.97351 0 6.16718V12.1685H24V6.16718C23.9962 4.97484 23.0211 4.01025 21.8194 4.01026Z" fill="#ED5565" /><path d="M0 17.8364C0 19.0314 0.976275 20.0001 2.18057 20.0001H21.8194C23.0237 20.0001 24 19.0314 24 17.8364V12.1753H0V17.8364Z" fill="#52C162" /><path d="M2.184 4.01021C0.981039 4.00832 0.00378141 4.97346 0 6.16713V17.8261C0 19.0211 0.976275 19.9898 2.18057 19.9898H7.88571V4L2.184 4.01021Z" fill="white" /></IconBase>)
FlagMadagascar.displayName = definePortfolioDisplayName("FlagMadagascar")

export { FlagMadagascar }