/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWeatherRainProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWeatherRainRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTMuOTYwOCAxNS4wNjk1TDExLjQ5OTggMTlNMjEuNDA0NiAxMy40NDc1TDE4LjQ5OTggMThNOC45MjYyNCAyMi4yNjk3TDguMjYxMzUgMjMuMjE5Mk04LjI2MTM1IDE1LjAwNDNMMy43OTgzNCAyMS41MDg4TTMuOTk5ODIgMTIuODQ0MkwxLjE1OTE4IDE2LjUzMTJNNy4zMDE4IDE0Ljc1NTVDNC4yMTU1NiAxMy44NzM2IDEuOTc1MjIgMTEuMjMzOCAxLjk3NTIyIDguMTE0MzNDMS45NzUyMiA0LjI3MzEgNS4zNzIyMyAxLjE1OTE4IDkuNTYyNjUgMS4xNTkxOEMxMi4zNzExIDEuMTU5MTggMTQuODIzMSAyLjU1Nzg1IDE2LjEzNSA0LjYzNjc1SDE3LjYyNDNDMjAuNTA1MiA0LjYzNjc1IDIyLjg0MDcgNi45NzIyIDIyLjg0MDcgOS44NTMxMUMyMi44NDA3IDEyLjczNCAyMC41MDUyIDE1LjA2OTUgMTcuNjI0MyAxNS4wNjk1SDkuMDg4NDNDOC40NjA4MyAxNS4wNjk1IDcuODU5MTIgMTQuOTU4NiA3LjMwMTggMTQuNzU1NVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineWeatherRain = React.forwardRef<IconLineWeatherRainRef, IconLineWeatherRainProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-weather-rain" ref={ref}><path d="M13.9608 15.0695L11.4998 19M21.4046 13.4475L18.4998 18M8.92624 22.2697L8.26135 23.2192M8.26135 15.0043L3.79834 21.5088M3.99982 12.8442L1.15918 16.5312M7.3018 14.7555C4.21556 13.8736 1.97522 11.2338 1.97522 8.11433C1.97522 4.2731 5.37223 1.15918 9.56265 1.15918C12.3711 1.15918 14.8231 2.55785 16.135 4.63675H17.6243C20.5052 4.63675 22.8407 6.9722 22.8407 9.85311C22.8407 12.734 20.5052 15.0695 17.6243 15.0695H9.08843C8.46083 15.0695 7.85912 14.9586 7.3018 14.7555Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineWeatherRain.displayName = definePortfolioDisplayName("IconLineWeatherRain")

export { IconLineWeatherRain }