/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCircleActionsInfoProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCircleActionsInfoRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTEyIDIzQzE4LjA3NTEgMjMgMjMgMTguMDc1MSAyMyAxMkMyMyA1LjkyNDg3IDE4LjA3NTEgMSAxMiAxQzUuOTI0ODcgMSAxIDUuOTI0ODcgMSAxMkMxIDE4LjA3NTEgNS45MjQ4NyAyMyAxMiAyM1pNMTMuMjE4NyA4LjIwM0MxMy45MzA2IDguMjAzIDE0LjUwNzggNy42MjU4NyAxNC41MDc4IDYuOTEzOTRDMTQuNTA3OCA2LjIwMjAxIDEzLjkzMDYgNS42MjQ4OCAxMy4yMTg3IDUuNjI0ODhDMTIuNTA2OCA1LjYyNDg4IDExLjkyOTcgNi4yMDIwMSAxMS45Mjk3IDYuOTEzOTRDMTEuOTI5NyA3LjYyNTg3IDEyLjUwNjggOC4yMDMgMTMuMjE4NyA4LjIwM1pNOS4wOTM3MiA5Ljc0OTg4SDEzLjk5NkwxMS45NDg5IDE1LjM4ODVDMTEuOTQ4OSAxNS4zODg1IDExLjk0ODkgMTUuOTAxMyAxMi40NjA2IDE1LjkwMTNDMTIuOTcyNCAxNS45MDEzIDEzLjk5NiAxNC44NzU2IDEzLjk5NiAxNC44NzU2TDE0Ljc2NTYgMTUuNjc5NkMxNC43NjU2IDE1LjY3OTYgMTMuMzUxNiAxNy43ODAxIDExLjk0ODkgMTcuOTUyN0MxMS4xMzEgMTguMDUzNCAxMC40NjkgMTguMDM4OSA5LjkwMTg0IDE3LjQzOTlDOS41OTQyNiAxNy4xMTUgOS40ODcwMiAxNi44NTEzIDkuMzkwMDcgMTYuNDE0MkM5LjMwMzM2IDE2LjAyMzEgOS4zOTAwNyAxNS4zODg1IDkuMzkwMDcgMTUuMzg4NUwxMS4xNTYyIDExLjI5NjhMOC41NzgwOSAxMS4wMzg5TDkuMDkzNzIgOS43NDk4OFoiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFilledCircleActionsInfo = React.forwardRef<IconFilledCircleActionsInfoRef, IconFilledCircleActionsInfoProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-circle-actions-info" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23ZM13.2187 8.203C13.9306 8.203 14.5078 7.62587 14.5078 6.91394C14.5078 6.20201 13.9306 5.62488 13.2187 5.62488C12.5068 5.62488 11.9297 6.20201 11.9297 6.91394C11.9297 7.62587 12.5068 8.203 13.2187 8.203ZM9.09372 9.74988H13.996L11.9489 15.3885C11.9489 15.3885 11.9489 15.9013 12.4606 15.9013C12.9724 15.9013 13.996 14.8756 13.996 14.8756L14.7656 15.6796C14.7656 15.6796 13.3516 17.7801 11.9489 17.9527C11.131 18.0534 10.469 18.0389 9.90184 17.4399C9.59426 17.115 9.48702 16.8513 9.39007 16.4142C9.30336 16.0231 9.39007 15.3885 9.39007 15.3885L11.1562 11.2968L8.57809 11.0389L9.09372 9.74988Z" fill="currentColor" /></IconBase>)
IconFilledCircleActionsInfo.displayName = definePortfolioDisplayName("IconFilledCircleActionsInfo")

export { IconFilledCircleActionsInfo }