/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineReceiptProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineReceiptRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTQuNSA4TDkuNSAxM005LjUgOC4wMDk5OFY4TTE0LjUgMTMuMDFWMTNNMjAgMjIuNVYzQzIwIDEuODk1NDMgMTkuMTA0NiAxIDE4IDFINkM0Ljg5NTQzIDEgNCAxLjg5NTQzIDQgM1YyMi41TDggMjFMMTIgMjNMMTYgMjFMMjAgMjIuNVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineReceipt = React.forwardRef<IconLineReceiptRef, IconLineReceiptProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-receipt-" ref={ref}><path d="M14.5 8L9.5 13M9.5 8.00998V8M14.5 13.01V13M20 22.5V3C20 1.89543 19.1046 1 18 1H6C4.89543 1 4 1.89543 4 3V22.5L8 21L12 23L16 21L20 22.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineReceipt.displayName = definePortfolioDisplayName("IconLineReceipt")

export { IconLineReceipt }