/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWeatherWaterDropProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWeatherWaterDropRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjAgMTVDMjAgMTkuNDE4MyAxNi40MTgzIDIzIDEyIDIzQzcuNTgxNzIgMjMgNCAxOS40MTgzIDQgMTVDNCAxMC41ODE3IDEyIDEuNSAxMiAxLjVDMTIgMS41IDIwIDEwLjU4MTcgMjAgMTVaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineWeatherWaterDrop = React.forwardRef<IconLineWeatherWaterDropRef, IconLineWeatherWaterDropProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-weather-water-drop" ref={ref}><path d="M20 15C20 19.4183 16.4183 23 12 23C7.58172 23 4 19.4183 4 15C4 10.5817 12 1.5 12 1.5C12 1.5 20 10.5817 20 15Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineWeatherWaterDrop.displayName = definePortfolioDisplayName("IconLineWeatherWaterDrop")

export { IconLineWeatherWaterDrop }