/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineThumbsDownProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineThumbsDownRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNiAxLjI1VjEzLjQyNzJNMTQuMTMzNyAxNi45MjQ2TDE0LjUwNDEgMjAuMDg0NkMxNC43MDE1IDIxLjc2OTggMTMuMzg0NyAyMy4yNSAxMS42ODc5IDIzLjI1QzExLjExOTIgMjMuMjUgMTAuNjA1NiAyMi45MTAyIDEwLjM4MzEgMjIuMzg2OEw3LjAxNzUzIDE0LjQ2NzdDNi43MDM3NCAxMy43Mjk0IDUuOTc5MTIgMTMuMjUgNS4xNzY4NyAxMy4yNUg0QzIuMzQzMTUgMTMuMjUgMSAxMS45MDY5IDEgMTAuMjVWNC4yNUMxIDIuNTkzMTUgMi4zNDMxNSAxLjI1IDQgMS4yNUgxNy43MzcxQzE5LjA3NjUgMS4yNSAyMC4yNTM3IDIuMTM3OTMgMjAuNjIxNyAzLjQyNTg0TDIyLjkwNzQgMTEuNDI1OEMyMy40NTQ5IDEzLjM0MjMgMjIuMDE1OSAxNS4yNSAyMC4wMjI4IDE1LjI1SDE1LjYyMzVDMTQuNzI1OSAxNS4yNSAxNC4wMjkzIDE2LjAzMzEgMTQuMTMzNyAxNi45MjQ2WiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgLz48L3N2Zz4=) */
const IconLineThumbsDown = React.forwardRef<IconLineThumbsDownRef, IconLineThumbsDownProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-thumbs-down" ref={ref}><path d="M6 1.25V13.4272M14.1337 16.9246L14.5041 20.0846C14.7015 21.7698 13.3847 23.25 11.6879 23.25C11.1192 23.25 10.6056 22.9102 10.3831 22.3868L7.01753 14.4677C6.70374 13.7294 5.97912 13.25 5.17687 13.25H4C2.34315 13.25 1 11.9069 1 10.25V4.25C1 2.59315 2.34315 1.25 4 1.25H17.7371C19.0765 1.25 20.2537 2.13793 20.6217 3.42584L22.9074 11.4258C23.4549 13.3423 22.0159 15.25 20.0228 15.25H15.6235C14.7259 15.25 14.0293 16.0331 14.1337 16.9246Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineThumbsDown.displayName = definePortfolioDisplayName("IconLineThumbsDown")

export { IconLineThumbsDown }