/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCryptoLitecoinLtcProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCryptoLitecoinLtcRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTI0IDEyQzI0IDE4LjYyNzQgMTguNjI3NCAyNCAxMiAyNEM1LjM3MjU4IDI0IDAgMTguNjI3NCAwIDEyQzAgNS4zNzI1OCA1LjM3MjU4IDAgMTIgMEMxOC42Mjc0IDAgMjQgNS4zNzI1OCAyNCAxMlpNNi45MzkgMThMNy44MjAyNSAxNC40MTA1TDYuNzUgMTQuODI2TDcuMjY2IDEyLjc1NjhMOC4zNDkgMTIuMzIxOEw5LjkwOTc1IDZIMTMuNzU2NUwxMi42MTczIDEwLjY0N0wxMy42NzQ3IDEwLjIxODhMMTMuMTY0NyAxMi4yODEyTDEyLjA5NDUgMTIuNzA5NUwxMS40NTg1IDE1LjMyMThIMTcuMjVMMTYuNTk1MyAxOEg2LjkzOVoiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFilledCryptoLitecoinLtc = React.forwardRef<IconFilledCryptoLitecoinLtcRef, IconFilledCryptoLitecoinLtcProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-crypto-litecoin-ltc" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0C18.6274 0 24 5.37258 24 12ZM6.939 18L7.82025 14.4105L6.75 14.826L7.266 12.7568L8.349 12.3218L9.90975 6H13.7565L12.6173 10.647L13.6747 10.2188L13.1647 12.2812L12.0945 12.7095L11.4585 15.3218H17.25L16.5953 18H6.939Z" fill="currentColor" /></IconBase>)
IconFilledCryptoLitecoinLtc.displayName = definePortfolioDisplayName("IconFilledCryptoLitecoinLtc")

export { IconFilledCryptoLitecoinLtc }