/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineSaveProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineSaveRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNiAzVjdDNiA4LjEwNDU3IDYuODk1NDMgOSA4IDlIMTJDMTMuMTA0NiA5IDE0IDguMTA0NTcgMTQgN1YzTTggMjFWMTZDOCAxNC44OTU0IDguODk1NDMgMTQgMTAgMTRIMTRDMTUuMTA0NiAxNCAxNiAxNC44OTU0IDE2IDE2VjIxTTE1LjE3MTYgM0g1QzMuODk1NDMgMyAzIDMuODk1NDMgMyA1VjE5QzMgMjAuMTA0NiAzLjg5NTQzIDIxIDUgMjFIMTlDMjAuMTA0NiAyMSAyMSAyMC4xMDQ2IDIxIDE5VjguODI4NDNDMjEgOC4yOTc5OSAyMC43ODkzIDcuNzg5MjkgMjAuNDE0MiA3LjQxNDIxTDE2LjU4NTggMy41ODU3OUMxNi4yMTA3IDMuMjEwNzEgMTUuNzAyIDMgMTUuMTcxNiAzWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgLz48L3N2Zz4=) */
const IconLineSave = React.forwardRef<IconLineSaveRef, IconLineSaveProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-save" ref={ref}><path d="M6 3V7C6 8.10457 6.89543 9 8 9H12C13.1046 9 14 8.10457 14 7V3M8 21V16C8 14.8954 8.89543 14 10 14H14C15.1046 14 16 14.8954 16 16V21M15.1716 3H5C3.89543 3 3 3.89543 3 5V19C3 20.1046 3.89543 21 5 21H19C20.1046 21 21 20.1046 21 19V8.82843C21 8.29799 20.7893 7.78929 20.4142 7.41421L16.5858 3.58579C16.2107 3.21071 15.702 3 15.1716 3Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineSave.displayName = definePortfolioDisplayName("IconLineSave")

export { IconLineSave }