/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledFilledAlertInfoProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledFilledAlertInfoRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTEyIDIzQzE4LjA3NTEgMjMgMjMgMTguMDc1MSAyMyAxMkMyMyA1LjkyNDg3IDE4LjA3NTEgMSAxMiAxQzUuOTI0ODcgMSAxIDUuOTI0ODcgMSAxMkMxIDE4LjA3NTEgNS45MjQ4NyAyMyAxMiAyM1pNMTIgNkMxMi41NTIzIDYgMTMgNi40NDc3MiAxMyA3VjEyQzEzIDEyLjU1MjMgMTIuNTUyMyAxMyAxMiAxM0MxMS40NDc3IDEzIDExIDEyLjU1MjMgMTEgMTJWN0MxMSA2LjQ0NzcyIDExLjQ0NzcgNiAxMiA2Wk0xMiAxNUMxMi41NTIzIDE1IDEzIDE1LjQ0NzcgMTMgMTZWMTYuNUMxMyAxNy4wNTIzIDEyLjU1MjMgMTcuNSAxMiAxNy41QzExLjQ0NzcgMTcuNSAxMSAxNy4wNTIzIDExIDE2LjVWMTZDMTEgMTUuNDQ3NyAxMS40NDc3IDE1IDEyIDE1WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledFilledAlertInfo = React.forwardRef<IconFilledFilledAlertInfoRef, IconFilledFilledAlertInfoProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-filled-alert-info" ref={ref}><path fill-rule="evenodd" clip-rule="evenodd" d="M12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23ZM12 6C12.5523 6 13 6.44772 13 7V12C13 12.5523 12.5523 13 12 13C11.4477 13 11 12.5523 11 12V7C11 6.44772 11.4477 6 12 6ZM12 15C12.5523 15 13 15.4477 13 16V16.5C13 17.0523 12.5523 17.5 12 17.5C11.4477 17.5 11 17.0523 11 16.5V16C11 15.4477 11.4477 15 12 15Z" fill="currentColor" /></IconBase>)
IconFilledFilledAlertInfo.displayName = definePortfolioDisplayName("IconFilledFilledAlertInfo")

export { IconFilledFilledAlertInfo }