/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineArrowCaretUpProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineArrowCaretUpRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTEuMDgxOCA3Ljk5MzYxQzExLjU3NjggNy40NTc4NiAxMi40MjMzIDcuNDU3ODYgMTIuOTE4MiA3Ljk5MzYxTDE2Ljk5IDEyLjQwMTRDMTcuNzI5NiAxMy4yMDIgMTcuMTYxNyAxNC40OTk2IDE2LjA3MTggMTQuNDk5Nkg3LjkyODI1QzYuODM4MzQgMTQuNDk5NiA2LjI3MDUgMTMuMjAyIDcuMDEwMDYgMTIuNDAxNEwxMS4wODE4IDcuOTkzNjFaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconLineArrowCaretUp = React.forwardRef<IconLineArrowCaretUpRef, IconLineArrowCaretUpProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-arrow-caret-up" ref={ref}><path d="M11.0818 7.99361C11.5768 7.45786 12.4233 7.45786 12.9182 7.99361L16.99 12.4014C17.7296 13.202 17.1617 14.4996 16.0718 14.4996H7.92825C6.83834 14.4996 6.2705 13.202 7.01006 12.4014L11.0818 7.99361Z" fill="currentColor" /></IconBase>)
IconLineArrowCaretUp.displayName = definePortfolioDisplayName("IconLineArrowCaretUp")

export { IconLineArrowCaretUp }