/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineDollarProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineDollarRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTcuMjUxIDcuMDk2MzdDMTcuMjUxIDcuMDk2MzcgMTYuNTk0NSAzLjkxNTY1IDEyLjAwMDQgMy45MTU2NU0xMi4wMDA0IDMuOTE1NjVDNy40MDYzOCAzLjkxNTY1IDYuMTg3MTIgNS44NDM3NSA2LjA5Mzc4IDcuMTcxODhDNi4wMDA0MyA4LjUgNi4wMDA0MiAxMS41IDEyLjAwMDQgMTEuNU0xMi4wMDA0IDMuOTE1NjVWMU0xMi4wMDA0IDMuOTE1NjVMMTIuMDAwNCAxMS41TTEyLjAwMDQgMTEuNUMxOC4wMDA0IDExLjUgMTguMDAwNCAxNSAxOC4wMDA0IDE1LjVDMTguMDAwNCAxNiAxNy45MDcxIDE5LjgxOTMgMTIuMDAwNCAxOS44MTkzTTEyLjAwMDQgMTEuNUwxMi4wMDA0IDE5LjgxOTNNMTIuMDAwNCAxOS44MTkzQzYuMDkzNzkgMTkuODE5MyA2LjA5Mzc5IDE2LjYzODUgNi4wOTM3OSAxNi42Mzg1TTEyLjAwMDQgMTkuODE5M1YyMyIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineDollar = React.forwardRef<IconLineDollarRef, IconLineDollarProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-dollar" ref={ref}><path d="M17.251 7.09637C17.251 7.09637 16.5945 3.91565 12.0004 3.91565M12.0004 3.91565C7.40638 3.91565 6.18712 5.84375 6.09378 7.17188C6.00043 8.5 6.00042 11.5 12.0004 11.5M12.0004 3.91565V1M12.0004 3.91565L12.0004 11.5M12.0004 11.5C18.0004 11.5 18.0004 15 18.0004 15.5C18.0004 16 17.9071 19.8193 12.0004 19.8193M12.0004 11.5L12.0004 19.8193M12.0004 19.8193C6.09379 19.8193 6.09379 16.6385 6.09379 16.6385M12.0004 19.8193V23" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineDollar.displayName = definePortfolioDisplayName("IconLineDollar")

export { IconLineDollar }