/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledPlayProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledPlayRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNSA1LjY1NDY3QzUgNC40ODc0MSA2LjI3NDU0IDMuNzY3NDMgNy4yNzQyNyA0LjM2OTk1TDE3LjgwMTcgMTAuNzE0NkMxOC43NjkzIDExLjI5NzggMTguNzY5MyAxMi43MDA4IDE3LjgwMTcgMTMuMjg0TDcuMjc0MjcgMTkuNjI4NkM2LjI3NDU0IDIwLjIzMTIgNSAxOS41MTEyIDUgMTguMzQzOVY1LjY1NDY3WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledPlay = React.forwardRef<IconFilledPlayRef, IconFilledPlayProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-play" ref={ref}><path d="M5 5.65467C5 4.48741 6.27454 3.76743 7.27427 4.36995L17.8017 10.7146C18.7693 11.2978 18.7693 12.7008 17.8017 13.284L7.27427 19.6286C6.27454 20.2312 5 19.5112 5 18.3439V5.65467Z" fill="currentColor" /></IconBase>)
IconFilledPlay.displayName = definePortfolioDisplayName("IconFilledPlay")

export { IconFilledPlay }