/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineItalicProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineItalicRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOCA0SDE0TTE0IDRIMjBNMTQgNEw5IDIwTTMgMjBIOU05IDIwSDE1IiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIC8+PC9zdmc+) */
const IconLineItalic = React.forwardRef<IconLineItalicRef, IconLineItalicProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-italic" ref={ref}><path d="M8 4H14M14 4H20M14 4L9 20M3 20H9M9 20H15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineItalic.displayName = definePortfolioDisplayName("IconLineItalic")

export { IconLineItalic }