/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledForwardProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledForwardRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNC4zMzIwNSA1LjI1NDQ1QzMuMzM1MjIgNC41ODk4OSAyIDUuMzA0NDggMiA2LjUwMjUyVjE2Ljg5N0MyIDE4LjA5NSAzLjMzNTIyIDE4LjgwOTYgNC4zMzIwNSAxOC4xNDVMMTEgMTMuNjk5N1YxNi44OTdDMTEgMTguMDk1MSAxMi4zMzUyIDE4LjgwOTcgMTMuMzMyIDE4LjE0NTFMMjEuMTI3OSAxMi45NDc5QzIyLjAxODUgMTIuMzU0MSAyMi4wMTg1IDExLjA0NTUgMjEuMTI3OSAxMC40NTE3TDEzLjMzMjEgNS4yNTQ1QzEyLjMzNTIgNC41ODk5NCAxMSA1LjMwNDUzIDExIDYuNTAyNTdWOS42OTk3NUw0LjMzMjA1IDUuMjU0NDVaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledForward = React.forwardRef<IconFilledForwardRef, IconFilledForwardProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-forward" ref={ref}><path d="M4.33205 5.25445C3.33522 4.58989 2 5.30448 2 6.50252V16.897C2 18.095 3.33522 18.8096 4.33205 18.145L11 13.6997V16.897C11 18.0951 12.3352 18.8097 13.332 18.1451L21.1279 12.9479C22.0185 12.3541 22.0185 11.0455 21.1279 10.4517L13.3321 5.2545C12.3352 4.58994 11 5.30453 11 6.50257V9.69975L4.33205 5.25445Z" fill="currentColor" /></IconBase>)
IconFilledForward.displayName = definePortfolioDisplayName("IconFilledForward")

export { IconFilledForward }