/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCryptoEthereumEthProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCryptoEthereumEthRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTI0IDEyQzI0IDE4LjYyNzQgMTguNjI3NCAyNCAxMiAyNEM1LjM3MjU4IDI0IDAgMTguNjI3NCAwIDEyQzAgNS4zNzI1OCA1LjM3MjU4IDAgMTIgMEMxOC42Mjc0IDAgMjQgNS4zNzI1OCAyNCAxMlpNNi43NSAxMi4xNjVMMTIuMzczMiAzTDE3Ljk5NiAxMi4xNjVMMTIuMzczMiA5LjY1MjVMNi43NSAxMi4xNjVaTTYuNzUgMTIuMTY1TDEyLjM3MzIgOS42NTM5MUwxNy45OTYgMTIuMTY1TDEyLjM3MzIgMTUuNDI5N0w2Ljc1IDEyLjE2NVpNMTcuOTk5NyAxMy4yMTE3TDEyLjM3MzIgMTYuNDc1N0w2Ljc1IDEzLjIxMTdMMTIuMzczMiAyMC45OTZMMTcuOTk5NyAxMy4yMTE3WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledCryptoEthereumEth = React.forwardRef<IconFilledCryptoEthereumEthRef, IconFilledCryptoEthereumEthProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-crypto-ethereum-eth" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0C18.6274 0 24 5.37258 24 12ZM6.75 12.165L12.3732 3L17.996 12.165L12.3732 9.6525L6.75 12.165ZM6.75 12.165L12.3732 9.65391L17.996 12.165L12.3732 15.4297L6.75 12.165ZM17.9997 13.2117L12.3732 16.4757L6.75 13.2117L12.3732 20.996L17.9997 13.2117Z" fill="currentColor" /></IconBase>)
IconFilledCryptoEthereumEth.displayName = definePortfolioDisplayName("IconFilledCryptoEthereumEth")

export { IconFilledCryptoEthereumEth }