/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledFilledSearchProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledFilledSearchRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTExIDBDNC45MjQ4NyAwIDAgNC45MjQ4NyAwIDExQzAgMTcuMDc1MSA0LjkyNDg3IDIyIDExIDIyQzEzLjMxNSAyMiAxNS40NjMgMjEuMjg0OSAxNy4yMzUgMjAuMDYzNUwxOS41ODU4IDIyLjQxNDJDMjAuMzY2OCAyMy4xOTUzIDIxLjYzMzIgMjMuMTk1MyAyMi40MTQyIDIyLjQxNDJDMjMuMTk1MyAyMS42MzMyIDIzLjE5NTMgMjAuMzY2OCAyMi40MTQyIDE5LjU4NThMMjAuMDYzNSAxNy4yMzVDMjEuMjg0OSAxNS40NjMgMjIgMTMuMzE1IDIyIDExQzIyIDQuOTI0ODcgMTcuMDc1MSAwIDExIDBaTTQgMTFDNCA3LjEzNDAxIDcuMTM0MDEgNCAxMSA0QzE0Ljg2NiA0IDE4IDcuMTM0MDEgMTggMTFDMTggMTQuODY2IDE0Ljg2NiAxOCAxMSAxOEM3LjEzNDAxIDE4IDQgMTQuODY2IDQgMTFaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledFilledSearch = React.forwardRef<IconFilledFilledSearchRef, IconFilledFilledSearchProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-filled-search" ref={ref}><path fill-rule="evenodd" clip-rule="evenodd" d="M11 0C4.92487 0 0 4.92487 0 11C0 17.0751 4.92487 22 11 22C13.315 22 15.463 21.2849 17.235 20.0635L19.5858 22.4142C20.3668 23.1953 21.6332 23.1953 22.4142 22.4142C23.1953 21.6332 23.1953 20.3668 22.4142 19.5858L20.0635 17.235C21.2849 15.463 22 13.315 22 11C22 4.92487 17.0751 0 11 0ZM4 11C4 7.13401 7.13401 4 11 4C14.866 4 18 7.13401 18 11C18 14.866 14.866 18 11 18C7.13401 18 4 14.866 4 11Z" fill="currentColor" /></IconBase>)
IconFilledFilledSearch.displayName = definePortfolioDisplayName("IconFilledFilledSearch")

export { IconFilledFilledSearch }