/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineDeviceLaptopProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineDeviceLaptopRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjMgMTVIMTYuNzVDMTUuOTYzMSAxNSAxNS4yMjIxIDE0Ljg3MDUgMTQuNzUgMTUuNUMxNC4yNzc5IDE2LjEyOTUgMTMuNTM2OSAxNiAxMi43NSAxNkgxMS41Nzg4QzEwLjczNDQgMTYgOS45MzEwNSAxNi4xMzU1IDkuMzc1IDE1LjVDOC44MTg5NSAxNC44NjQ1IDguMDE1NjQgMTUgNy4xNzEyMyAxNUgxTTIzIDE1LjQ0NDRWN0MyMyA1Ljg5NTQzIDIyLjEwNDYgNSAyMSA1SDNDMS44OTU0MyA1IDEgNS44OTU0MyAxIDdWMTUuNDQ0NEMxIDE3LjQwODEgMi41OTE4OCAxOSA0LjU1NTU2IDE5SDE5LjQ0NDRDMjEuNDA4MSAxOSAyMyAxNy40MDgxIDIzIDE1LjQ0NDRaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineDeviceLaptop = React.forwardRef<IconLineDeviceLaptopRef, IconLineDeviceLaptopProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-device-laptop" ref={ref}><path d="M23 15H16.75C15.9631 15 15.2221 14.8705 14.75 15.5C14.2779 16.1295 13.5369 16 12.75 16H11.5788C10.7344 16 9.93105 16.1355 9.375 15.5C8.81895 14.8645 8.01564 15 7.17123 15H1M23 15.4444V7C23 5.89543 22.1046 5 21 5H3C1.89543 5 1 5.89543 1 7V15.4444C1 17.4081 2.59188 19 4.55556 19H19.4444C21.4081 19 23 17.4081 23 15.4444Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineDeviceLaptop.displayName = definePortfolioDisplayName("IconLineDeviceLaptop")

export { IconLineDeviceLaptop }