/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineForwardArrowProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineForwardArrowRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTQuMjgyNyA1TDIwLjk5OTggMTJNMjAuOTk5OCAxMkwxNC4yODI3IDE5TTIwLjk5OTggMTJMMy45OTk4OCAxMi4wMzE3IiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineForwardArrow = React.forwardRef<IconLineForwardArrowRef, IconLineForwardArrowProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-forward-arrow" ref={ref}><path d="M14.2827 5L20.9998 12M20.9998 12L14.2827 19M20.9998 12L3.99988 12.0317" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineForwardArrow.displayName = definePortfolioDisplayName("IconLineForwardArrow")

export { IconLineForwardArrow }