/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWeatherPartlyCloudlyNightProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWeatherPartlyCloudlyNightRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOS41OTQwNyAxMS4yOTk4QzguOTQ5NjIgMTEuMTA1MyA4LjI2MDk1IDExLjAwMDEgNy41NDU0NiAxMS4wMDAxQzMuOTMwNSAxMS4wMDAxIDEgMTMuNjg2NCAxIDE3LjAwMDFDMSAxOS42OTExIDIuOTMyNjUgMjEuOTY4NCA1LjU5NTAzIDIyLjcyOTJDNi4wNzU4MyAyMi45MDQ1IDYuNTk0OTIgMjMuMDAwMSA3LjEzNjM1IDIzLjAwMDFIMTQuNUMxNi45ODUzIDIzLjAwMDEgMTkgMjAuOTg1NCAxOSAxOC41MDAxQzE5IDE2LjYzODYgMTcuODY5NyAxNS4wNDExIDE2LjI1OCAxNC4zNTY1TTExLjIwNzkgNi41NDIxN0MxMi41NDI1IDkuNjY1NTEgMTYuMDE3MiAxMS4xNzUgMTguOTY4OSA5LjkxMzgxQzE5LjU0NTkgOS42NjcyNiAyMC4wNjAyIDkuMzMzMDggMjAuNTA0MyA4LjkzMTYyQzIwLjQwOTcgMTEuMTQ5NSAxOS4xNDM2IDEzLjE4MzEgMTcuMDU5NiAxNC4wNzM2QzE0LjEwNzkgMTUuMzM0OCAxMC42MzMyIDEzLjgyNTIgOS4yOTg2MyAxMC43MDE5QzguMjI0OTQgOC4xODkxMiA4Ljg2MzU1IDUuMzk3MzQgMTAuNjkxMyAzLjc0NTEyQzEwLjY1MTkgNC42Njg1OCAxMC44MTU2IDUuNjI0IDExLjIwNzkgNi41NDIxN1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineWeatherPartlyCloudlyNight = React.forwardRef<IconLineWeatherPartlyCloudlyNightRef, IconLineWeatherPartlyCloudlyNightProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-weather-partly-cloudly-night" ref={ref}><path d="M9.59407 11.2998C8.94962 11.1053 8.26095 11.0001 7.54546 11.0001C3.9305 11.0001 1 13.6864 1 17.0001C1 19.6911 2.93265 21.9684 5.59503 22.7292C6.07583 22.9045 6.59492 23.0001 7.13635 23.0001H14.5C16.9853 23.0001 19 20.9854 19 18.5001C19 16.6386 17.8697 15.0411 16.258 14.3565M11.2079 6.54217C12.5425 9.66551 16.0172 11.175 18.9689 9.91381C19.5459 9.66726 20.0602 9.33308 20.5043 8.93162C20.4097 11.1495 19.1436 13.1831 17.0596 14.0736C14.1079 15.3348 10.6332 13.8252 9.29863 10.7019C8.22494 8.18912 8.86355 5.39734 10.6913 3.74512C10.6519 4.66858 10.8156 5.624 11.2079 6.54217Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineWeatherPartlyCloudlyNight.displayName = definePortfolioDisplayName("IconLineWeatherPartlyCloudlyNight")

export { IconLineWeatherPartlyCloudlyNight }