/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineFullScreenProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineFullScreenRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTYgMUgyM1Y4TTIzIDE2VjIzSDE2TTggMUgxVjhNMSAxNlYyM0g4IiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineFullScreen = React.forwardRef<IconLineFullScreenRef, IconLineFullScreenProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-full-screen" ref={ref}><path d="M16 1H23V8M23 16V23H16M8 1H1V8M1 16V23H8" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineFullScreen.displayName = definePortfolioDisplayName("IconLineFullScreen")

export { IconLineFullScreen }