/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledGamepadProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledGamepadRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTEwIDVDNS41ODE3MiA1IDIgOC41ODE3MiAyIDEzVjE5LjU5NjNDMiAyMC45MjM4IDMuMDc2MTYgMjIgNC40MDM2NyAyMkM1Ljc0MDQ0IDIyIDcuMDE2ODQgMjEuNDQzNCA3LjkyNjQ1IDIwLjQ2MzhMOC4zNzM0MSAxOS45ODI1QzEwLjg3MTMgMTcuMjkyNSAxNS4xMjg3IDE3LjI5MjUgMTcuNjI2NiAxOS45ODI1TDE4LjA3MzUgMjAuNDYzOEMxOC45ODMyIDIxLjQ0MzQgMjAuMjU5NiAyMiAyMS41OTYzIDIyQzIyLjkyMzggMjIgMjQgMjAuOTIzOCAyNCAxOS41OTYzVjEzQzI0IDguNTgxNzIgMjAuNDE4MyA1IDE2IDVIMTBaTTkuNSAxNEg4LjVWMTJINi41VjExSDguNVY5SDkuNVYxMUgxMS41VjEySDkuNVYxNFpNMTYgMTFDMTYuNTUyMyAxMSAxNyAxMC41NTIzIDE3IDEwQzE3IDkuNDQ3NzIgMTYuNTUyMyA5IDE2IDlDMTUuNDQ3NyA5IDE1IDkuNDQ3NzIgMTUgMTBDMTUgMTAuNTUyMyAxNS40NDc3IDExIDE2IDExWk0xOSAxM0MxOSAxMy41NTIzIDE4LjU1MjMgMTQgMTggMTRDMTcuNDQ3NyAxNCAxNyAxMy41NTIzIDE3IDEzQzE3IDEyLjQ0NzcgMTcuNDQ3NyAxMiAxOCAxMkMxOC41NTIzIDEyIDE5IDEyLjQ0NzcgMTkgMTNaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledGamepad = React.forwardRef<IconFilledGamepadRef, IconFilledGamepadProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-gamepad" ref={ref}><path fill-rule="evenodd" clip-rule="evenodd" d="M10 5C5.58172 5 2 8.58172 2 13V19.5963C2 20.9238 3.07616 22 4.40367 22C5.74044 22 7.01684 21.4434 7.92645 20.4638L8.37341 19.9825C10.8713 17.2925 15.1287 17.2925 17.6266 19.9825L18.0735 20.4638C18.9832 21.4434 20.2596 22 21.5963 22C22.9238 22 24 20.9238 24 19.5963V13C24 8.58172 20.4183 5 16 5H10ZM9.5 14H8.5V12H6.5V11H8.5V9H9.5V11H11.5V12H9.5V14ZM16 11C16.5523 11 17 10.5523 17 10C17 9.44772 16.5523 9 16 9C15.4477 9 15 9.44772 15 10C15 10.5523 15.4477 11 16 11ZM19 13C19 13.5523 18.5523 14 18 14C17.4477 14 17 13.5523 17 13C17 12.4477 17.4477 12 18 12C18.5523 12 19 12.4477 19 13Z" fill="currentColor" /></IconBase>)
IconFilledGamepad.displayName = definePortfolioDisplayName("IconFilledGamepad")

export { IconFilledGamepad }