/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledFilledBackspaceProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledFilledBackspaceRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTUuNDg3NzkgNC4yNjQyMUM2LjA1MDM1IDMuNDcxMiA2Ljk2MjM0IDMgNy45MzQ2MyAzSDIwQzIxLjY1NjkgMyAyMyA0LjM0MzE1IDIzIDZWMThDMjMgMTkuNjU2OSAyMS42NTY5IDIxIDIwIDIxSDcuOTM0NjNDNi45NjIzNCAyMSA2LjA1MDM1IDIwLjUyODggNS40ODc3OSAxOS43MzU4TDAuODIwOTIyIDEzLjE1NzJDMC4zMjkyMjQgMTIuNDY0MSAwLjMyOTIyNCAxMS41MzU5IDAuODIwOTIyIDEwLjg0MjhMNS40ODc3OSA0LjI2NDIxWk05LjI5MjkgOC4yOTI4OUM5LjY4MzQyIDcuOTAyMzcgMTAuMzE2NiA3LjkwMjM3IDEwLjcwNzEgOC4yOTI4OUwxMyAxMC41ODU4TDE1LjI5MjkgOC4yOTI4OUMxNS42ODM0IDcuOTAyMzcgMTYuMzE2NiA3LjkwMjM3IDE2LjcwNzEgOC4yOTI4OUMxNy4wOTc2IDguNjgzNDIgMTcuMDk3NiA5LjMxNjU4IDE2LjcwNzEgOS43MDcxMUwxNC40MTQyIDEyTDE2LjcwNzEgMTQuMjkyOUMxNy4wOTc2IDE0LjY4MzQgMTcuMDk3NiAxNS4zMTY2IDE2LjcwNzEgMTUuNzA3MUMxNi4zMTY2IDE2LjA5NzYgMTUuNjgzNCAxNi4wOTc2IDE1LjI5MjkgMTUuNzA3MUwxMyAxMy40MTQyTDEwLjcwNzEgMTUuNzA3MUMxMC4zMTY2IDE2LjA5NzYgOS42ODM0MiAxNi4wOTc2IDkuMjkyOSAxNS43MDcxQzguOTAyMzcgMTUuMzE2NiA4LjkwMjM3IDE0LjY4MzQgOS4yOTI5IDE0LjI5MjlMMTEuNTg1OCAxMkw5LjI5MjkgOS43MDcxMUM4LjkwMjM3IDkuMzE2NTggOC45MDIzNyA4LjY4MzQyIDkuMjkyOSA4LjI5Mjg5WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledFilledBackspace = React.forwardRef<IconFilledFilledBackspaceRef, IconFilledFilledBackspaceProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-filled-backspace" ref={ref}><path fill-rule="evenodd" clip-rule="evenodd" d="M5.48779 4.26421C6.05035 3.4712 6.96234 3 7.93463 3H20C21.6569 3 23 4.34315 23 6V18C23 19.6569 21.6569 21 20 21H7.93463C6.96234 21 6.05035 20.5288 5.48779 19.7358L0.820922 13.1572C0.329224 12.4641 0.329224 11.5359 0.820922 10.8428L5.48779 4.26421ZM9.2929 8.29289C9.68342 7.90237 10.3166 7.90237 10.7071 8.29289L13 10.5858L15.2929 8.29289C15.6834 7.90237 16.3166 7.90237 16.7071 8.29289C17.0976 8.68342 17.0976 9.31658 16.7071 9.70711L14.4142 12L16.7071 14.2929C17.0976 14.6834 17.0976 15.3166 16.7071 15.7071C16.3166 16.0976 15.6834 16.0976 15.2929 15.7071L13 13.4142L10.7071 15.7071C10.3166 16.0976 9.68342 16.0976 9.2929 15.7071C8.90237 15.3166 8.90237 14.6834 9.2929 14.2929L11.5858 12L9.2929 9.70711C8.90237 9.31658 8.90237 8.68342 9.2929 8.29289Z" fill="currentColor" /></IconBase>)
IconFilledFilledBackspace.displayName = definePortfolioDisplayName("IconFilledFilledBackspace")

export { IconFilledFilledBackspace }