/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineCircleCurrencyPoundProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineCircleCurrencyPoundRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTQuMTIxIDcuNjI5QzEzLjcyMDcgNy4yMjg4IDEzLjIxNTQgNi45NSAxMi42NjM1IDYuODI0NzlDMTIuMTExNSA2LjY5OTU5IDExLjUzNTMgNi43MzMwOSAxMS4wMDE2IDYuOTIxNDNDMTAuNDY3OCA3LjEwOTc3IDkuOTk4MjQgNy40NDUyNiA5LjY0NzA3IDcuODg5MTZDOS4yOTU5IDguMzMzMDUgOS4wNzc0NiA4Ljg2NzIzIDkuMDE3IDkuNDNDOC45OTQgOS42NDIgOS4wMTUgOS44NTUgOS4wNDUgMTAuMDY2TDkuNTUxIDEzLjYwN0M5LjY4MDY0IDE0LjUxMzUgOS41MzA2MyAxNS40MzggOS4xMjEgMTYuMjU3TDkgMTYuNUwxMC41MzkgMTUuOTg3QzExLjAwMDUgMTUuODMzMyAxMS40OTk1IDE1LjgzMzMgMTEuOTYxIDE1Ljk4N0wxMi42MTYgMTYuMjA1QzEyLjg5NjMgMTYuMjk4NSAxMy4xOTI0IDE2LjMzNTggMTMuNDg3MSAxNi4zMTQ5QzEzLjc4MTkgMTYuMjk0IDE0LjA2OTcgMTYuMjE1MiAxNC4zMzQgMTYuMDgzTDE1IDE1Ljc1TTguMjUgMTJIMTJNMjIgMTJDMjIgMTcuNTIyOCAxNy41MjI4IDIyIDEyIDIyQzYuNDc3MTUgMjIgMiAxNy41MjI4IDIgMTJDMiA2LjQ3NzE1IDYuNDc3MTUgMiAxMiAyQzE3LjUyMjggMiAyMiA2LjQ3NzE1IDIyIDEyWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineCircleCurrencyPound = React.forwardRef<IconLineCircleCurrencyPoundRef, IconLineCircleCurrencyPoundProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-circle-currency-pound" ref={ref}><path d="M14.121 7.629C13.7207 7.2288 13.2154 6.95 12.6635 6.82479C12.1115 6.69959 11.5353 6.73309 11.0016 6.92143C10.4678 7.10977 9.99824 7.44526 9.64707 7.88916C9.2959 8.33305 9.07746 8.86723 9.017 9.43C8.994 9.642 9.015 9.855 9.045 10.066L9.551 13.607C9.68064 14.5135 9.53063 15.438 9.121 16.257L9 16.5L10.539 15.987C11.0005 15.8333 11.4995 15.8333 11.961 15.987L12.616 16.205C12.8963 16.2985 13.1924 16.3358 13.4871 16.3149C13.7819 16.294 14.0697 16.2152 14.334 16.083L15 15.75M8.25 12H12M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineCircleCurrencyPound.displayName = definePortfolioDisplayName("IconLineCircleCurrencyPound")

export { IconLineCircleCurrencyPound }