/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineHelpProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineHelpRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTkuNzc4MiA0LjIyMTgzQzI0LjA3MzkgOC41MTc1OSAyNC4wNzM5IDE1LjQ4MjQgMTkuNzc4MiAxOS43NzgyQzE1LjQ4MjQgMjQuMDczOSA4LjUxNzU5IDI0LjA3MzkgNC4yMjE4MyAxOS43NzgyTTE5Ljc3ODIgNC4yMjE4M0MxNS40ODI0IC0wLjA3Mzk0MTcgOC41MTc1OSAtMC4wNzM5NDE3IDQuMjIxODMgNC4yMjE4M00xOS43NzgyIDQuMjIxODNMMTUuNTM1NSA4LjQ2NDQ4TTQuMjIxODMgMTkuNzc4MkMtMC4wNzM5NDE3IDE1LjQ4MjQgLTAuMDczOTQxNyA4LjUxNzU5IDQuMjIxODMgNC4yMjE4M000LjIyMTgzIDE5Ljc3ODJMOC40NjQ0NyAxNS41MzU0TTQuMjIxODMgNC4yMjE4M0w4LjExMDkxIDguMTEwODlNMTUuNTM1NSAxNS41MzU1TDE5LjQyNDYgMTkuNDI0Nk0xNyAxMkMxNyAxNC43NjE0IDE0Ljc2MTQgMTcgMTIgMTdDOS4yMzg1OCAxNyA3IDE0Ljc2MTQgNyAxMkM3IDkuMjM4NTggOS4yMzg1OCA3IDEyIDdDMTQuNzYxNCA3IDE3IDkuMjM4NTggMTcgMTJaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineHelp = React.forwardRef<IconLineHelpRef, IconLineHelpProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-help" ref={ref}><path d="M19.7782 4.22183C24.0739 8.51759 24.0739 15.4824 19.7782 19.7782C15.4824 24.0739 8.51759 24.0739 4.22183 19.7782M19.7782 4.22183C15.4824 -0.0739417 8.51759 -0.0739417 4.22183 4.22183M19.7782 4.22183L15.5355 8.46448M4.22183 19.7782C-0.0739417 15.4824 -0.0739417 8.51759 4.22183 4.22183M4.22183 19.7782L8.46447 15.5354M4.22183 4.22183L8.11091 8.11089M15.5355 15.5355L19.4246 19.4246M17 12C17 14.7614 14.7614 17 12 17C9.23858 17 7 14.7614 7 12C7 9.23858 9.23858 7 12 7C14.7614 7 17 9.23858 17 12Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineHelp.displayName = definePortfolioDisplayName("IconLineHelp")

export { IconLineHelp }