/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCryptoTetherUsdtProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCryptoTetherUsdtRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTMuNTQ4MyAxMi4xODA4VjEyLjE4MjFDMTYuMDY4MyAxMi4wNzA5IDE3Ljk0ODYgMTEuNjM0NiAxNy45NDg2IDExLjExMUMxNy45NDg2IDEwLjU4ODggMTYuMDY4MyAxMC4xNTExIDEzLjU0ODMgMTAuMDM5M1YxMS43NDc3QzEzLjQ3NDkgMTEuNzU0MiAxMy4wODIgMTEuNzg2NSAxMi4yOTgxIDExLjc4NjVDMTEuNjQ0NyAxMS43ODY1IDExLjE3MTkgMTEuNzU4NyAxMS4wMDY5IDExLjc0NzFWMTAuMDM4QzguNDgxNjggMTAuMTUwNSA2LjU5Njg4IDEwLjU4ODEgNi41OTY4OCAxMS4xMTFDNi41OTY4OCAxMS42MzQ2IDguNDgxNjggMTIuMDcyMiAxMS4wMDY5IDEyLjE4MjhWMTIuMTgwOEMxMS4xNjkzIDEyLjE4ODYgMTEuNjMxIDEyLjIwOCAxMi4yODcgMTIuMjA4QzEzLjEwODYgMTIuMjA4IDEzLjQ3NjkgMTIuMTg2IDEzLjU0ODMgMTIuMTgwOFoiIGZpbGw9IiMxRTIwMjgiIC8+PHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yNCAxMkMyNCAxOC42Mjc0IDE4LjYyNzQgMjQgMTIgMjRDNS4zNzI1OCAyNCAwIDE4LjYyNzQgMCAxMkMwIDUuMzcyNTggNS4zNzI1OCAwIDEyIDBDMTguNjI3NCAwIDI0IDUuMzcyNTggMjQgMTJaTTEzLjU0ODMgOC4zMzIxOVY5Ljg2MTU2QzE2LjQwMTUgOS45OTI3OCAxOC41NDU1IDEwLjU1NTggMTguNTQ1NSAxMS4yM0MxOC41NDU1IDExLjkwNDIgMTYuNDAxNSAxMi40NjcyIDEzLjU0ODMgMTIuNTk3N1YxNy41SDExLjAwNjlWMTIuNTk5QzguMTQ5MTUgMTIuNDY3OCA2IDExLjkwNDggNiAxMS4yM0M2IDEwLjU1NTEgOC4xNDkxNSA5Ljk5MTQ4IDExLjAwNjkgOS44NjA5MVY4LjMzMjE5SDcuNDkwNTdWNkgxNy4wNjQ2VjguMzMyMTlIMTMuNTQ4M1oiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFilledCryptoTetherUsdt = React.forwardRef<IconFilledCryptoTetherUsdtRef, IconFilledCryptoTetherUsdtProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-crypto-tether-usdt" ref={ref}><path d="M13.5483 12.1808V12.1821C16.0683 12.0709 17.9486 11.6346 17.9486 11.111C17.9486 10.5888 16.0683 10.1511 13.5483 10.0393V11.7477C13.4749 11.7542 13.082 11.7865 12.2981 11.7865C11.6447 11.7865 11.1719 11.7587 11.0069 11.7471V10.038C8.48168 10.1505 6.59688 10.5881 6.59688 11.111C6.59688 11.6346 8.48168 12.0722 11.0069 12.1828V12.1808C11.1693 12.1886 11.631 12.208 12.287 12.208C13.1086 12.208 13.4769 12.186 13.5483 12.1808Z" fill="currentColor" /><path fill-rule="evenodd" clip-rule="evenodd" d="M24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0C18.6274 0 24 5.37258 24 12ZM13.5483 8.33219V9.86156C16.4015 9.99278 18.5455 10.5558 18.5455 11.23C18.5455 11.9042 16.4015 12.4672 13.5483 12.5977V17.5H11.0069V12.599C8.14915 12.4678 6 11.9048 6 11.23C6 10.5551 8.14915 9.99148 11.0069 9.86091V8.33219H7.49057V6H17.0646V8.33219H13.5483Z" fill="currentColor" /></IconBase>)
IconFilledCryptoTetherUsdt.displayName = definePortfolioDisplayName("IconFilledCryptoTetherUsdt")

export { IconFilledCryptoTetherUsdt }