/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineCursorProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineCursorRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTguMzY4OCAxMS4yNjA3TDUuNTM2NjIgNi41MzcxMUwxMC4yNjAyIDE5LjM2OTNMMTMuMTQ0MSAxNi40ODU0TDE2LjA3MDEgMTkuNDExM0wxOC40MTA4IDE3LjA3MDZMMTUuNDg0OSAxNC4xNDQ2TDE4LjM2ODggMTEuMjYwN1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineCursor = React.forwardRef<IconLineCursorRef, IconLineCursorProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-cursor" ref={ref}><path d="M18.3688 11.2607L5.53662 6.53711L10.2602 19.3693L13.1441 16.4854L16.0701 19.4113L18.4108 17.0706L15.4849 14.1446L18.3688 11.2607Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineCursor.displayName = definePortfolioDisplayName("IconLineCursor")

export { IconLineCursor }