/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineSleepingBedProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineSleepingBedRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjIgMThWMjBNMiAxOFYyME0yMiAxM1Y2QzIyIDQuODk1NDMgMjEuMTA0NiA0IDIwIDRINEMyLjg5NTQzIDQgMiA0Ljg5NTQzIDIgNlYxM0gyMlpNMjMgMThWMTVDMjMgMTMuODk1NCAyMi4xMDQ2IDEzIDIxIDEzSDNDMS44OTU0MyAxMyAxIDEzLjg5NTQgMSAxNVYxOEgyM1pNNi41IDEzSDkuNUMxMC4wNTIzIDEzIDEwLjUgMTIuNTUyMyAxMC41IDEyVjEwQzEwLjUgOS40NDc3MiAxMC4wNTIzIDkgOS41IDlINi41QzUuOTQ3NzIgOSA1LjUgOS40NDc3MiA1LjUgMTBWMTJDNS41IDEyLjU1MjMgNS45NDc3MiAxMyA2LjUgMTNaTTE0LjUgMTNIMTcuNUMxOC4wNTIzIDEzIDE4LjUgMTIuNTUyMyAxOC41IDEyVjEwQzE4LjUgOS40NDc3MiAxOC4wNTIzIDkgMTcuNSA5SDE0LjVDMTMuOTQ3NyA5IDEzLjUgOS40NDc3MiAxMy41IDEwVjEyQzEzLjUgMTIuNTUyMyAxMy45NDc3IDEzIDE0LjUgMTNaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineSleepingBed = React.forwardRef<IconLineSleepingBedRef, IconLineSleepingBedProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-sleeping-bed" ref={ref}><path d="M22 18V20M2 18V20M22 13V6C22 4.89543 21.1046 4 20 4H4C2.89543 4 2 4.89543 2 6V13H22ZM23 18V15C23 13.8954 22.1046 13 21 13H3C1.89543 13 1 13.8954 1 15V18H23ZM6.5 13H9.5C10.0523 13 10.5 12.5523 10.5 12V10C10.5 9.44772 10.0523 9 9.5 9H6.5C5.94772 9 5.5 9.44772 5.5 10V12C5.5 12.5523 5.94772 13 6.5 13ZM14.5 13H17.5C18.0523 13 18.5 12.5523 18.5 12V10C18.5 9.44772 18.0523 9 17.5 9H14.5C13.9477 9 13.5 9.44772 13.5 10V12C13.5 12.5523 13.9477 13 14.5 13Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineSleepingBed.displayName = definePortfolioDisplayName("IconLineSleepingBed")

export { IconLineSleepingBed }