/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineCircleActionsAlertQuestionProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineCircleActionsAlertQuestionRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIgMTRWMTMuMjI5NUMxMiAxMi4yMzY0IDEyLjc2MjcgMTEuNDE2NyAxMy42MTMzIDEwLjkwNDFDMTQuNDM0NCAxMC40MDkyIDE1LjIxODUgOS41Mjk1IDE1IDcuOTk5OTlDMTQuNTcxNCA0Ljk5OTk3IDEwLjUgNi41IDEwLjUgNi41TTEyIDE3VjE3LjVNMjMgMTJDMjMgMTguMDc1MSAxOC4wNzUxIDIzIDEyIDIzQzUuOTI0ODcgMjMgMSAxOC4wNzUxIDEgMTJDMSA1LjkyNDg3IDUuOTI0ODcgMSAxMiAxQzE4LjA3NTEgMSAyMyA1LjkyNDg3IDIzIDEyWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineCircleActionsAlertQuestion = React.forwardRef<IconLineCircleActionsAlertQuestionRef, IconLineCircleActionsAlertQuestionProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-circle-actions-alert-question" ref={ref}><path d="M12 14V13.2295C12 12.2364 12.7627 11.4167 13.6133 10.9041C14.4344 10.4092 15.2185 9.5295 15 7.99999C14.5714 4.99997 10.5 6.5 10.5 6.5M12 17V17.5M23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineCircleActionsAlertQuestion.displayName = definePortfolioDisplayName("IconLineCircleActionsAlertQuestion")

export { IconLineCircleActionsAlertQuestion }