/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledBackwardProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledBackwardRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTkuNDYzOCA1LjI1NDQ1QzIwLjQ2MDYgNC41ODk4OSAyMS43OTU4IDUuMzA0NDggMjEuNzk1OCA2LjUwMjUyVjE2Ljg5N0MyMS43OTU4IDE4LjA5NSAyMC40NjA2IDE4LjgwOTYgMTkuNDYzOCAxOC4xNDVMMTIuNzk1OCAxMy42OTk3VjE2Ljg5N0MxMi43OTU4IDE4LjA5NTEgMTEuNDYwNiAxOC44MDk3IDEwLjQ2MzggMTguMTQ1MUwyLjY2Nzk1IDEyLjk0NzlDMS43NzczNSAxMi4zNTQxIDEuNzc3MzUgMTEuMDQ1NSAyLjY2Nzk1IDEwLjQ1MTdMMTAuNDYzOCA1LjI1NDVDMTEuNDYwNiA0LjU4OTk0IDEyLjc5NTggNS4zMDQ1MyAxMi43OTU4IDYuNTAyNTdWOS42OTk3NUwxOS40NjM4IDUuMjU0NDVaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledBackward = React.forwardRef<IconFilledBackwardRef, IconFilledBackwardProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-backward" ref={ref}><path d="M19.4638 5.25445C20.4606 4.58989 21.7958 5.30448 21.7958 6.50252V16.897C21.7958 18.095 20.4606 18.8096 19.4638 18.145L12.7958 13.6997V16.897C12.7958 18.0951 11.4606 18.8097 10.4638 18.1451L2.66795 12.9479C1.77735 12.3541 1.77735 11.0455 2.66795 10.4517L10.4638 5.2545C11.4606 4.58994 12.7958 5.30453 12.7958 6.50257V9.69975L19.4638 5.25445Z" fill="currentColor" /></IconBase>)
IconFilledBackward.displayName = definePortfolioDisplayName("IconFilledBackward")

export { IconFilledBackward }