/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineRoomServiceHelpProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineRoomServiceHelpRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAgM0gxNE0xMiAzVjdNMTIgN0MxNi45NzA1IDcgMjEgMTEuMDI5NCAyMSAxNk0xMiA3QzcuMDI5NDYgNyAzIDExLjAyOTQgMyAxNk0zIDE2VjIwTTMgMTZIMjFNMjEgMTZWMjBNMSAxNkgyM00xIDIwSDIzIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineRoomServiceHelp = React.forwardRef<IconLineRoomServiceHelpRef, IconLineRoomServiceHelpProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-room-service-help" ref={ref}><path d="M10 3H14M12 3V7M12 7C16.9705 7 21 11.0294 21 16M12 7C7.02946 7 3 11.0294 3 16M3 16V20M3 16H21M21 16V20M1 16H23M1 20H23" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineRoomServiceHelp.displayName = definePortfolioDisplayName("IconLineRoomServiceHelp")

export { IconLineRoomServiceHelp }