/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineNotificationBellProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineNotificationBellRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTkuMzMzNSA5LjAxNDQ5QzE5LjMzMzUgNy4xNTQxMyAxOC41NjA5IDUuMzY5OTcgMTcuMTg1NiA0LjA1NDVDMTUuODEwNCAyLjczOTAyIDEzLjk0NTEgMiAxMi4wMDAyIDJDMTAuMDU1MiAyIDguMTg5OTkgMi43MzkwMiA2LjgxNDcyIDQuMDU0NUM1LjQzOTQ1IDUuMzY5OTcgNC42NjY4NCA3LjE1NDEzIDQuNjY2ODQgOS4wMTQ0OUM0LjY2Njg0IDE0Ljk0ODQgMi4yMTMyMSAxNy44MDkgMC44NjQyMjggMTguOTMzM0MwLjY2MTY2MyAxOS4xMDIxIDAuNzkzNTM0IDE5LjUzNjIgMS4wNTcyMyAxOS41MzYySDcuNTIyM0M3LjYzOTI3IDE5LjUzNjIgNy43NDA5IDE5LjYxNTQgNy43NzUzOCAxOS43MjcxQzcuOTk5MjggMjAuNDUyOSA4Ljk5ODgzIDIzIDEyLjAwMDIgMjNDMTUuMDAxNSAyMyAxNi4wMDExIDIwLjQ1MjkgMTYuMjI1IDE5LjcyNzFDMTYuMjU5NCAxOS42MTU0IDE2LjM2MTEgMTkuNTM2MiAxNi40NzggMTkuNTM2MkgyMi45NDMxQzIzLjIwNjggMTkuNTM2MiAyMy4zMzg3IDE5LjEwMjEgMjMuMTM2MSAxOC45MzMzQzIxLjc4NzEgMTcuODA5IDE5LjMzMzUgMTQuOTQ4NCAxOS4zMzM1IDkuMDE0NDlaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineNotificationBell = React.forwardRef<IconLineNotificationBellRef, IconLineNotificationBellProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-notification-bell" ref={ref}><path d="M19.3335 9.01449C19.3335 7.15413 18.5609 5.36997 17.1856 4.0545C15.8104 2.73902 13.9451 2 12.0002 2C10.0552 2 8.18999 2.73902 6.81472 4.0545C5.43945 5.36997 4.66684 7.15413 4.66684 9.01449C4.66684 14.9484 2.21321 17.809 0.864228 18.9333C0.661663 19.1021 0.793534 19.5362 1.05723 19.5362H7.5223C7.63927 19.5362 7.7409 19.6154 7.77538 19.7271C7.99928 20.4529 8.99883 23 12.0002 23C15.0015 23 16.0011 20.4529 16.225 19.7271C16.2594 19.6154 16.3611 19.5362 16.478 19.5362H22.9431C23.2068 19.5362 23.3387 19.1021 23.1361 18.9333C21.7871 17.809 19.3335 14.9484 19.3335 9.01449Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineNotificationBell.displayName = definePortfolioDisplayName("IconLineNotificationBell")

export { IconLineNotificationBell }