/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineShuffleProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineShuffleRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjMgNUwxNy43Mjk4IDVDMTYuMDI4NCA1IDE0LjQ0MzkgNS44NjUxIDEzLjUyMzkgNy4yOTYyMUw4LjA2NjU5IDE1Ljc4NTNDNi43Nzg1OSAxNy43ODg5IDQuNTYwMTkgMTkgMi4xNzgzNCAxOUgxTTIzIDVMMTkgMU0yMyA1TDE5IDlNMjMgMTlMMTcuNDAzMSAxOUMxNS44ODQyIDE5IDE0LjQ0NzYgMTguMzA5NiAxMy40OTg4IDE3LjEyMzVMMTMgMTYuNU0yMyAxOUwxOSAyM00yMyAxOUwxOSAxNU0xIDVMMS43MjEzOCA1QzMuNzk4ODQgNSA1Ljc2ODk3IDUuOTIyNzYgNy4wOTg5MiA3LjUxODcxTDcuNSA4IiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineShuffle = React.forwardRef<IconLineShuffleRef, IconLineShuffleProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-shuffle" ref={ref}><path d="M23 5L17.7298 5C16.0284 5 14.4439 5.8651 13.5239 7.29621L8.06659 15.7853C6.77859 17.7889 4.56019 19 2.17834 19H1M23 5L19 1M23 5L19 9M23 19L17.4031 19C15.8842 19 14.4476 18.3096 13.4988 17.1235L13 16.5M23 19L19 23M23 19L19 15M1 5L1.72138 5C3.79884 5 5.76897 5.92276 7.09892 7.51871L7.5 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineShuffle.displayName = definePortfolioDisplayName("IconLineShuffle")

export { IconLineShuffle }