/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineTicketProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineTicketRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTUgNFY2TTE1IDExVjEzTTE1IDE4VjIwTTEgNkMxIDQuODk1NDMgMS44OTU0MyA0IDMgNEgyMUMyMi4xMDQ2IDQgMjMgNC44OTU0MyAyMyA2VjkuMTcwNzFDMjEuODM0OCA5LjU4MjU0IDIxIDEwLjY5MzggMjEgMTJDMjEgMTMuMzA2MiAyMS44MzQ4IDE0LjQxNzUgMjMgMTQuODI5M1YxOEMyMyAxOS4xMDQ2IDIyLjEwNDYgMjAgMjEgMjBIM0MxLjg5NTQzIDIwIDEgMTkuMTA0NiAxIDE4VjE0LjgyOTNDMi4xNjUxOSAxNC40MTc1IDMgMTMuMzA2MiAzIDEyQzMgMTAuNjkzOCAyLjE2NTE5IDkuNTgyNTQgMSA5LjE3MDcxVjZaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineTicket = React.forwardRef<IconLineTicketRef, IconLineTicketProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-ticket" ref={ref}><path d="M15 4V6M15 11V13M15 18V20M1 6C1 4.89543 1.89543 4 3 4H21C22.1046 4 23 4.89543 23 6V9.17071C21.8348 9.58254 21 10.6938 21 12C21 13.3062 21.8348 14.4175 23 14.8293V18C23 19.1046 22.1046 20 21 20H3C1.89543 20 1 19.1046 1 18V14.8293C2.16519 14.4175 3 13.3062 3 12C3 10.6938 2.16519 9.58254 1 9.17071V6Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineTicket.displayName = definePortfolioDisplayName("IconLineTicket")

export { IconLineTicket }