/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledFilledBagProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledFilledBagRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMi40NjM1NiA0LjQ0MzczQzIuNDQ4MTMgNC40NjIyNCAyLjQzMzA2IDQuNDgxIDIuNDE4MzYgNC41SDIxLjU4MTZDMjEuNTY2OSA0LjQ4MSAyMS41NTE5IDQuNDYyMjQgMjEuNTM2NCA0LjQ0MzczTDE5LjI2NjQgMS43MTk2M0MxOC44ODY0IDEuMjYzNjUgMTguMzIzNSAxIDE3LjcyOTkgMUg2LjI3MDA4QzUuNjc2NTIgMSA1LjExMzYzIDEuMjYzNjUgNC43MzM2NCAxLjcxOTYzTDIuNDYzNTYgNC40NDM3M1oiIGZpbGw9IiMxRTIwMjgiIC8+PHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0yIDIwVjYuNUgyMlYyMEMyMiAyMS42NTY5IDIwLjY1NjkgMjMgMTkgMjNINUMzLjM0MzE1IDIzIDIgMjEuNjU2OSAyIDIwWk05IDEwQzkgOS40NDc3MSA4LjU1MjI4IDkgOCA5QzcuNDQ3NzIgOSA3IDkuNDQ3NzEgNyAxMEM3IDEyLjc2MTQgOS4yMzg1OCAxNSAxMiAxNUMxNC43NjE0IDE1IDE3IDEyLjc2MTQgMTcgMTBDMTcgOS40NDc3MSAxNi41NTIzIDkgMTYgOUMxNS40NDc3IDkgMTUgOS40NDc3MSAxNSAxMEMxNSAxMS42NTY5IDEzLjY1NjkgMTMgMTIgMTNDMTAuMzQzMSAxMyA5IDExLjY1NjkgOSAxMFoiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFilledFilledBag = React.forwardRef<IconFilledFilledBagRef, IconFilledFilledBagProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-filled-bag" ref={ref}><path d="M2.46356 4.44373C2.44813 4.46224 2.43306 4.481 2.41836 4.5H21.5816C21.5669 4.481 21.5519 4.46224 21.5364 4.44373L19.2664 1.71963C18.8864 1.26365 18.3235 1 17.7299 1H6.27008C5.67652 1 5.11363 1.26365 4.73364 1.71963L2.46356 4.44373Z" fill="currentColor" /><path fill-rule="evenodd" clip-rule="evenodd" d="M2 20V6.5H22V20C22 21.6569 20.6569 23 19 23H5C3.34315 23 2 21.6569 2 20ZM9 10C9 9.44771 8.55228 9 8 9C7.44772 9 7 9.44771 7 10C7 12.7614 9.23858 15 12 15C14.7614 15 17 12.7614 17 10C17 9.44771 16.5523 9 16 9C15.4477 9 15 9.44771 15 10C15 11.6569 13.6569 13 12 13C10.3431 13 9 11.6569 9 10Z" fill="currentColor" /></IconBase>)
IconFilledFilledBag.displayName = definePortfolioDisplayName("IconFilledFilledBag")

export { IconFilledFilledBag }