/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFillSkipForwardProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFillSkipForwardRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMy4zMzIwNSA1LjI1NDQ1QzIuMzM1MjIgNC41ODk4OSAxIDUuMzA0NDggMSA2LjUwMjUyVjE2Ljg5N0MxIDE4LjA5NSAyLjMzNTIyIDE4LjgwOTYgMy4zMzIwNSAxOC4xNDVMMTEuMTI3OSAxMi45NDc4QzExLjUxNDQgMTIuNjkwMiAxMS43MzMxIDEyLjI5NzkgMTEuNzg0MiAxMS44ODc4VjE2Ljg5N0MxMS43ODQyIDE4LjA5NSAxMy4xMTk0IDE4LjgwOTYgMTQuMTE2MiAxOC4xNDVMMjEuOTEyMSAxMi45NDc4QzIyLjgwMjcgMTIuMzU0MSAyMi44MDI3IDExLjA0NTQgMjEuOTEyMSAxMC40NTE3TDE0LjExNjIgNS4yNTQ0NUMxMy4xMTk0IDQuNTg5ODkgMTEuNzg0MiA1LjMwNDQ4IDExLjc4NDIgNi41MDI1MlYxMS41MTE3QzExLjczMzEgMTEuMTAxNiAxMS41MTQ0IDEwLjcwOTMgMTEuMTI3OSAxMC40NTE3TDMuMzMyMDUgNS4yNTQ0NVoiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFillSkipForward = React.forwardRef<IconFillSkipForwardRef, IconFillSkipForwardProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-fill-skip-forward" ref={ref}><path d="M3.33205 5.25445C2.33522 4.58989 1 5.30448 1 6.50252V16.897C1 18.095 2.33522 18.8096 3.33205 18.145L11.1279 12.9478C11.5144 12.6902 11.7331 12.2979 11.7842 11.8878V16.897C11.7842 18.095 13.1194 18.8096 14.1162 18.145L21.9121 12.9478C22.8027 12.3541 22.8027 11.0454 21.9121 10.4517L14.1162 5.25445C13.1194 4.58989 11.7842 5.30448 11.7842 6.50252V11.5117C11.7331 11.1016 11.5144 10.7093 11.1279 10.4517L3.33205 5.25445Z" fill="currentColor" /></IconBase>)
IconFillSkipForward.displayName = definePortfolioDisplayName("IconFillSkipForward")

export { IconFillSkipForward }