/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBioFingerprintProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBioFingerprintRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNS40NzU3OCA3LjI4OTYzTDUuNTkxOTggNi45NjM4N0M3LjEyMjg4IDIuNjcyMSAxMS44NTUgMC40NDY5NTcgMTYuMTM2OCAyLjAwNTQyQzIwLjEzNjEgMy40NjEwNCAyMi4zNjc2IDcuNzMyNDkgMjEuMjQyOSAxMS44MzcxQzIwLjkxNTcgMTMuMDMxNCAyMC42MzE4IDE0LjA1MTUgMjAuNDc0OCAxNC41NzkzQzE5LjkxNTcgMTYuNDU4OSAxNy43NTM3IDIwLjg4MyAxNy43NTM3IDIwLjg4M00yLjQwODIgMTQuMDI4NEMyLjQwODIgMTQuMDI4NCAzLjA0MDc4IDEzLjE1NTcgMy4zNzEwNyAxMi41NTE2QzMuNjQzMDQgMTIuMDU0MiAzLjk4NDk2IDExLjIzNjEgMy45ODQ5NiAxMS4yMzYxTTE1LjM3ODQgMTUuNzI5TDE2Ljk3MjYgMTEuMzk2M0MxNy43NjM5IDkuMjQ1NSAxNi42NTcxIDYuODYxMSAxNC41MDM2IDYuMDc3MjhDMTIuMTg4MSA1LjIzNDU0IDkuNjUyMDYgNi41ODg4OCA4Ljk0MDgxIDguOTQ4QzguNDY1OTQgMTAuNTIzMSA3Ljg5NzUyIDEyLjI0MDYgNy4zMTg2NiAxMy42MDMyQzYuMDE1NjUgMTYuNjcwNCA0LjE2MDM0IDE4LjY5MDUgNC4xNjAzNCAxOC42OTA1TTEzLjgwNzMgMTkuNTY3NUMxMy44MDczIDE5LjU2NzUgMTMuNDQwMyAyMC40NTE4IDEzLjEwNTcgMjAuOTcwN0MxMi43MDEgMjEuNTk4MyAxMi4yMjg3IDIyLjE5ODUgMTIuMjI4NyAyMi4xOTg1TTEzLjA4MzYgMTAuNTM5NEMxMy4wODM2IDEwLjUzOTQgMTEuOTYwNiAxMy4yOTcgMTAuODk4MyAxNS44MjI2QzkuNzYzNzMgMTguNTE5OCA3LjIyOTg4IDIxLjMyMTUgNy4yMjk4OCAyMS4zMjE1IiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineBioFingerprint = React.forwardRef<IconLineBioFingerprintRef, IconLineBioFingerprintProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-bio-fingerprint" ref={ref}><path d="M5.47578 7.28963L5.59198 6.96387C7.12288 2.6721 11.855 0.446957 16.1368 2.00542C20.1361 3.46104 22.3676 7.73249 21.2429 11.8371C20.9157 13.0314 20.6318 14.0515 20.4748 14.5793C19.9157 16.4589 17.7537 20.883 17.7537 20.883M2.4082 14.0284C2.4082 14.0284 3.04078 13.1557 3.37107 12.5516C3.64304 12.0542 3.98496 11.2361 3.98496 11.2361M15.3784 15.729L16.9726 11.3963C17.7639 9.2455 16.6571 6.8611 14.5036 6.07728C12.1881 5.23454 9.65206 6.58888 8.94081 8.948C8.46594 10.5231 7.89752 12.2406 7.31866 13.6032C6.01565 16.6704 4.16034 18.6905 4.16034 18.6905M13.8073 19.5675C13.8073 19.5675 13.4403 20.4518 13.1057 20.9707C12.701 21.5983 12.2287 22.1985 12.2287 22.1985M13.0836 10.5394C13.0836 10.5394 11.9606 13.297 10.8983 15.8226C9.76373 18.5198 7.22988 21.3215 7.22988 21.3215" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineBioFingerprint.displayName = definePortfolioDisplayName("IconLineBioFingerprint")

export { IconLineBioFingerprint }