/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineMedicalProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineMedicalRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIgMjJWMjNNMTIgNVYxMk0xMiA1QzEzLjEwNDYgNSAxNCA0LjEwNDU3IDE0IDNDMTQgMS44OTU0MyAxMy4xMDQ2IDEgMTIgMUMxMC44OTU0IDEgMTAgMS44OTU0MyAxMCAzQzEwIDQuMTA0NTcgMTAuODk1NCA1IDEyIDVaTTggNy4xOTczMUM2IDUuNSA1IDQgNSAxSDFNMTYgNy4xOTczMUMxOC41IDUuNSAxOSA0IDE5IDFIMjNNMiA3SDNNMjEgN0gyMk04IDExSDZDNC44OTU0MyAxMSA0IDExLjg5NTQgNCAxM0M0IDE0LjEwNDYgNC44OTU0MyAxNSA2IDE1SDE2QzE3LjEwNDYgMTUgMTggMTUuODk1NCAxOCAxN0MxOCAxOC4xMDQ2IDE3LjEwNDYgMTkgMTYgMTlIOCIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineMedical = React.forwardRef<IconLineMedicalRef, IconLineMedicalProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-medical" ref={ref}><path d="M12 22V23M12 5V12M12 5C13.1046 5 14 4.10457 14 3C14 1.89543 13.1046 1 12 1C10.8954 1 10 1.89543 10 3C10 4.10457 10.8954 5 12 5ZM8 7.19731C6 5.5 5 4 5 1H1M16 7.19731C18.5 5.5 19 4 19 1H23M2 7H3M21 7H22M8 11H6C4.89543 11 4 11.8954 4 13C4 14.1046 4.89543 15 6 15H16C17.1046 15 18 15.8954 18 17C18 18.1046 17.1046 19 16 19H8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineMedical.displayName = definePortfolioDisplayName("IconLineMedical")

export { IconLineMedical }