/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledFilledStarProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledFilledStarRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTEuMzA3NyAyLjY1ODM0QzExLjU2NDMgMi4wNDM1NyAxMi40MzUzIDIuMDQzNTcgMTIuNjkxOSAyLjY1ODM0TDE0Ljg5MzUgNy45MzIyM0MxNC45OTYxIDguMTc3OTIgMTUuMjIxMiA4LjM1MDgyIDE1LjQ4NSA4LjM4NjUzTDIxLjI4NzQgOS4xNzE4NkMyMS45Mzc2IDkuMjU5ODYgMjIuMTY5MyAxMC4wODEzIDIxLjY2MSAxMC40OTYyTDE3LjE4MDcgMTQuMTUyMkMxNi45NTkzIDE0LjMzMjkgMTYuODU5OCAxNC42MjM5IDE2LjkyNDIgMTQuOTAyNEwxOC4zNTY2IDIxLjA5MjJDMTguNTExNyAyMS43NjI0IDE3Ljc1ODEgMjIuMjcwNCAxNy4xOTUxIDIxLjg3NTJMMTIuNDMwNyAxOC41MzEzQzEyLjE3MjEgMTguMzQ5OCAxMS44Mjc1IDE4LjM0OTggMTEuNTY5IDE4LjUzMTNMNi44MDQ1MiAyMS44NzUyQzYuMjQxNDkgMjIuMjcwNCA1LjQ4NzkgMjEuNzYyNCA1LjY0Mjk3IDIxLjA5MjNMNy4wNzUyOCAxNC45MDIzQzcuMTM5NzIgMTQuNjIzOCA3LjA0MDI0IDE0LjMzMjkgNi44MTg3NyAxNC4xNTIyTDIuMzM4NjIgMTAuNDk2MkMxLjgzMDMgMTAuMDgxMyAyLjA2MjA0IDkuMjU5ODYgMi43MTIyMiA5LjE3MTg2TDguNTE0NjEgOC4zODY1M0M4Ljc3ODQ1IDguMzUwODIgOS4wMDM1NyA4LjE3NzkyIDkuMTA2MTQgNy45MzIyM0wxMS4zMDc3IDIuNjU4MzRaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledFilledStar = React.forwardRef<IconFilledFilledStarRef, IconFilledFilledStarProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-filled-star" ref={ref}><path d="M11.3077 2.65834C11.5643 2.04357 12.4353 2.04357 12.6919 2.65834L14.8935 7.93223C14.9961 8.17792 15.2212 8.35082 15.485 8.38653L21.2874 9.17186C21.9376 9.25986 22.1693 10.0813 21.661 10.4962L17.1807 14.1522C16.9593 14.3329 16.8598 14.6239 16.9242 14.9024L18.3566 21.0922C18.5117 21.7624 17.7581 22.2704 17.1951 21.8752L12.4307 18.5313C12.1721 18.3498 11.8275 18.3498 11.569 18.5313L6.80452 21.8752C6.24149 22.2704 5.4879 21.7624 5.64297 21.0923L7.07528 14.9023C7.13972 14.6238 7.04024 14.3329 6.81877 14.1522L2.33862 10.4962C1.8303 10.0813 2.06204 9.25986 2.71222 9.17186L8.51461 8.38653C8.77845 8.35082 9.00357 8.17792 9.10614 7.93223L11.3077 2.65834Z" fill="currentColor" /></IconBase>)
IconFilledFilledStar.displayName = definePortfolioDisplayName("IconFilledFilledStar")

export { IconFilledFilledStar }