/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineHashtagProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineHashtagRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNSA5SDEwLjEyNU0xMC4xMjUgOUgxNi4xMjVNMTAuMTI1IDlMMTIgNE0xMC4xMjUgOUw3Ljg3NSAxNU0xNi4xMjUgOUgyMU0xNi4xMjUgOUwxOCA0TTE2LjEyNSA5TDEzLjg3NSAxNU0zIDE1SDcuODc1TTcuODc1IDE1SDEzLjg3NU03Ljg3NSAxNUw2IDIwTTEzLjg3NSAxNUgxOU0xMy44NzUgMTVMMTIgMjAiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineHashtag = React.forwardRef<IconLineHashtagRef, IconLineHashtagProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-hashtag" ref={ref}><path d="M5 9H10.125M10.125 9H16.125M10.125 9L12 4M10.125 9L7.875 15M16.125 9H21M16.125 9L18 4M16.125 9L13.875 15M3 15H7.875M7.875 15H13.875M7.875 15L6 20M13.875 15H19M13.875 15L12 20" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineHashtag.displayName = definePortfolioDisplayName("IconLineHashtag")

export { IconLineHashtag }