/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineThumbsUpProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineThumbsUpRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNiAxMC41NzI4VjIyLjc1TTE0LjEzMzcgNy4wNzU0MUwxNC41MDQxIDMuOTE1NDNDMTQuNzAxNSAyLjIzMDIyIDEzLjM4NDcgMC43NSAxMS42ODc5IDAuNzVDMTEuMTE5MiAwLjc1IDEwLjYwNTYgMS4wODk4MSAxMC4zODMxIDEuNjEzMThMNy4wMTc1MyA5LjUzMjI4QzYuNzAzNzQgMTAuMjcwNiA1Ljk3OTEyIDEwLjc1IDUuMTc2ODcgMTAuNzVINEMyLjM0MzE1IDEwLjc1IDEgMTIuMDkzMSAxIDEzLjc1VjE5Ljc1QzEgMjEuNDA2OSAyLjM0MzE1IDIyLjc1IDQgMjIuNzVIMTcuNzM3MUMxOS4wNzY1IDIyLjc1IDIwLjI1MzcgMjEuODYyMSAyMC42MjE3IDIwLjU3NDJMMjIuOTA3NCAxMi41NzQyQzIzLjQ1NDkgMTAuNjU3NyAyMi4wMTU5IDguNzUgMjAuMDIyOCA4Ljc1SDE1LjYyMzVDMTQuNzI1OSA4Ljc1IDE0LjAyOTMgNy45NjY5MyAxNC4xMzM3IDcuMDc1NDFaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineThumbsUp = React.forwardRef<IconLineThumbsUpRef, IconLineThumbsUpProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-thumbs-up" ref={ref}><path d="M6 10.5728V22.75M14.1337 7.07541L14.5041 3.91543C14.7015 2.23022 13.3847 0.75 11.6879 0.75C11.1192 0.75 10.6056 1.08981 10.3831 1.61318L7.01753 9.53228C6.70374 10.2706 5.97912 10.75 5.17687 10.75H4C2.34315 10.75 1 12.0931 1 13.75V19.75C1 21.4069 2.34315 22.75 4 22.75H17.7371C19.0765 22.75 20.2537 21.8621 20.6217 20.5742L22.9074 12.5742C23.4549 10.6577 22.0159 8.75 20.0228 8.75H15.6235C14.7259 8.75 14.0293 7.96693 14.1337 7.07541Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineThumbsUp.displayName = definePortfolioDisplayName("IconLineThumbsUp")

export { IconLineThumbsUp }