/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineLinkProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineLinkRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAuNSA3LjAwMDE3TDEzLjgxNzQgMy42MjYyOEMxNS41NjM5IDEuODUgMTguNDIzNSAxLjgzNzkxIDIwLjE4NDkgMy41OTkzN0MyMS45MzU5IDUuMzUwMzYgMjEuOTM1OSA4LjE4OTI3IDIwLjE4NDkgOS45NDAyNUwxNi4xNzk5IDEzLjk0NTJDMTQuNjU5MiAxNS40NjYgMTIuMjA4MiAxNS41MTIgMTAuNjMxNCAxNC4wNDk1TDkuNTAwMDMgMTMuMDAwMk0xMS44NTU0IDE3LjgxMjdMOC41MzgwNCAyMS4xODY2QzYuNzkxNTMgMjIuOTYyOCAzLjkzMTk0IDIyLjk3NDkgMi4xNzA0OCAyMS4yMTM1QzAuNDE5NDkzIDE5LjQ2MjUgMC40MTk0OTIgMTYuNjIzNiAyLjE3MDQ4IDE0Ljg3MjZMNi4xNzU0NSAxMC44Njc2QzcuNjk2MiA5LjM0Njg2IDEwLjE0NzIgOS4zMDA3OSAxMS43MjQgMTAuNzYzM0wxMi44NTU0IDExLjgxMjciIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineLink = React.forwardRef<IconLineLinkRef, IconLineLinkProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-link" ref={ref}><path d="M10.5 7.00017L13.8174 3.62628C15.5639 1.85 18.4235 1.83791 20.1849 3.59937C21.9359 5.35036 21.9359 8.18927 20.1849 9.94025L16.1799 13.9452C14.6592 15.466 12.2082 15.512 10.6314 14.0495L9.50003 13.0002M11.8554 17.8127L8.53804 21.1866C6.79153 22.9628 3.93194 22.9749 2.17048 21.2135C0.419493 19.4625 0.419492 16.6236 2.17048 14.8726L6.17545 10.8676C7.6962 9.34686 10.1472 9.30079 11.724 10.7633L12.8554 11.8127" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineLink.displayName = definePortfolioDisplayName("IconLineLink")

export { IconLineLink }