/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineAirlinePlaneProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineAirlinePlaneRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNC44NjQwNyA2LjEzNTczTDcuMTc4MjQgMy44MjE1N0wxNS4yNzc4IDUuNjIxNDhMMTcuNTMzMiAzLjM2NjEzQzE3LjU3MjQgMy4zMjY5MyAxNy42MTE2IDMuMjkwNjcgMTcuNjU0NiAzLjI1NTY4QzE4LjA5NiAyLjg5NjMzIDIwLjc1NTYgMC44MTQwOTcgMjEuODM0NiAxLjg5MzA5QzIyLjkxMzYgMi45NzIwOSAyMC44MzE0IDUuNjMxNyAyMC40NzIgNi4wNzMxN0MyMC40MzcxIDYuMTE2MTYgMjAuNDAwOCA2LjE1NTM2IDIwLjM2MTYgNi4xOTQ1NkwxOC4xMDYzIDguNDQ5OUwxOS45MDYyIDE2LjU0OTVMMTcuNTkyIDE4Ljg2MzdMMTMuOTE1IDEyLjQyOUw5LjEwNjcxIDE2Ljc0MjNMOS42ODUyNSAxOS42OTkzTDcuNjkyNSAyMS42OTIxTDUuODI4MzEgMTcuODk5NEwyLjAzNTY0IDE2LjAzNTJMNC4wMjg0IDE0LjA0MjVMNi45ODUzOSAxNC42MjFMMTEuMjk4NyA5LjgxMjY5TDQuODY0MDcgNi4xMzU3M1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineAirlinePlane = React.forwardRef<IconLineAirlinePlaneRef, IconLineAirlinePlaneProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-airline-plane" ref={ref}><path d="M4.86407 6.13573L7.17824 3.82157L15.2778 5.62148L17.5332 3.36613C17.5724 3.32693 17.6116 3.29067 17.6546 3.25568C18.096 2.89633 20.7556 0.814097 21.8346 1.89309C22.9136 2.97209 20.8314 5.6317 20.472 6.07317C20.4371 6.11616 20.4008 6.15536 20.3616 6.19456L18.1063 8.4499L19.9062 16.5495L17.592 18.8637L13.915 12.429L9.10671 16.7423L9.68525 19.6993L7.6925 21.6921L5.82831 17.8994L2.03564 16.0352L4.0284 14.0425L6.98539 14.621L11.2987 9.81269L4.86407 6.13573Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineAirlinePlane.displayName = definePortfolioDisplayName("IconLineAirlinePlane")

export { IconLineAirlinePlane }