/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledMediumProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledMediumRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTIuODQ2IDYuODg3QzIuODc2IDYuNTkyIDIuNzYzIDYuMzAxIDIuNTQzIDYuMTAzTDAuMzAzIDMuNDAzVjNINy4yNjFMMTIuNjM5IDE0Ljc5NUwxNy4zNjcgM0gyNFYzLjQwM0wyMi4wODQgNS4yNEMyMS45MTkgNS4zNjYgMjEuODM3IDUuNTczIDIxLjg3MSA1Ljc3OFYxOS4yNzZDMjEuODM3IDE5LjQ4IDIxLjkxOSAxOS42ODcgMjIuMDg0IDE5LjgxM0wyMy45NTUgMjEuNjVWMjIuMDUzSDE0LjU0M1YyMS42NUwxNi40ODIgMTkuNzY4QzE2LjY3MiAxOS41NzggMTYuNjcyIDE5LjUyMiAxNi42NzIgMTkuMjMxVjguMzIxTDExLjI4MyAyMi4wMDlIMTAuNTU1TDQuMjggOC4zMjFWMTcuNDk1QzQuMjI4IDE3Ljg4IDQuMzU2IDE4LjI2OSA0LjYyNyAxOC41NDdMNy4xNDggMjEuNjA1VjIyLjAwOUgwVjIxLjYwNUwyLjUyMSAxOC41NDdDMi43OTEgMTguMjY4IDIuOTExIDE3Ljg3NyAyLjg0NiAxNy40OTVWNi44ODdaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledMedium = React.forwardRef<IconFilledMediumRef, IconFilledMediumProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-medium" ref={ref}><path fill-rule="evenodd" clip-rule="evenodd" d="M2.846 6.887C2.876 6.592 2.763 6.301 2.543 6.103L0.303 3.403V3H7.261L12.639 14.795L17.367 3H24V3.403L22.084 5.24C21.919 5.366 21.837 5.573 21.871 5.778V19.276C21.837 19.48 21.919 19.687 22.084 19.813L23.955 21.65V22.053H14.543V21.65L16.482 19.768C16.672 19.578 16.672 19.522 16.672 19.231V8.321L11.283 22.009H10.555L4.28 8.321V17.495C4.228 17.88 4.356 18.269 4.627 18.547L7.148 21.605V22.009H0V21.605L2.521 18.547C2.791 18.268 2.911 17.877 2.846 17.495V6.887Z" fill="currentColor" /></IconBase>)
IconFilledMedium.displayName = definePortfolioDisplayName("IconFilledMedium")

export { IconFilledMedium }