/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineExportProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineExportRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjUiIHZpZXdCb3g9IjAgMCAyNCAyNSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjAgMTIuMzg5NlYxNy4zODk2QzIwIDIwLjE1MTEgMTcuNzYxNCAyMi4zODk2IDE1IDIyLjM4OTZIOEM1LjIzODU4IDIyLjM4OTYgMyAyMC4xNTExIDMgMTcuMzg5NlYxMi4zODk2TTE2Ljg4OTQgNS45NDQ0NUwxMS43Mjk0IDAuNzVNMTEuNzI5NCAwLjc1TDYuNTY5NTIgNS45NDQ0NU0xMS43Mjk0IDAuNzVMMTEuNzI4NyAxMi42NDk2IiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineExport = React.forwardRef<IconLineExportRef, IconLineExportProps>((props, ref) => <IconBase {...props} width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-export" ref={ref}><path d="M20 12.3896V17.3896C20 20.1511 17.7614 22.3896 15 22.3896H8C5.23858 22.3896 3 20.1511 3 17.3896V12.3896M16.8894 5.94445L11.7294 0.75M11.7294 0.75L6.56952 5.94445M11.7294 0.75L11.7287 12.6496" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineExport.displayName = definePortfolioDisplayName("IconLineExport")

export { IconLineExport }