/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineThreePeopleProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineThreePeopleRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTcgMjBWMThNMTcgMjBIN00xNyAyMEgyM1YxOC41QzIzIDE2LjU2NyAyMS40MzMgMTUgMTkuNSAxNUMxOC4zNzA4IDE1IDE3LjM2NjUgMTUuNTM0OCAxNi43MjY1IDE2LjM2NDhDMTYuOTAzNyAxNi44NzcyIDE3IDE3LjQyNzQgMTcgMThNNyAyMFYxOE03IDIwSDFWMTguNUMxIDE2LjU2NyAyLjU2NyAxNSA0LjUgMTVDNS42MjkyMSAxNSA2LjYzMzUxIDE1LjUzNDggNy4yNzM0OSAxNi4zNjQ4QzcuMDk2MjYgMTYuODc3MiA3IDE3LjQyNzQgNyAxOE0xNyAxOEMxNyAxNS4yMzg2IDE0Ljc2MTQgMTMgMTIgMTNDOS4yMzg1OCAxMyA3IDE1LjIzODYgNyAxOE0xNSA3QzE1IDguNjU2ODUgMTMuNjU2OSAxMCAxMiAxMEMxMC4zNDMxIDEwIDkgOC42NTY4NSA5IDdDOSA1LjM0MzE1IDEwLjM0MzEgNCAxMiA0QzEzLjY1NjkgNCAxNSA1LjM0MzE1IDE1IDdaTTYgMTBDNiAxMS4xMDQ2IDUuMTA0NTcgMTIgNCAxMkMyLjg5NTQzIDEyIDIgMTEuMTA0NiAyIDEwQzIgOC44OTU0MyAyLjg5NTQzIDggNCA4QzUuMTA0NTcgOCA2IDguODk1NDMgNiAxMFpNMjIgMTBDMjIgMTEuMTA0NiAyMS4xMDQ2IDEyIDIwIDEyQzE4Ljg5NTQgMTIgMTggMTEuMTA0NiAxOCAxMEMxOCA4Ljg5NTQzIDE4Ljg5NTQgOCAyMCA4QzIxLjEwNDYgOCAyMiA4Ljg5NTQzIDIyIDEwWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgLz48L3N2Zz4=) */
const IconLineThreePeople = React.forwardRef<IconLineThreePeopleRef, IconLineThreePeopleProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-three-people" ref={ref}><path d="M17 20V18M17 20H7M17 20H23V18.5C23 16.567 21.433 15 19.5 15C18.3708 15 17.3665 15.5348 16.7265 16.3648C16.9037 16.8772 17 17.4274 17 18M7 20V18M7 20H1V18.5C1 16.567 2.567 15 4.5 15C5.62921 15 6.63351 15.5348 7.27349 16.3648C7.09626 16.8772 7 17.4274 7 18M17 18C17 15.2386 14.7614 13 12 13C9.23858 13 7 15.2386 7 18M15 7C15 8.65685 13.6569 10 12 10C10.3431 10 9 8.65685 9 7C9 5.34315 10.3431 4 12 4C13.6569 4 15 5.34315 15 7ZM6 10C6 11.1046 5.10457 12 4 12C2.89543 12 2 11.1046 2 10C2 8.89543 2.89543 8 4 8C5.10457 8 6 8.89543 6 10ZM22 10C22 11.1046 21.1046 12 20 12C18.8954 12 18 11.1046 18 10C18 8.89543 18.8954 8 20 8C21.1046 8 22 8.89543 22 10Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineThreePeople.displayName = definePortfolioDisplayName("IconLineThreePeople")

export { IconLineThreePeople }