/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineFastForwardProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineFastForwardRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTguNTMgNEwxOC41Mjc0IDEyTTE4LjUzIDIwTDE4LjUyNzQgMTJNMTguNTI3NCAxMkMxOC41Mjc2IDExLjUwMzIgMTguMjg1NyAxMS4wMDYzIDE3LjgwMTcgMTAuNzE0Nkw3LjI3NDI3IDQuMzY5OTVDNi4yNzQ1NCAzLjc2NzQzIDUgNC40ODc0MSA1IDUuNjU0NjdWMTguMzQzOUM1IDE5LjUxMTIgNi4yNzQ1NCAyMC4yMzEyIDcuMjc0MjcgMTkuNjI4NkwxNy44MDE3IDEzLjI4NEMxOC4yODUyIDEyLjk5MjYgMTguNTI3MiAxMi40OTYzIDE4LjUyNzQgMTJaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIC8+PC9zdmc+) */
const IconLineFastForward = React.forwardRef<IconLineFastForwardRef, IconLineFastForwardProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-fast-forward" ref={ref}><path d="M18.53 4L18.5274 12M18.53 20L18.5274 12M18.5274 12C18.5276 11.5032 18.2857 11.0063 17.8017 10.7146L7.27427 4.36995C6.27454 3.76743 5 4.48741 5 5.65467V18.3439C5 19.5112 6.27454 20.2312 7.27427 19.6286L17.8017 13.284C18.2852 12.9926 18.5272 12.4963 18.5274 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineFastForward.displayName = definePortfolioDisplayName("IconLineFastForward")

export { IconLineFastForward }