/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineComponentInstanceProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineComponentInstanceRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMS44NDkxMiAxMi4wNTAzTDExLjg5OTQgMkwyMS45NDk3IDEyLjA1MDNMMTEuODk5NCAyMi4xMDA2TDEuODQ5MTIgMTIuMDUwM1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineComponentInstance = React.forwardRef<IconLineComponentInstanceRef, IconLineComponentInstanceProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-component-instance" ref={ref}><path d="M1.84912 12.0503L11.8994 2L21.9497 12.0503L11.8994 22.1006L1.84912 12.0503Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineComponentInstance.displayName = definePortfolioDisplayName("IconLineComponentInstance")

export { IconLineComponentInstance }