/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineGymWeightProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineGymWeightRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOSAxMkgxNU0yMiAxMkgyM00xIDEySDJNNyAxOEM1Ljg5NTQzIDE4IDUgMTcuMTA0NiA1IDE2VjhDNSA2Ljg5NTQzIDUuODk1NDMgNiA3IDZDOC4xMDQ1NyA2IDkgNi44OTU0MyA5IDhWMTZDOSAxNy4xMDQ2IDguMTA0NTcgMTggNyAxOFpNMy41IDE2QzIuNjcxNTcgMTYgMiAxNS4zMjg0IDIgMTQuNVY5LjVDMiA4LjY3MTU3IDIuNjcxNTcgOCAzLjUgOEM0LjMyODQzIDggNSA4LjY3MTU3IDUgOS41VjE0LjVDNSAxNS4zMjg0IDQuMzI4NDMgMTYgMy41IDE2Wk0xNyAxOEMxNS44OTU0IDE4IDE1IDE3LjEwNDYgMTUgMTZWOEMxNSA2Ljg5NTQzIDE1Ljg5NTQgNiAxNyA2QzE4LjEwNDYgNiAxOSA2Ljg5NTQzIDE5IDhWMTZDMTkgMTcuMTA0NiAxOC4xMDQ2IDE4IDE3IDE4Wk0yMC41IDE2QzE5LjY3MTYgMTYgMTkgMTUuMzI4NCAxOSAxNC41VjkuNUMxOSA4LjY3MTU3IDE5LjY3MTYgOCAyMC41IDhDMjEuMzI4NCA4IDIyIDguNjcxNTcgMjIgOS41VjE0LjVDMjIgMTUuMzI4NCAyMS4zMjg0IDE2IDIwLjUgMTZaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIC8+PC9zdmc+) */
const IconLineGymWeight = React.forwardRef<IconLineGymWeightRef, IconLineGymWeightProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-gym-weight" ref={ref}><path d="M9 12H15M22 12H23M1 12H2M7 18C5.89543 18 5 17.1046 5 16V8C5 6.89543 5.89543 6 7 6C8.10457 6 9 6.89543 9 8V16C9 17.1046 8.10457 18 7 18ZM3.5 16C2.67157 16 2 15.3284 2 14.5V9.5C2 8.67157 2.67157 8 3.5 8C4.32843 8 5 8.67157 5 9.5V14.5C5 15.3284 4.32843 16 3.5 16ZM17 18C15.8954 18 15 17.1046 15 16V8C15 6.89543 15.8954 6 17 6C18.1046 6 19 6.89543 19 8V16C19 17.1046 18.1046 18 17 18ZM20.5 16C19.6716 16 19 15.3284 19 14.5V9.5C19 8.67157 19.6716 8 20.5 8C21.3284 8 22 8.67157 22 9.5V14.5C22 15.3284 21.3284 16 20.5 16Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineGymWeight.displayName = definePortfolioDisplayName("IconLineGymWeight")

export { IconLineGymWeight }