/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledTinderProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledTinderRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTcuMTkxNDEgOS42ODk5N0M3LjE3NjY1IDkuNjk0NTkgNy4xNjA2IDkuNjk1MSA3LjE0NTQ5IDkuNjkxNDVDNy4xMzAzOCA5LjY4NzggNy4xMTY5NCA5LjY4MDE2IDcuMTA3MDMgOS42Njk1OUM2LjE3NDIyIDguNTk1MTYgNS45Mzk4NCA2Ljc0ODA1IDUuODgyODEgNi4wMzg1NkM1Ljg3MTA5IDUuOTAxOTYgNS42OTQ1MyA1LjgyNTE3IDUuNTUzMTIgNS44OTM4MUMyLjY3MjY2IDcuMzAxMjMgMCAxMC42MzA1IDAgMTMuODQ1QzAgMTkuMzY3MyA0LjQwOTM4IDI0IDEyIDI0QzE5LjExMTcgMjQgMjQgMTkuMjI1MiAyNCAxMy44NDU2QzI0IDYuODA2NDkgMTguMjE3MiAyLjEyOTU5IDEzLjA2NjQgMC4wMTUzOTczQzEzLjAzNjMgMC4wMDMwMzU2NiAxMy4wMDI5IC0wLjAwMjAyOTY0IDEyLjk2OTcgMC4wMDA3MzUxNDNDMTIuOTM2NiAwLjAwMzQ5OTkzIDEyLjkwNDkgMC4wMTM5OTI0IDEyLjg3OCAwLjAzMTEwNzFDMTIuODUxMiAwLjA0ODIyMTcgMTIuODMwMSAwLjA3MTMyNDggMTIuODE3IDAuMDk3OTgxOUMxMi44MDQgMC4xMjQ2MzkgMTIuNzk5NSAwLjE1Mzg2MyAxMi44MDM5IDAuMTgyNTc1QzEzLjQ2NzIgMy45NzYwMiAxMi41NTA4IDguMTAxNzggNy4xOTE0MSA5LjY4OTk3WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledTinder = React.forwardRef<IconFilledTinderRef, IconFilledTinderProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-tinder" ref={ref}><path fill-rule="evenodd" clip-rule="evenodd" d="M7.19141 9.68997C7.17665 9.69459 7.1606 9.6951 7.14549 9.69145C7.13038 9.6878 7.11694 9.68016 7.10703 9.66959C6.17422 8.59516 5.93984 6.74805 5.88281 6.03856C5.87109 5.90196 5.69453 5.82517 5.55312 5.89381C2.67266 7.30123 0 10.6305 0 13.845C0 19.3673 4.40938 24 12 24C19.1117 24 24 19.2252 24 13.8456C24 6.80649 18.2172 2.12959 13.0664 0.0153973C13.0363 0.00303566 13.0029 -0.00202964 12.9697 0.000735143C12.9366 0.00349993 12.9049 0.0139924 12.878 0.0311071C12.8512 0.0482217 12.8301 0.0713248 12.817 0.0979819C12.804 0.124639 12.7995 0.153863 12.8039 0.182575C13.4672 3.97602 12.5508 8.10178 7.19141 9.68997Z" fill="currentColor" /></IconBase>)
IconFilledTinder.displayName = definePortfolioDisplayName("IconFilledTinder")

export { IconFilledTinder }