/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineMicrophoneProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineMicrophoneRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNCA5LjVWMTFDNCAxNS40MTgzIDcuNTgxNzIgMTkgMTIgMTlNMjAgOS41VjExQzIwIDE1LjQxODMgMTYuNDE4MyAxOSAxMiAxOU0xMiAxOVYyM00xNiAyM0g4TTEyIDE1QzkuNzkwODYgMTUgOCAxMy4yMDkxIDggMTFWNUM4IDIuNzkwODYgOS43OTA4NiAxIDEyIDFDMTQuMjA5MSAxIDE2IDIuNzkwODYgMTYgNVYxMUMxNiAxMy4yMDkxIDE0LjIwOTEgMTUgMTIgMTVaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIC8+PC9zdmc+) */
const IconLineMicrophone = React.forwardRef<IconLineMicrophoneRef, IconLineMicrophoneProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-microphone" ref={ref}><path d="M4 9.5V11C4 15.4183 7.58172 19 12 19M20 9.5V11C20 15.4183 16.4183 19 12 19M12 19V23M16 23H8M12 15C9.79086 15 8 13.2091 8 11V5C8 2.79086 9.79086 1 12 1C14.2091 1 16 2.79086 16 5V11C16 13.2091 14.2091 15 12 15Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineMicrophone.displayName = definePortfolioDisplayName("IconLineMicrophone")

export { IconLineMicrophone }