/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineLogInCircleProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineLogInCircleRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNS4zNDMxNiAxOS4wNzExQzkuMjQ4NDEgMjIuOTc2MyAxNS41ODAxIDIyLjk3NjMgMTkuNDg1MyAxOS4wNzExQzIzLjM5MDUgMTUuMTY1OCAyMy4zOTA1IDguODM0MTggMTkuNDg1MyA0LjkyODkzQzE1LjU4MDEgMS4wMjM2OSA5LjI0ODQxIDEuMDIzNjkgNS4zNDMxNiA0LjkyODkzTTExIDkuMDAwMjRMMTMuNjY2NyAxMi4wMDAyTDExIDE1LjAwMDJNMTMuNSAxMi4wMDAySDEiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineLogInCircle = React.forwardRef<IconLineLogInCircleRef, IconLineLogInCircleProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-log-in-circle" ref={ref}><path d="M5.34316 19.0711C9.24841 22.9763 15.5801 22.9763 19.4853 19.0711C23.3905 15.1658 23.3905 8.83418 19.4853 4.92893C15.5801 1.02369 9.24841 1.02369 5.34316 4.92893M11 9.00024L13.6667 12.0002L11 15.0002M13.5 12.0002H1" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineLogInCircle.displayName = definePortfolioDisplayName("IconLineLogInCircle")

export { IconLineLogInCircle }