/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBackspaceProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBackspaceRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjUiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNSAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAuNTIzOSA5TDE2LjUyMzkgMTVNMTAuNTIzOSAxNUwxNi41MjM5IDlNMC45MzQzODcgMTIuNTc4Nkw2LjAxMTcxIDE5LjczNThDNi41NzQyNyAyMC41Mjg4IDcuNDg2MjcgMjEgOC40NTg1NSAyMUgyMC41MjM5QzIyLjE4MDggMjEgMjMuNTIzOSAxOS42NTY5IDIzLjUyMzkgMThWNkMyMy41MjM5IDQuMzQzMTUgMjIuMTgwOCAzIDIwLjUyMzkgM0g4LjQ1ODU1QzcuNDg2MjcgMyA2LjU3NDI3IDMuNDcxMiA2LjAxMTcxIDQuMjY0MjFMMC45MzQzODcgMTEuNDIxNEMwLjY4ODUzOCAxMS43NjggMC42ODg1MzggMTIuMjMyIDAuOTM0Mzg3IDEyLjU3ODZaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineBackspace = React.forwardRef<IconLineBackspaceRef, IconLineBackspaceProps>((props, ref) => <IconBase {...props} width="25" height="24" viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-backspace" ref={ref}><path d="M10.5239 9L16.5239 15M10.5239 15L16.5239 9M0.934387 12.5786L6.01171 19.7358C6.57427 20.5288 7.48627 21 8.45855 21H20.5239C22.1808 21 23.5239 19.6569 23.5239 18V6C23.5239 4.34315 22.1808 3 20.5239 3H8.45855C7.48627 3 6.57427 3.4712 6.01171 4.26421L0.934387 11.4214C0.688538 11.768 0.688538 12.232 0.934387 12.5786Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineBackspace.displayName = definePortfolioDisplayName("IconLineBackspace")

export { IconLineBackspace }