/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineSparkleStarProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineSparkleStarRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTEuNDI4OSAyLjQ0MzQ1QzExLjU4MDEgMS44NTIxOCAxMi40MTk5IDEuODUyMTkgMTIuNTcxMSAyLjQ0MzQ1TDEzLjM2MjIgNS41MzY5OEMxNC4wMDI3IDguMDQxNTcgMTUuOTU4NCA5Ljk5NzMxIDE4LjQ2MyAxMC42Mzc4TDIxLjU1NjYgMTEuNDI4OUMyMi4xNDc4IDExLjU4MDEgMjIuMTQ3OCAxMi40MTk5IDIxLjU1NjYgMTIuNTcxMUwxOC40NjMgMTMuMzYyMkMxNS45NTg0IDE0LjAwMjcgMTQuMDAyNyAxNS45NTg0IDEzLjM2MjIgMTguNDYzTDEyLjU3MTEgMjEuNTU2NkMxMi40MTk5IDIyLjE0NzggMTEuNTgwMSAyMi4xNDc4IDExLjQyODkgMjEuNTU2NkwxMC42Mzc4IDE4LjQ2M0M5Ljk5NzMxIDE1Ljk1ODQgOC4wNDE1NyAxNC4wMDI3IDUuNTM2OTggMTMuMzYyMkwyLjQ0MzQ1IDEyLjU3MTFDMS44NTIxOCAxMi40MTk5IDEuODUyMTkgMTEuNTgwMSAyLjQ0MzQ1IDExLjQyODlMNS41MzY5OCAxMC42Mzc4QzguMDQxNTcgOS45OTczMSA5Ljk5NzMxIDguMDQxNTcgMTAuNjM3OCA1LjUzNjk4TDExLjQyODkgMi40NDM0NVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineSparkleStar = React.forwardRef<IconLineSparkleStarRef, IconLineSparkleStarProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-sparkle-star" ref={ref}><path d="M11.4289 2.44345C11.5801 1.85218 12.4199 1.85219 12.5711 2.44345L13.3622 5.53698C14.0027 8.04157 15.9584 9.99731 18.463 10.6378L21.5566 11.4289C22.1478 11.5801 22.1478 12.4199 21.5566 12.5711L18.463 13.3622C15.9584 14.0027 14.0027 15.9584 13.3622 18.463L12.5711 21.5566C12.4199 22.1478 11.5801 22.1478 11.4289 21.5566L10.6378 18.463C9.99731 15.9584 8.04157 14.0027 5.53698 13.3622L2.44345 12.5711C1.85218 12.4199 1.85219 11.5801 2.44345 11.4289L5.53698 10.6378C8.04157 9.99731 9.99731 8.04157 10.6378 5.53698L11.4289 2.44345Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineSparkleStar.displayName = definePortfolioDisplayName("IconLineSparkleStar")

export { IconLineSparkleStar }