/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineCircleCurrencyDollarProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineCircleCurrencyDollarRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIgNlYxOE05IDE1LjE4Mkw5Ljg3OSAxNS44NDFDMTEuMDUgMTYuNzIgMTIuOTQ5IDE2LjcyIDE0LjEyMSAxNS44NDFDMTUuMjkzIDE0Ljk2MiAxNS4yOTMgMTMuNTM4IDE0LjEyMSAxMi42NTlDMTMuNTM2IDEyLjIxOSAxMi43NjggMTIgMTIgMTJDMTEuMjc1IDEyIDEwLjU1IDExLjc4IDkuOTk3IDExLjM0MUM4Ljg5MSAxMC40NjIgOC44OTEgOS4wMzggOS45OTcgOC4xNTlDMTEuMTAzIDcuMjggMTIuODk3IDcuMjggMTQuMDAzIDguMTU5TDE0LjQxOCA4LjQ4OU0yMiAxMkMyMiAxNy41MjI4IDE3LjUyMjggMjIgMTIgMjJDNi40NzcxNSAyMiAyIDE3LjUyMjggMiAxMkMyIDYuNDc3MTUgNi40NzcxNSAyIDEyIDJDMTcuNTIyOCAyIDIyIDYuNDc3MTUgMjIgMTJaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineCircleCurrencyDollar = React.forwardRef<IconLineCircleCurrencyDollarRef, IconLineCircleCurrencyDollarProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-circle-currency-dollar" ref={ref}><path d="M12 6V18M9 15.182L9.879 15.841C11.05 16.72 12.949 16.72 14.121 15.841C15.293 14.962 15.293 13.538 14.121 12.659C13.536 12.219 12.768 12 12 12C11.275 12 10.55 11.78 9.997 11.341C8.891 10.462 8.891 9.038 9.997 8.159C11.103 7.28 12.897 7.28 14.003 8.159L14.418 8.489M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineCircleCurrencyDollar.displayName = definePortfolioDisplayName("IconLineCircleCurrencyDollar")

export { IconLineCircleCurrencyDollar }