/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWeatherThunderstormsProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWeatherThunderstormsRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMS41IDE0TDUuNTAwMDMgOS41QzUuNTAwMDMgOS41IDUuMDA4NzkgOC40NDc5NiA1LjAwODc5IDdDNS4wMDg3OSAzLjY4NjI5IDcuOTM5MjkgMSAxMS41NTQyIDFDMTMuOTc3IDEgMTYuMDkyMyAyLjIwNjYgMTcuMjI0IDRIMTguNTA4OEMyMC45OTQxIDQgMjMuMDA4OCA2LjAxNDcyIDIzLjAwODggOC41QzIzLjAwODggMTAuMDY0IDIyIDEyIDIxIDEzLjI0ODFDMjAgMTQuNDk2MiAxNCAyMS41IDE0IDIxLjVNMTYuODY3NiAxMS4yOTQxTDE2LjIyNDggMTIuMDYwMk0zIDE5TDIgMjBNMTIuODAzNSA4LjcyMjc2TDYuNjYxMiAxNS44NTExTDExLjY1MzcgMTYuMTI0MUw1Ljk5OTk5IDIyLjUwMDEiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineWeatherThunderstorms = React.forwardRef<IconLineWeatherThunderstormsRef, IconLineWeatherThunderstormsProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-weather-thunderstorms" ref={ref}><path d="M1.5 14L5.50003 9.5C5.50003 9.5 5.00879 8.44796 5.00879 7C5.00879 3.68629 7.93929 1 11.5542 1C13.977 1 16.0923 2.2066 17.224 4H18.5088C20.9941 4 23.0088 6.01472 23.0088 8.5C23.0088 10.064 22 12 21 13.2481C20 14.4962 14 21.5 14 21.5M16.8676 11.2941L16.2248 12.0602M3 19L2 20M12.8035 8.72276L6.6612 15.8511L11.6537 16.1241L5.99999 22.5001" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineWeatherThunderstorms.displayName = definePortfolioDisplayName("IconLineWeatherThunderstorms")

export { IconLineWeatherThunderstorms }