/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineFileStructureProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineFileStructureRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOCAxOUg0VjdNNCAxVjdNNCA3SDhNMTYuNjQ0NCAzSDE1QzEzLjg5NTQgMyAxMyAzLjg5NTQzIDEzIDVWOUMxMyAxMC4xMDQ2IDEzLjg5NTQgMTEgMTUgMTFIMThDMTkuMTA0NiAxMSAyMCAxMC4xMDQ2IDIwIDlWNi43NjkwNkMyMCA2LjMyOTI2IDE5Ljg1NSA1LjkwMTcyIDE5LjU4NzUgNS41NTI2MUwxOC4yMzIgMy43ODM1NUMxNy44NTM1IDMuMjg5NjMgMTcuMjY2NyAzIDE2LjY0NDQgM1pNMTYuNjQ0NCAxNUgxNUMxMy44OTU0IDE1IDEzIDE1Ljg5NTQgMTMgMTdWMjFDMTMgMjIuMTA0NiAxMy44OTU0IDIzIDE1IDIzSDE4QzE5LjEwNDYgMjMgMjAgMjIuMTA0NiAyMCAyMVYxOC43NjkxQzIwIDE4LjMyOTMgMTkuODU1IDE3LjkwMTcgMTkuNTg3NSAxNy41NTI2TDE4LjIzMiAxNS43ODM1QzE3Ljg1MzUgMTUuMjg5NiAxNy4yNjY3IDE1IDE2LjY0NDQgMTVaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineFileStructure = React.forwardRef<IconLineFileStructureRef, IconLineFileStructureProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-file-structure" ref={ref}><path d="M8 19H4V7M4 1V7M4 7H8M16.6444 3H15C13.8954 3 13 3.89543 13 5V9C13 10.1046 13.8954 11 15 11H18C19.1046 11 20 10.1046 20 9V6.76906C20 6.32926 19.855 5.90172 19.5875 5.55261L18.232 3.78355C17.8535 3.28963 17.2667 3 16.6444 3ZM16.6444 15H15C13.8954 15 13 15.8954 13 17V21C13 22.1046 13.8954 23 15 23H18C19.1046 23 20 22.1046 20 21V18.7691C20 18.3293 19.855 17.9017 19.5875 17.5526L18.232 15.7835C17.8535 15.2896 17.2667 15 16.6444 15Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineFileStructure.displayName = definePortfolioDisplayName("IconLineFileStructure")

export { IconLineFileStructure }