/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBattery50Props = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBattery50Ref = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuNDI4NiA5LjQyODU3SDIxLjgyMTRDMjIuNDcyIDkuNDI4NTcgMjMgMTAuMDA0NiAyMyAxMC43MTQzVjEzLjI4NTdDMjMgMTMuOTk1NCAyMi40NzIgMTQuNTcxNCAyMS44MjE0IDE0LjU3MTRIMjEuNDI4Nk0zLjM1NzE0IDE4SDE5LjA3MTRDMTkuNjk2NiAxOCAyMC4yOTYxIDE3LjcyOTEgMjAuNzM4MiAxNy4yNDY4QzIxLjE4MDIgMTYuNzY0NiAyMS40Mjg2IDE2LjExMDYgMjEuNDI4NiAxNS40Mjg2VjguNTcxNDNDMjEuNDI4NiA3Ljg4OTQ0IDIxLjE4MDIgNy4yMzUzOSAyMC43MzgyIDYuNzUzMTVDMjAuMjk2MSA2LjI3MDkyIDE5LjY5NjYgNiAxOS4wNzE0IDZIMy4zNTcxNEMyLjczMTk5IDYgMi4xMzI0NCA2LjI3MDkyIDEuNjkwMzkgNi43NTMxNUMxLjI0ODM0IDcuMjM1MzkgMSA3Ljg4OTQ0IDEgOC41NzE0M1YxNS40Mjg2QzEgMTYuMTEwNiAxLjI0ODM0IDE2Ljc2NDYgMS42OTAzOSAxNy4yNDY4QzIuMTMyNDQgMTcuNzI5MSAyLjczMTk5IDE4IDMuMzU3MTQgMThaTTUuMjUgMTVIMTAuNzVDMTEuNDQwNCAxNSAxMiAxNC40NDA0IDEyIDEzLjc1VjEwLjI1QzEyIDkuNTU5NjQgMTEuNDQwNCA5IDEwLjc1IDlINS4yNUM0LjU1OTY0IDkgNCA5LjU1OTY0IDQgMTAuMjVWMTMuNzVDNCAxNC40NDA0IDQuNTU5NjQgMTUgNS4yNSAxNVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineBattery50 = React.forwardRef<IconLineBattery50Ref, IconLineBattery50Props>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-battery-50" ref={ref}><path d="M21.4286 9.42857H21.8214C22.472 9.42857 23 10.0046 23 10.7143V13.2857C23 13.9954 22.472 14.5714 21.8214 14.5714H21.4286M3.35714 18H19.0714C19.6966 18 20.2961 17.7291 20.7382 17.2468C21.1802 16.7646 21.4286 16.1106 21.4286 15.4286V8.57143C21.4286 7.88944 21.1802 7.23539 20.7382 6.75315C20.2961 6.27092 19.6966 6 19.0714 6H3.35714C2.73199 6 2.13244 6.27092 1.69039 6.75315C1.24834 7.23539 1 7.88944 1 8.57143V15.4286C1 16.1106 1.24834 16.7646 1.69039 17.2468C2.13244 17.7291 2.73199 18 3.35714 18ZM5.25 15H10.75C11.4404 15 12 14.4404 12 13.75V10.25C12 9.55964 11.4404 9 10.75 9H5.25C4.55964 9 4 9.55964 4 10.25V13.75C4 14.4404 4.55964 15 5.25 15Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineBattery50.displayName = definePortfolioDisplayName("IconLineBattery50")

export { IconLineBattery50 }