/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineSkipForwardProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineSkipForwardRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIuMjA0MSA2LjgwMjMzQzEyLjIwNDEgNS42MDQyOCAxMy41MzkzIDQuODg5NyAxNC41MzYyIDUuNTU0MjVMMjIuMzMyIDEwLjc1MTVDMjMuMjIyNiAxMS4zNDUyIDIzLjIyMjYgMTIuNjUzOSAyMi4zMzIgMTMuMjQ3NkwxNC41MzYyIDE4LjQ0NDlDMTMuNTM5MyAxOS4xMDk0IDEyLjIwNDEgMTguMzk0OCAxMi4yMDQxIDE3LjE5NjhWNi44MDIzM1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48cGF0aCBkPSJNMS4yMDQxIDYuODAyMzNDMS4yMDQxIDUuNjA0MjggMi41MzkzMiA0Ljg4OTcgMy41MzYxNSA1LjU1NDI1TDExLjUzIDEwLjc1MTVDMTIuNDIwNiAxMS4zNDUyIDEyLjQyMDYgMTIuNjUzOSAxMS41MyAxMy4yNDc2TDMuNTM2MTUgMTguNDQ0OUMyLjUzOTMyIDE5LjEwOTQgMS4yMDQxIDE4LjM5NDggMS4yMDQxIDE3LjE5NjhWNi44MDIzM1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineSkipForward = React.forwardRef<IconLineSkipForwardRef, IconLineSkipForwardProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-skip-forward" ref={ref}><path d="M12.2041 6.80233C12.2041 5.60428 13.5393 4.8897 14.5362 5.55425L22.332 10.7515C23.2226 11.3452 23.2226 12.6539 22.332 13.2476L14.5362 18.4449C13.5393 19.1094 12.2041 18.3948 12.2041 17.1968V6.80233Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /><path d="M1.2041 6.80233C1.2041 5.60428 2.53932 4.8897 3.53615 5.55425L11.53 10.7515C12.4206 11.3452 12.4206 12.6539 11.53 13.2476L3.53615 18.4449C2.53932 19.1094 1.2041 18.3948 1.2041 17.1968V6.80233Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineSkipForward.displayName = definePortfolioDisplayName("IconLineSkipForward")

export { IconLineSkipForward }