/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledVenmoProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledVenmoRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTQgMEMxLjc5MDg2IDAgMCAxLjc5MDg2IDAgNFYyMEMwIDIyLjIwOTEgMS43OTA4NiAyNCA0IDI0SDIwQzIyLjIwOTEgMjQgMjQgMjIuMjA5MSAyNCAyMFY0QzI0IDEuNzkwODYgMjIuMjA5MSAwIDIwIDBINFpNMTggOC4zOTk3M0MxOCA3LjQ2MjQyIDE3LjgwNzggNi43MjA0IDE3LjM4MTMgNkwxMy42OTMzIDYuNzYzNjNDMTMuOTI3NyA3LjI2NTg4IDE0LjA3NzcgNy44NzU4NyAxNC4wNzc3IDguNzcxNDFDMTQuMDc3NyAxMC40MDc1IDEyLjk0NjkgMTIuODA3MiAxMi4wMzA1IDE0LjMzNDNMMTEuMDQ5OCA2LjI2MTI2TDcgNi42NTQ1NUw4Ljg1NDk0IDE4SDEzLjQ4MDFDMTUuNTA1IDE1LjI3MjkgMTggMTEuMzg5MyAxOCA4LjM5OTczWiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledVenmo = React.forwardRef<IconFilledVenmoRef, IconFilledVenmoProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-venmo" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M4 0C1.79086 0 0 1.79086 0 4V20C0 22.2091 1.79086 24 4 24H20C22.2091 24 24 22.2091 24 20V4C24 1.79086 22.2091 0 20 0H4ZM18 8.39973C18 7.46242 17.8078 6.7204 17.3813 6L13.6933 6.76363C13.9277 7.26588 14.0777 7.87587 14.0777 8.77141C14.0777 10.4075 12.9469 12.8072 12.0305 14.3343L11.0498 6.26126L7 6.65455L8.85494 18H13.4801C15.505 15.2729 18 11.3893 18 8.39973Z" fill="currentColor" /></IconBase>)
IconFilledVenmo.displayName = definePortfolioDisplayName("IconFilledVenmo")

export { IconFilledVenmo }