/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineRepeatProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineRepeatRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNSA1SDE3QzIwLjMxMzcgNSAyMyA3LjY4NjI5IDIzIDExVjEyTTUgNUw5IDFNNSA1TDkgOU0xOSAxOUw3IDE5QzMuNjg2MjkgMTkgMSAxNi4zMTM3IDEgMTNWMTJNMTkgMTlMMTUgMjNNMTkgMTlMMTUgMTUiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineRepeat = React.forwardRef<IconLineRepeatRef, IconLineRepeatProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-repeat" ref={ref}><path d="M5 5H17C20.3137 5 23 7.68629 23 11V12M5 5L9 1M5 5L9 9M19 19L7 19C3.68629 19 1 16.3137 1 13V12M19 19L15 23M19 19L15 15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineRepeat.displayName = definePortfolioDisplayName("IconLineRepeat")

export { IconLineRepeat }