/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledFilledCloseProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledFilledCloseRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTEyIDIzQzE4LjA3NTEgMjMgMjMgMTguMDc1MSAyMyAxMkMyMyA1LjkyNDg3IDE4LjA3NTEgMSAxMiAxQzUuOTI0ODcgMSAxIDUuOTI0ODcgMSAxMkMxIDE4LjA3NTEgNS45MjQ4NyAyMyAxMiAyM1pNOC4yOTI4OSAxNS43MDcxQzcuOTAyMzcgMTUuMzE2NiA3LjkwMjM3IDE0LjY4MzQgOC4yOTI4OSAxNC4yOTI5TDEwLjU4NTggMTJMOC4yOTI4OSA5LjcwNzExQzcuOTAyMzcgOS4zMTY1OCA3LjkwMjM3IDguNjgzNDIgOC4yOTI4OSA4LjI5Mjg5QzguNjgzNDIgNy45MDIzNyA5LjMxNjU4IDcuOTAyMzcgOS43MDcxMSA4LjI5Mjg5TDEyIDEwLjU4NThMMTQuMjkyOSA4LjI5Mjg5QzE0LjY4MzQgNy45MDIzNyAxNS4zMTY2IDcuOTAyMzcgMTUuNzA3MSA4LjI5Mjg5QzE2LjA5NzYgOC42ODM0MiAxNi4wOTc2IDkuMzE2NTggMTUuNzA3MSA5LjcwNzExTDEzLjQxNDIgMTJMMTUuNzA3MSAxNC4yOTI5QzE2LjA5NzYgMTQuNjgzNCAxNi4wOTc2IDE1LjMxNjYgMTUuNzA3MSAxNS43MDcxQzE1LjMxNjYgMTYuMDk3NiAxNC42ODM0IDE2LjA5NzYgMTQuMjkyOSAxNS43MDcxTDEyIDEzLjQxNDJMOS43MDcxMSAxNS43MDcxQzkuMzE2NTggMTYuMDk3NiA4LjY4MzQyIDE2LjA5NzYgOC4yOTI4OSAxNS43MDcxWiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledFilledClose = React.forwardRef<IconFilledFilledCloseRef, IconFilledFilledCloseProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-filled-close" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M12 23C18.0751 23 23 18.0751 23 12C23 5.92487 18.0751 1 12 1C5.92487 1 1 5.92487 1 12C1 18.0751 5.92487 23 12 23ZM8.29289 15.7071C7.90237 15.3166 7.90237 14.6834 8.29289 14.2929L10.5858 12L8.29289 9.70711C7.90237 9.31658 7.90237 8.68342 8.29289 8.29289C8.68342 7.90237 9.31658 7.90237 9.70711 8.29289L12 10.5858L14.2929 8.29289C14.6834 7.90237 15.3166 7.90237 15.7071 8.29289C16.0976 8.68342 16.0976 9.31658 15.7071 9.70711L13.4142 12L15.7071 14.2929C16.0976 14.6834 16.0976 15.3166 15.7071 15.7071C15.3166 16.0976 14.6834 16.0976 14.2929 15.7071L12 13.4142L9.70711 15.7071C9.31658 16.0976 8.68342 16.0976 8.29289 15.7071Z" fill="currentColor" /></IconBase>)
IconFilledFilledClose.displayName = definePortfolioDisplayName("IconFilledFilledClose")

export { IconFilledFilledClose }