/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBorderAllProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBorderAllRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNCAyM0gyME00IDFIMjBNMSA0VjIwTTIzIDRWMjAiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineBorderAll = React.forwardRef<IconLineBorderAllRef, IconLineBorderAllProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-border-all" ref={ref}><path d="M4 23H20M4 1H20M1 4V20M23 4V20" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineBorderAll.displayName = definePortfolioDisplayName("IconLineBorderAll")

export { IconLineBorderAll }