/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineTentProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineTentRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjUiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNSAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMi4yNSAyMEgyMi4yNU0yLjI1IDIwTDEyLjI1IDJNMi4yNSAyMEwwLjc1IDE4TTIyLjI1IDIwTDEyLjI1IDJNMjIuMjUgMjBMMjMuNzUgMThNMTIuMjUgMlYyME0xMi4yNSAyMFY5TDE4LjI1IDIwSDEyLjI1WiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineTent = React.forwardRef<IconLineTentRef, IconLineTentProps>((props, ref) => <IconBase {...props} width="25" height="24" viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-tent" ref={ref}><path d="M2.25 20H22.25M2.25 20L12.25 2M2.25 20L0.75 18M22.25 20L12.25 2M22.25 20L23.75 18M12.25 2V20M12.25 20V9L18.25 20H12.25Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineTent.displayName = definePortfolioDisplayName("IconLineTent")

export { IconLineTent }