/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledFacebookProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledFacebookRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjQgMTIuMDczM0MyNCA1LjQwNTQxIDE4LjYyNzQgMCAxMiAwQzUuMzcyNTggMCAwIDUuNDA1NDEgMCAxMi4wNzMzQzAgMTguMDk5NCA0LjM4ODIgMjMuMDk0MyAxMC4xMjUgMjRWMTUuNTYzM0g3LjA3ODEyVjEyLjA3MzNIMTAuMTI1VjkuNDEzNDNDMTAuMTI1IDYuMzg3NTUgMTEuOTE2NiA0LjcxNjE1IDE0LjY1NzYgNC43MTYxNUMxNS45NzAxIDQuNzE2MTUgMTcuMzQzOCA0Ljk1MTk1IDE3LjM0MzggNC45NTE5NVY3LjkyMzEzSDE1LjgzMDZDMTQuMzQgNy45MjMxMyAxMy44NzUgOC44NTM4NiAxMy44NzUgOS44MDk1OFYxMi4wNzMzSDE3LjIwMzFMMTYuNjcxMSAxNS41NjMzSDEzLjg3NVYyNEMxOS42MTE4IDIzLjA5NDMgMjQgMTguMDk5NCAyNCAxMi4wNzMzWiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledFacebook = React.forwardRef<IconFilledFacebookRef, IconFilledFacebookProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-facebook-" ref={ref}><path d="M24 12.0733C24 5.40541 18.6274 0 12 0C5.37258 0 0 5.40541 0 12.0733C0 18.0994 4.3882 23.0943 10.125 24V15.5633H7.07812V12.0733H10.125V9.41343C10.125 6.38755 11.9166 4.71615 14.6576 4.71615C15.9701 4.71615 17.3438 4.95195 17.3438 4.95195V7.92313H15.8306C14.34 7.92313 13.875 8.85386 13.875 9.80958V12.0733H17.2031L16.6711 15.5633H13.875V24C19.6118 23.0943 24 18.0994 24 12.0733Z" fill="currentColor" /></IconBase>)
IconFilledFacebook.displayName = definePortfolioDisplayName("IconFilledFacebook")

export { IconFilledFacebook }