/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBatteryProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBatteryRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuNDI4NiA5LjQyODU3SDIxLjgyMTRDMjIuNDcyIDkuNDI4NTcgMjMgMTAuMDA0NiAyMyAxMC43MTQzVjEzLjI4NTdDMjMgMTMuOTk1NCAyMi40NzIgMTQuNTcxNCAyMS44MjE0IDE0LjU3MTRIMjEuNDI4Nk0zLjM1NzE0IDE4SDE5LjA3MTRDMTkuNjk2NiAxOCAyMC4yOTYxIDE3LjcyOTEgMjAuNzM4MiAxNy4yNDY4QzIxLjE4MDIgMTYuNzY0NiAyMS40Mjg2IDE2LjExMDYgMjEuNDI4NiAxNS40Mjg2VjguNTcxNDNDMjEuNDI4NiA3Ljg4OTQ0IDIxLjE4MDIgNy4yMzUzOSAyMC43MzgyIDYuNzUzMTVDMjAuMjk2MSA2LjI3MDkyIDE5LjY5NjYgNiAxOS4wNzE0IDZIMy4zNTcxNEMyLjczMTk5IDYgMi4xMzI0NCA2LjI3MDkyIDEuNjkwMzkgNi43NTMxNUMxLjI0ODM0IDcuMjM1MzkgMSA3Ljg4OTQ0IDEgOC41NzE0M1YxNS40Mjg2QzEgMTYuMTEwNiAxLjI0ODM0IDE2Ljc2NDYgMS42OTAzOSAxNy4yNDY4QzIuMTMyNDQgMTcuNzI5MSAyLjczMTk5IDE4IDMuMzU3MTQgMThaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineBattery = React.forwardRef<IconLineBatteryRef, IconLineBatteryProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-battery" ref={ref}><path d="M21.4286 9.42857H21.8214C22.472 9.42857 23 10.0046 23 10.7143V13.2857C23 13.9954 22.472 14.5714 21.8214 14.5714H21.4286M3.35714 18H19.0714C19.6966 18 20.2961 17.7291 20.7382 17.2468C21.1802 16.7646 21.4286 16.1106 21.4286 15.4286V8.57143C21.4286 7.88944 21.1802 7.23539 20.7382 6.75315C20.2961 6.27092 19.6966 6 19.0714 6H3.35714C2.73199 6 2.13244 6.27092 1.69039 6.75315C1.24834 7.23539 1 7.88944 1 8.57143V15.4286C1 16.1106 1.24834 16.7646 1.69039 17.2468C2.13244 17.7291 2.73199 18 3.35714 18Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineBattery.displayName = definePortfolioDisplayName("IconLineBattery")

export { IconLineBattery }