/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLinePersonProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLinePersonRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTguOTUwNiAxNy4zODAyQzE3LjM3ODMgMTYuNTY2OSAxNC43ODQ5IDE1LjUgMTIgMTUuNUM5LjIxNTEzIDE1LjUgNi42MjE3NSAxNi41NjY5IDUuMDQ5NDIgMTcuMzgwMkM0LjAzNDMxIDE3LjkwNTIgMy40MjI5NSAxOC45MzUxIDMuMjg4MyAyMC4wN0wzIDIyLjVIMjFMMjAuNzExNyAyMC4wN0MyMC41NzcgMTguOTM1MSAxOS45NjU3IDE3LjkwNTIgMTguOTUwNiAxNy4zODAyWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjxwYXRoIGQ9Ik0xMiAxMUMxNC40ODUzIDExIDE2LjUgOC45ODUyOCAxNi41IDYuNUMxNi41IDQuMDE0NzIgMTQuNDg1MyAyIDEyIDJDOS41MTQ3MiAyIDcuNSA0LjAxNDcyIDcuNSA2LjVDNy41IDguOTg1MjggOS41MTQ3MiAxMSAxMiAxMVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLinePerson = React.forwardRef<IconLinePersonRef, IconLinePersonProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-person" ref={ref}><path d="M18.9506 17.3802C17.3783 16.5669 14.7849 15.5 12 15.5C9.21513 15.5 6.62175 16.5669 5.04942 17.3802C4.03431 17.9052 3.42295 18.9351 3.2883 20.07L3 22.5H21L20.7117 20.07C20.577 18.9351 19.9657 17.9052 18.9506 17.3802Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /><path d="M12 11C14.4853 11 16.5 8.98528 16.5 6.5C16.5 4.01472 14.4853 2 12 2C9.51472 2 7.5 4.01472 7.5 6.5C7.5 8.98528 9.51472 11 12 11Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLinePerson.displayName = definePortfolioDisplayName("IconLinePerson")

export { IconLinePerson }