/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledGooglePlaystoreProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledGooglePlaystoreRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTcuNzEwMyA4LjQ2NDJMMTMuODEzMiAxMi4yNUwxNy4zODcyIDE1LjcyMTlMMjEuNTY3MiAxMy4zNDg4QzIyLjU2NSAxMi43ODExIDIyLjgwMTggMTEuOTQwMSAyMi4yNzc0IDExLjI0NjFDMjIuMjY1NyAxMS4yMjg2IDIyLjI1MzYgMTEuMjExMiAyMi4yNDExIDExLjE5NDFDMjIuMDY5MSAxMC45NTc0IDIxLjgzNjggMTAuNzcxMSAyMS41Njg0IDEwLjY1NDZMMjEuNTY3MiAxMC42NTM5TDE3LjcxMDMgOC40NjQyWiIgZmlsbD0iIzFFMjAyOCIgLz48cGF0aCBkPSJNMTYuNDc4IDE2LjIzMjlMMTMuMDk1NiAxMi45NDcxTDEuODMzNjIgMjMuODg3M0MyLjAxODAzIDIzLjk2MTMgMi4yMTYgMjQgMi40MTcxNyAyNEMyLjc1NDUxIDI0IDMuMDgyODMgMjMuODkxMSAzLjM1MzMyIDIzLjY4OTZMMTYuNDc4IDE2LjIzMjlaIiBmaWxsPSIjMUUyMDI4IiAvPjxwYXRoIGQ9Ik0xLjE0OTI2IDIzLjE1NzlMMTIuMzc4IDEyLjI1TDEuMDMyMjkgMS4yMjg0NEMxLjAwNDI1IDEuMzc3NDUgMC45OTQyIDEuNTMwNDQgMS4wMDMyMSAxLjY4NDE4VjIyLjE4NTdDMC45OTk5NzggMjIuMjQzNiAwLjk5OTQwNyAyMi4zMDE1IDEuMDAxNDIgMjIuMzU4OUMwLjk5MjA1NyAyMi42MzQ5IDEuMDQzMzUgMjIuOTA3MyAxLjE0OTI2IDIzLjE1NzlaIiBmaWxsPSIjMUUyMDI4IiAvPjxwYXRoIGQ9Ik0xLjUwOTIzIDAuMjk3NTk5TDEzLjA5NTYgMTEuNTUyOUwxNi44MDQ1IDcuOTVMMy4zNTMzOCAwLjMxMzMwMUMzLjA3NTcyIDAuMDk5ODI4OSAyLjczMjU2IC0wLjAxMDYyNDMgMi4zODI1IDAuMDAwODA1OTAzTDIuMzU2MDcgMC4wMDE5MDA0MUMyLjAyNDg5IC0wLjAwNjExNTc2IDEuNzM0ODkgMC4wOTY2NjkzIDEuNTA5MjMgMC4yOTc1OTlaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledGooglePlaystore = React.forwardRef<IconFilledGooglePlaystoreRef, IconFilledGooglePlaystoreProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-google-playstore" ref={ref}><path d="M17.7103 8.4642L13.8132 12.25L17.3872 15.7219L21.5672 13.3488C22.565 12.7811 22.8018 11.9401 22.2774 11.2461C22.2657 11.2286 22.2536 11.2112 22.2411 11.1941C22.0691 10.9574 21.8368 10.7711 21.5684 10.6546L21.5672 10.6539L17.7103 8.4642Z" fill="currentColor" /><path d="M16.478 16.2329L13.0956 12.9471L1.83362 23.8873C2.01803 23.9613 2.216 24 2.41717 24C2.75451 24 3.08283 23.8911 3.35332 23.6896L16.478 16.2329Z" fill="currentColor" /><path d="M1.14926 23.1579L12.378 12.25L1.03229 1.22844C1.00425 1.37745 0.9942 1.53044 1.00321 1.68418V22.1857C0.999978 22.2436 0.999407 22.3015 1.00142 22.3589C0.992057 22.6349 1.04335 22.9073 1.14926 23.1579Z" fill="currentColor" /><path d="M1.50923 0.297599L13.0956 11.5529L16.8045 7.95L3.35338 0.313301C3.07572 0.0998289 2.73256 -0.0106243 2.3825 0.000805903L2.35607 0.00190041C2.02489 -0.00611576 1.73489 0.0966693 1.50923 0.297599Z" fill="currentColor" /></IconBase>)
IconFilledGooglePlaystore.displayName = definePortfolioDisplayName("IconFilledGooglePlaystore")

export { IconFilledGooglePlaystore }