/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineAlignCenterProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineAlignCenterRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjYiIGhlaWdodD0iMjYiIHZpZXdCb3g9IjAgMCAyNiAyNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMC43NjQ3MDYgMC43NjQ3MDZIMjUuMjM1M000LjEwMTYgOC45MjE1N0gyMS44OTg0TTAuNzY0NzA2IDE3LjA3ODRIMjUuMjM1M000LjEwMTYgMjUuMjM1M0gyMS44OTg0IiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineAlignCenter = React.forwardRef<IconLineAlignCenterRef, IconLineAlignCenterProps>((props, ref) => <IconBase {...props} width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-align-center" ref={ref}><path d="M0.764706 0.764706H25.2353M4.1016 8.92157H21.8984M0.764706 17.0784H25.2353M4.1016 25.2353H21.8984" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineAlignCenter.displayName = definePortfolioDisplayName("IconLineAlignCenter")

export { IconLineAlignCenter }