/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLinePlaylistProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLinePlaylistRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjYiIGhlaWdodD0iMjYiIHZpZXdCb3g9IjAgMCAyNiAyNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTguNTc1MiA4LjI5NDEySDI1LjIzNTNNMTMuMDI1MiAxNi40NTFIMjUuMjM1M00wLjgxNTE3IDI1LjIzNTNIMjUuMjM1M00wLjc2NDcwNiAxLjk4MTRDMC43NjQ3MDYgMS4wNDYxOCAxLjYwNTYyIDAuNDYxNjczIDIuMjc4MzUgMC45MjkyODJMMTEuMzYwMiA3LjI0MkMxMi4wMzI5IDcuNzA5NjEgMTIuMDMyOSA4Ljg3ODYzIDExLjM2MDIgOS4zNDYyNEwyLjI3ODM1IDE1LjY1OUMxLjYwNTYyIDE2LjEyNjYgMC43NjQ3MDYgMTUuNTQyMSAwLjc2NDcwNiAxNC42MDY4TDAuNzY0NzA2IDEuOTgxNFoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLinePlaylist = React.forwardRef<IconLinePlaylistRef, IconLinePlaylistProps>((props, ref) => <IconBase {...props} width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-playlist" ref={ref}><path d="M18.5752 8.29412H25.2353M13.0252 16.451H25.2353M0.81517 25.2353H25.2353M0.764706 1.9814C0.764706 1.04618 1.60562 0.461673 2.27835 0.929282L11.3602 7.242C12.0329 7.70961 12.0329 8.87863 11.3602 9.34624L2.27835 15.659C1.60562 16.1266 0.764706 15.5421 0.764706 14.6068L0.764706 1.9814Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLinePlaylist.displayName = definePortfolioDisplayName("IconLinePlaylist")

export { IconLinePlaylist }