/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCryptoMoneroXmrProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCryptoMoneroXmrRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTExLjk5OTMgMjMuOTM2QzE4LjU5MTcgMjMuOTM2IDIzLjkzNTkgMTguNTkxNyAyMy45MzU5IDExLjk5OTJDMjMuOTM1OSA1LjQwNjc0IDE4LjU5MTcgMC4wNjI1IDExLjk5OTMgMC4wNjI1QzUuNDA2NzQgMC4wNjI1IDAuMDYyNSA1LjQwNjc0IDAuMDYyNSAxMS45OTkyQzAuMDYyNSAxOC41OTE3IDUuNDA2NzQgMjMuOTM2IDExLjk5OTMgMjMuOTM2Wk02LjYyODU3IDE0LjU1NTNWNy43MTAyN0wxMi4wMDExIDEzLjAyNTVMMTcuMzczNSA3LjcxMDI3VjE0LjU1NTNIMTkuODYzMkMyMC4xNTE1IDEzLjcyNTYgMjAuMzA4NyAxMi44NDQxIDIwLjMwODcgMTEuOTEwNkMyMC4zMDg3IDcuMzczMjEgMTYuNTg3MyAzLjY5MTQxIDEyLjAwMTEgMy42OTE0MUM3LjQxNDc5IDMuNjkxNDEgMy42OTMzNiA3LjM3MzIxIDMuNjkzMzYgMTEuOTEwNkMzLjY5MzM2IDEyLjg0NDEgMy44NTA2IDEzLjcyNTYgNC4xMzg4OCAxNC41NTUzSDYuNjI4NTdaTTE1LjY0NzIgMTYuNDUwNVYxMS45OTlMMTIuMDAxMyAxNS41OTY0TDguMzU1MzIgMTEuOTk5VjE2LjQ1MDVINC45NzE2OEM2LjQ0MDU1IDE4Ljc1MzkgOS4wMzczIDIwLjMwNjcgMTIuMDAxMyAyMC4zMDY3QzE0Ljk2NTIgMjAuMzA2NyAxNy41NjIgMTguNzc5OCAxOS4wMzA5IDE2LjQ1MDVIMTUuNjQ3MloiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFilledCryptoMoneroXmr = React.forwardRef<IconFilledCryptoMoneroXmrRef, IconFilledCryptoMoneroXmrProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-crypto-monero-xmr" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M11.9993 23.936C18.5917 23.936 23.9359 18.5917 23.9359 11.9992C23.9359 5.40674 18.5917 0.0625 11.9993 0.0625C5.40674 0.0625 0.0625 5.40674 0.0625 11.9992C0.0625 18.5917 5.40674 23.936 11.9993 23.936ZM6.62857 14.5553V7.71027L12.0011 13.0255L17.3735 7.71027V14.5553H19.8632C20.1515 13.7256 20.3087 12.8441 20.3087 11.9106C20.3087 7.37321 16.5873 3.69141 12.0011 3.69141C7.41479 3.69141 3.69336 7.37321 3.69336 11.9106C3.69336 12.8441 3.8506 13.7256 4.13888 14.5553H6.62857ZM15.6472 16.4505V11.999L12.0013 15.5964L8.35532 11.999V16.4505H4.97168C6.44055 18.7539 9.0373 20.3067 12.0013 20.3067C14.9652 20.3067 17.562 18.7798 19.0309 16.4505H15.6472Z" fill="currentColor" /></IconBase>)
IconFilledCryptoMoneroXmr.displayName = definePortfolioDisplayName("IconFilledCryptoMoneroXmr")

export { IconFilledCryptoMoneroXmr }