/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWeatherStarsProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWeatherStarsRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjUiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNSAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMyAxVjVNNSAzSDFNNCAxOVYyM002IDIxSDJNOS41MTgxNyAxMC44NDQ2TDYuODk0MjcgMTEuNTE1NkM2LjM5Mjc4IDExLjY0MzggNi4zOTI3NyAxMi4zNTYyIDYuODk0MjcgMTIuNDg0NEw5LjUxODE2IDEzLjE1NTRDMTEuNjQyNSAxMy42OTg3IDEzLjMwMTMgMTUuMzU3NSAxMy44NDQ2IDE3LjQ4MThMMTQuNTE1NiAyMC4xMDU3QzE0LjY0MzggMjAuNjA3MiAxNS4zNTYyIDIwLjYwNzIgMTUuNDg0NCAyMC4xMDU3TDE2LjE1NTQgMTcuNDgxOEMxNi42OTg3IDE1LjM1NzUgMTguMzU3NSAxMy42OTg3IDIwLjQ4MTggMTMuMTU1NEwyMy4xMDU3IDEyLjQ4NDRDMjMuNjA3MiAxMi4zNTYyIDIzLjYwNzIgMTEuNjQzOCAyMy4xMDU3IDExLjUxNTZMMjAuNDgxOCAxMC44NDQ2QzE4LjM1NzUgMTAuMzAxMyAxNi42OTg3IDguNjQyNTIgMTYuMTU1NCA2LjUxODE3TDE1LjQ4NDQgMy44OTQyN0MxNS4zNTYyIDMuMzkyNzggMTQuNjQzOCAzLjM5Mjc3IDE0LjUxNTYgMy44OTQyN0wxMy44NDQ2IDYuNTE4MTZDMTMuMzAxMyA4LjY0MjUyIDExLjY0MjUgMTAuMzAxMyA5LjUxODE3IDEwLjg0NDZaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineWeatherStars = React.forwardRef<IconLineWeatherStarsRef, IconLineWeatherStarsProps>((props, ref) => <IconBase {...props} width="25" height="24" viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-weather-stars" ref={ref}><path d="M3 1V5M5 3H1M4 19V23M6 21H2M9.51817 10.8446L6.89427 11.5156C6.39278 11.6438 6.39277 12.3562 6.89427 12.4844L9.51816 13.1554C11.6425 13.6987 13.3013 15.3575 13.8446 17.4818L14.5156 20.1057C14.6438 20.6072 15.3562 20.6072 15.4844 20.1057L16.1554 17.4818C16.6987 15.3575 18.3575 13.6987 20.4818 13.1554L23.1057 12.4844C23.6072 12.3562 23.6072 11.6438 23.1057 11.5156L20.4818 10.8446C18.3575 10.3013 16.6987 8.64252 16.1554 6.51817L15.4844 3.89427C15.3562 3.39278 14.6438 3.39277 14.5156 3.89427L13.8446 6.51816C13.3013 8.64252 11.6425 10.3013 9.51817 10.8446Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineWeatherStars.displayName = definePortfolioDisplayName("IconLineWeatherStars")

export { IconLineWeatherStars }