/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCryptoBasicAttentionTokenBatProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCryptoBasicAttentionTokenBatRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTI0IDEyQzI0IDE4LjYyNzQgMTguNjI3NCAyNCAxMiAyNEM1LjM3MjU4IDI0IDAgMTguNjI3NCAwIDEyQzAgNS4zNzI1OCA1LjM3MjU4IDAgMTIgMEMxOC42Mjc0IDAgMjQgNS4zNzI1OCAyNCAxMlpNMTEuOTY1NyA5LjgwNTk0TDExLjk2NDIgNC41TDUgMTYuNDgzOUw5LjQ5ODkzIDEzLjkxNDlMMTEuOTY1NyA5LjgwNTk0Wk0xNS4wMTEgMTMuOTU4OEwxMi40NjcyIDkuNzQwNjFMMTIuNDY4NyA0LjVMMTkuNDMyOSAxNi40ODM5TDE1LjAxMSAxMy45NTg4Wk0xNC4yNTg1IDE0LjE0NjlIMTAuMjMwNUw1LjIxNjQ2IDE2Ljk5NDVMMTkuMjE2NCAxNi45NzhMMTQuMjU4NSAxNC4xNDY5WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledCryptoBasicAttentionTokenBat = React.forwardRef<IconFilledCryptoBasicAttentionTokenBatRef, IconFilledCryptoBasicAttentionTokenBatProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-crypto-basic-attention-token-bat" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0C18.6274 0 24 5.37258 24 12ZM11.9657 9.80594L11.9642 4.5L5 16.4839L9.49893 13.9149L11.9657 9.80594ZM15.011 13.9588L12.4672 9.74061L12.4687 4.5L19.4329 16.4839L15.011 13.9588ZM14.2585 14.1469H10.2305L5.21646 16.9945L19.2164 16.978L14.2585 14.1469Z" fill="currentColor" /></IconBase>)
IconFilledCryptoBasicAttentionTokenBat.displayName = definePortfolioDisplayName("IconFilledCryptoBasicAttentionTokenBat")

export { IconFilledCryptoBasicAttentionTokenBat }