/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledNetflixProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledNetflixRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTUgMFYxMkwxMC41IDBINlYyNEgxMC41VjEyTDE1IDI0SDE5LjVWMEgxNVoiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFilledNetflix = React.forwardRef<IconFilledNetflixRef, IconFilledNetflixProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-netflix" ref={ref}><path d="M15 0V12L10.5 0H6V24H10.5V12L15 24H19.5V0H15Z" fill="currentColor" /></IconBase>)
IconFilledNetflix.displayName = definePortfolioDisplayName("IconFilledNetflix")

export { IconFilledNetflix }