/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineRewindProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineRewindRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNSA0TDUuMDAyNjIgMTJNNSAyMEw1LjAwMjYyIDEyTTUuMDAyNjIgMTJDNS4wMDIzOSAxMS41MDMyIDUuMjQ0MyAxMS4wMDYzIDUuNzI4MzUgMTAuNzE0NkwxNi4yNTU3IDQuMzY5OTVDMTcuMjU1NSAzLjc2NzQzIDE4LjUzIDQuNDg3NDEgMTguNTMgNS42NTQ2N1YxOC4zNDM5QzE4LjUzIDE5LjUxMTIgMTcuMjU1NSAyMC4yMzEyIDE2LjI1NTcgMTkuNjI4Nkw1LjcyODM1IDEzLjI4NEM1LjI0NDc2IDEyLjk5MjYgNS4wMDI4NSAxMi40OTYzIDUuMDAyNjIgMTJaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIC8+PC9zdmc+) */
const IconLineRewind = React.forwardRef<IconLineRewindRef, IconLineRewindProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-rewind" ref={ref}><path d="M5 4L5.00262 12M5 20L5.00262 12M5.00262 12C5.00239 11.5032 5.2443 11.0063 5.72835 10.7146L16.2557 4.36995C17.2555 3.76743 18.53 4.48741 18.53 5.65467V18.3439C18.53 19.5112 17.2555 20.2312 16.2557 19.6286L5.72835 13.284C5.24476 12.9926 5.00285 12.4963 5.00262 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineRewind.displayName = definePortfolioDisplayName("IconLineRewind")

export { IconLineRewind }