/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWifiProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWifiRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIgMjBWMTkuOTlNNy45NDc2IDE1LjgzMjFDOS4wMjI0MiAxNC43MjY4IDEwLjQ4MDEgMTQuMTA1OSAxMiAxNC4xMDU5QzEzLjUxOTkgMTQuMTA1OSAxNC45Nzc2IDE0LjcyNjggMTYuMDUyNCAxNS44MzIxTTQuNDczOCAxMi4yNTkyQzguNjI5OTEgNy45ODM1MSAxNS4zNjkgNy45ODM1MSAxOS41MjYyIDEyLjI1OTJNMSA4LjY4NjRDNy4wNzUzMyAyLjQzNzg3IDE2LjkyNDcgMi40Mzc4NyAyMyA4LjY4NjQiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineWifi = React.forwardRef<IconLineWifiRef, IconLineWifiProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-wifi" ref={ref}><path d="M12 20V19.99M7.9476 15.8321C9.02242 14.7268 10.4801 14.1059 12 14.1059C13.5199 14.1059 14.9776 14.7268 16.0524 15.8321M4.4738 12.2592C8.62991 7.98351 15.369 7.98351 19.5262 12.2592M1 8.6864C7.07533 2.43787 16.9247 2.43787 23 8.6864" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineWifi.displayName = definePortfolioDisplayName("IconLineWifi")

export { IconLineWifi }