/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineFireProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineFireRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNCAyM0wxOSAxOE0xOSAyM0w0IDE4TTE4IDEyQzE3LjY0NjUgMTMuNDE0MSAxNS44ODk4IDE1Ljc1MDggMTMuNTk5OCAxNi42NDA3QzEzLjYyNDQgMTUuNDI2NyAxMy4wNzE1IDE0LjgxMjggMTIuNTc5OCAxNC4yNjY4QzEyLjM1MjQgMTQuMDE0MiAxMi4xMzggMTMuNzc2MiAxMiAxMy41QzExLjUgMTIuNSAxMS4zODA5IDExLjQxNjcgMTEuNjE5IDExQzExLjYxOSAxMSA4Ljk5OTk1IDEzIDguOTk5OTUgMTUuNUM4Ljk5OTk1IDE1Ljg2OTcgOS4wMjEyNyAxNi4yMTc3IDkuMDYyNTMgMTYuNTQyM0M3LjI1MTU2IDE1Ljg1MjcgNiAxNC4zNzAxIDYgMTJDNiA4Ljk4MTI0IDcuMjkyMDUgNy42MjM2OSA4LjY3MzUzIDYuMTcyMTdDOC44NjEwNyA1Ljk3NTEyIDkuMDUwMjYgNS43NzYzNCA5LjIzODEgNS41NzE0M0MxMC40OTUyIDQuMiAxMC43NjE5IDEuOTUyMzggMTAuMjM4MSAxQzEwLjM1MjUgMS4wODMyNCAxMC41NDk4IDEuMjAxMDMgMTAuNzk2OCAxLjM0ODYxQzExLjY4MDUgMS44NzY0NiAxMy4yMDIyIDIuNzg1MzcgMTMuODU3MSAzLjg1NzE0QzE0LjMwMTggNC41ODQ3OSAxNC4wMjM3IDUuMzc5NDEgMTMuNzUyMSA2LjE1NTcyQzEzLjM4MzcgNy4yMDgzMyAxMy4wMjcxIDguMjI3MjkgMTQuNSA5QzE1Ljk5NzcgOS43ODU3MSAxNy40Mjg2IDcgMTcuNDI4NiA3QzE3LjQyODYgNyAxOC41IDEwIDE4IDEyWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineFire = React.forwardRef<IconLineFireRef, IconLineFireProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-fire" ref={ref}><path d="M4 23L19 18M19 23L4 18M18 12C17.6465 13.4141 15.8898 15.7508 13.5998 16.6407C13.6244 15.4267 13.0715 14.8128 12.5798 14.2668C12.3524 14.0142 12.138 13.7762 12 13.5C11.5 12.5 11.3809 11.4167 11.619 11C11.619 11 8.99995 13 8.99995 15.5C8.99995 15.8697 9.02127 16.2177 9.06253 16.5423C7.25156 15.8527 6 14.3701 6 12C6 8.98124 7.29205 7.62369 8.67353 6.17217C8.86107 5.97512 9.05026 5.77634 9.2381 5.57143C10.4952 4.2 10.7619 1.95238 10.2381 1C10.3525 1.08324 10.5498 1.20103 10.7968 1.34861C11.6805 1.87646 13.2022 2.78537 13.8571 3.85714C14.3018 4.58479 14.0237 5.37941 13.7521 6.15572C13.3837 7.20833 13.0271 8.22729 14.5 9C15.9977 9.78571 17.4286 7 17.4286 7C17.4286 7 18.5 10 18 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineFire.displayName = definePortfolioDisplayName("IconLineFire")

export { IconLineFire }