/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineLogOutCircleProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineLogOutCircleRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTYuMzY0IDE4LjM2NEMxMi44NDkyIDIxLjg3ODcgNy4xNTA3NiAyMS44Nzg3IDMuNjM2MDQgMTguMzY0QzAuMTIxMzIgMTQuODQ5MiAwLjEyMTMyIDkuMTUwNzYgMy42MzYwNCA1LjYzNjA0QzcuMTUwNzYgMi4xMjEzMiAxMi44NDkyIDIuMTIxMzIgMTYuMzY0IDUuNjM2MDRNMjAgOS4wMDAyNEwyMi42NjY3IDEyLjAwMDJMMjAgMTUuMDAwMk0yMi41IDEyLjAwMDJIMTAiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineLogOutCircle = React.forwardRef<IconLineLogOutCircleRef, IconLineLogOutCircleProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-log-out-circle" ref={ref}><path d="M16.364 18.364C12.8492 21.8787 7.15076 21.8787 3.63604 18.364C0.12132 14.8492 0.12132 9.15076 3.63604 5.63604C7.15076 2.12132 12.8492 2.12132 16.364 5.63604M20 9.00024L22.6667 12.0002L20 15.0002M22.5 12.0002H10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineLogOutCircle.displayName = definePortfolioDisplayName("IconLineLogOutCircle")

export { IconLineLogOutCircle }