/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWorldNetProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWorldNetRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjMgMTJDMjMgMTguMDc1MSAxOC4wNzUxIDIzIDEyIDIzTTIzIDEyQzIzIDUuOTI0ODcgMTguMDc1MSAxIDEyIDFNMjMgMTJIMU0xMiAyM0M1LjkyNDg3IDIzIDEgMTguMDc1MSAxIDEyTTEyIDIzQzEyIDIzIDggMjAuOCA4IDEyQzggMy4yIDEyIDEgMTIgMU0xMiAyM0MxMiAyMyAxNiAyMC44IDE2IDEyQzE2IDMuMiAxMiAxIDEyIDFNMSAxMkMxIDUuOTI0ODcgNS45MjQ4NyAxIDEyIDEiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineWorldNet = React.forwardRef<IconLineWorldNetRef, IconLineWorldNetProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-world-net" ref={ref}><path d="M23 12C23 18.0751 18.0751 23 12 23M23 12C23 5.92487 18.0751 1 12 1M23 12H1M12 23C5.92487 23 1 18.0751 1 12M12 23C12 23 8 20.8 8 12C8 3.2 12 1 12 1M12 23C12 23 16 20.8 16 12C16 3.2 12 1 12 1M1 12C1 5.92487 5.92487 1 12 1" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineWorldNet.displayName = definePortfolioDisplayName("IconLineWorldNet")

export { IconLineWorldNet }