/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineQrCodeProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineQrCodeRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTQgMUgxMVYxMUgxVjE0TTI0IDE5SDExVjIzSDI0TTEwIDE1SDE5VjExSDIzVjE2TTEgMUg3VjdIMVYxWk0xIDE3SDdWMjNIMVYxN1pNMTcgMUgyM1Y3SDE3VjFaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineQrCode = React.forwardRef<IconLineQrCodeRef, IconLineQrCodeProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-qr-code" ref={ref}><path d="M14 1H11V11H1V14M24 19H11V23H24M10 15H19V11H23V16M1 1H7V7H1V1ZM1 17H7V23H1V17ZM17 1H23V7H17V1Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineQrCode.displayName = definePortfolioDisplayName("IconLineQrCode")

export { IconLineQrCode }