/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCircleCurrencyYenProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCircleCurrencyYenRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTI0IDEyQzI0IDE4LjYyNzQgMTguNjI3NCAyNCAxMiAyNEM1LjM3MjU4IDI0IDAgMTguNjI3NCAwIDEyQzAgNS4zNzI1OCA1LjM3MjU4IDAgMTIgMEMxOC42Mjc0IDAgMjQgNS4zNzI1OCAyNCAxMlpNMTIgMTAuNjQ3OUw5LjIwODA0IDYuNDU5OTZMNy45NTk5NiA3LjI5MjAxTDEwLjU5ODYgMTEuMjVIOC4yNTAwMlYxMi43NUgxMS4yNVYxNC4yNUg4LjI1MDAyVjE1Ljc1SDExLjI1VjE4SDEyLjc1VjE1Ljc1SDE1Ljc1VjE0LjI1SDEyLjc1VjEyLjc1SDE1Ljc1VjExLjI1SDEzLjQwMTRMMTYuMDQwMSA3LjI5MjAxTDE0Ljc5MiA2LjQ1OTk2TDEyIDEwLjY0NzlaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledCircleCurrencyYen = React.forwardRef<IconFilledCircleCurrencyYenRef, IconFilledCircleCurrencyYenProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-circle-currency-yen" ref={ref}><path fill-rule="evenodd" clip-rule="evenodd" d="M24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0C18.6274 0 24 5.37258 24 12ZM12 10.6479L9.20804 6.45996L7.95996 7.29201L10.5986 11.25H8.25002V12.75H11.25V14.25H8.25002V15.75H11.25V18H12.75V15.75H15.75V14.25H12.75V12.75H15.75V11.25H13.4014L16.0401 7.29201L14.792 6.45996L12 10.6479Z" fill="currentColor" /></IconBase>)
IconFilledCircleCurrencyYen.displayName = definePortfolioDisplayName("IconFilledCircleCurrencyYen")

export { IconFilledCircleCurrencyYen }