/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCircleCurrencyRupeeProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCircleCurrencyRupeeRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTI0IDEyQzI0IDE4LjYyNzQgMTguNjI3NCAyNCAxMiAyNEM1LjM3MjU4IDI0IDAgMTguNjI3NCAwIDEyQzAgNS4zNzI1OCA1LjM3MjU4IDAgMTIgMEMxOC42Mjc0IDAgMjQgNS4zNzI1OCAyNCAxMlpNMTUuNzUwMSA3LjVIOC4yNTAxMVY5SDEwLjUwMDFDMTEuMDk2OSA5IDExLjY2OTEgOS4yMzcwNSAxMi4wOTExIDkuNjU5MDFDMTIuMzMwNyA5Ljg5ODU2IDEyLjUxMDYgMTAuMTg2NiAxMi42MjE0IDEwLjVIOC4yNTAxMVYxMkgxMi42MjE0QzEyLjUxMDYgMTIuMzEzNCAxMi4zMzA3IDEyLjYwMTQgMTIuMDkxMSAxMi44NDFDMTEuNjY5MSAxMy4yNjI5IDExLjA5NjkgMTMuNSAxMC41MDAxIDEzLjVINy4xODk0NUwxMi4wMDAxIDE4LjMxMDdMMTMuMDYwOCAxNy4yNUwxMC43OTg5IDE0Ljk4ODFDMTEuNjg0MSAxNC45MTc0IDEyLjUxOTMgMTQuNTM0MiAxMy4xNTE4IDEzLjkwMTdDMTMuNjc1NiAxMy4zNzc5IDE0LjAyODQgMTIuNzE1MSAxNC4xNzQ0IDEySDE1Ljc1MDFWMTAuNUgxNC4xNzQ0QzE0LjA2MzYgOS45NTcyMyAxMy44MzM2IDkuNDQ0NTkgMTMuNTAwMSA5SDE1Ljc1MDFWNy41WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledCircleCurrencyRupee = React.forwardRef<IconFilledCircleCurrencyRupeeRef, IconFilledCircleCurrencyRupeeProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-circle-currency-rupee" ref={ref}><path fill-rule="evenodd" clip-rule="evenodd" d="M24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0C18.6274 0 24 5.37258 24 12ZM15.7501 7.5H8.25011V9H10.5001C11.0969 9 11.6691 9.23705 12.0911 9.65901C12.3307 9.89856 12.5106 10.1866 12.6214 10.5H8.25011V12H12.6214C12.5106 12.3134 12.3307 12.6014 12.0911 12.841C11.6691 13.2629 11.0969 13.5 10.5001 13.5H7.18945L12.0001 18.3107L13.0608 17.25L10.7989 14.9881C11.6841 14.9174 12.5193 14.5342 13.1518 13.9017C13.6756 13.3779 14.0284 12.7151 14.1744 12H15.7501V10.5H14.1744C14.0636 9.95723 13.8336 9.44459 13.5001 9H15.7501V7.5Z" fill="currentColor" /></IconBase>)
IconFilledCircleCurrencyRupee.displayName = definePortfolioDisplayName("IconFilledCircleCurrencyRupee")

export { IconFilledCircleCurrencyRupee }