/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineHospitalClinicProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineHospitalClinicRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTkgMjNWNUg1VjIzTTE5IDIzSDVNMTkgMjNWMTVIMjNWMjNIMTlaTTUgMjNIMVYxNUg1VjIzWk0xMiAxN0gxNlYyM0gxMk0xMiAxN1YyM00xMiAxN0g4VjIzSDEyTTEyIDhWMTRNOSAxMUgxNU04IDVIMTZWMUg4VjVaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineHospitalClinic = React.forwardRef<IconLineHospitalClinicRef, IconLineHospitalClinicProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-hospital-clinic" ref={ref}><path d="M19 23V5H5V23M19 23H5M19 23V15H23V23H19ZM5 23H1V15H5V23ZM12 17H16V23H12M12 17V23M12 17H8V23H12M12 8V14M9 11H15M8 5H16V1H8V5Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineHospitalClinic.displayName = definePortfolioDisplayName("IconLineHospitalClinic")

export { IconLineHospitalClinic }