/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineChipProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineChipRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTUgMVY0TTIzIDlIMjBNMjMgMTVIMjBNNCA5SDFNNCAxNUgxTTkgMVY0TTE1IDIwVjIzTTkgMjBWMjNNNyAyMEgxN0MxOC42NTY5IDIwIDIwIDE4LjY1NjkgMjAgMTdWN0MyMCA1LjM0MzE1IDE4LjY1NjkgNCAxNyA0SDdDNS4zNDMxNSA0IDQgNS4zNDMxNSA0IDdWMTdDNCAxOC42NTY5IDUuMzQzMTUgMjAgNyAyMFpNOS41IDE1SDE0LjVDMTQuNzc2MSAxNSAxNSAxNC43NzYxIDE1IDE0LjVWOS41QzE1IDkuMjIzODYgMTQuNzc2MSA5IDE0LjUgOUg5LjVDOS4yMjM4NiA5IDkgOS4yMjM4NiA5IDkuNVYxNC41QzkgMTQuNzc2MSA5LjIyMzg2IDE1IDkuNSAxNVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineChip = React.forwardRef<IconLineChipRef, IconLineChipProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-chip" ref={ref}><path d="M15 1V4M23 9H20M23 15H20M4 9H1M4 15H1M9 1V4M15 20V23M9 20V23M7 20H17C18.6569 20 20 18.6569 20 17V7C20 5.34315 18.6569 4 17 4H7C5.34315 4 4 5.34315 4 7V17C4 18.6569 5.34315 20 7 20ZM9.5 15H14.5C14.7761 15 15 14.7761 15 14.5V9.5C15 9.22386 14.7761 9 14.5 9H9.5C9.22386 9 9 9.22386 9 9.5V14.5C9 14.7761 9.22386 15 9.5 15Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineChip.displayName = definePortfolioDisplayName("IconLineChip")

export { IconLineChip }