/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineArrowCaretBackProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineArrowCaretBackRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNy45OTQxIDEyLjkxODJDNy40NTgzNSAxMi40MjMzIDcuNDU4MzUgMTEuNTc2OCA3Ljk5NDEgMTEuMDgxOEwxMi40MDE5IDcuMDEwMDZDMTMuMjAyNSA2LjI3MDUgMTQuNTAwMSA2LjgzODM0IDE0LjUwMDEgNy45MjgyNVYxNi4wNzE4QzE0LjUwMDEgMTcuMTYxNyAxMy4yMDI1IDE3LjcyOTYgMTIuNDAxOSAxNi45OUw3Ljk5NDEgMTIuOTE4MloiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconLineArrowCaretBack = React.forwardRef<IconLineArrowCaretBackRef, IconLineArrowCaretBackProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-arrow-caret-back" ref={ref}><path d="M7.9941 12.9182C7.45835 12.4233 7.45835 11.5768 7.9941 11.0818L12.4019 7.01006C13.2025 6.2705 14.5001 6.83834 14.5001 7.92825V16.0718C14.5001 17.1617 13.2025 17.7296 12.4019 16.99L7.9941 12.9182Z" fill="currentColor" /></IconBase>)
IconLineArrowCaretBack.displayName = definePortfolioDisplayName("IconLineArrowCaretBack")

export { IconLineArrowCaretBack }