/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWeatherCloudProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWeatherCloudRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTUuOTI5NyA4QzE0LjU0NjUgNS42MDg3OSAxMS45NjExIDQgOSA0QzQuNTgxNzIgNCAxIDcuNTgxNzIgMSAxMkMxIDE2LjQxODMgNC41ODE3MiAyMCA5IDIwSDE3QzIwLjMxMzcgMjAgMjMgMTcuMzEzNyAyMyAxNEMyMyAxMC42ODYzIDIwLjMxMzcgOCAxNyA4SDE1LjkyOTdaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineWeatherCloud = React.forwardRef<IconLineWeatherCloudRef, IconLineWeatherCloudProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-weather-cloud" ref={ref}><path d="M15.9297 8C14.5465 5.60879 11.9611 4 9 4C4.58172 4 1 7.58172 1 12C1 16.4183 4.58172 20 9 20H17C20.3137 20 23 17.3137 23 14C23 10.6863 20.3137 8 17 8H15.9297Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineWeatherCloud.displayName = definePortfolioDisplayName("IconLineWeatherCloud")

export { IconLineWeatherCloud }