/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBushProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBushRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOS4wMDAxMSAxNS4xMjlDOSAxNCAxMC4xOTQgMTMuMTI5IDExLjY2NjggMTMuMTI5QzEyLjY3MTEgMTMuMTI5IDEzLjU0NTcgMTMuNTQ1NCAxNC4wMDA1IDE0LjE2MDVNOC4wOTY3NyA3Ljg0QzguMDk2NzcgNS43MTkyMiAxMC4wMDMyIDQgMTIuMzU0OCA0QzE0LjQ2NzYgNCAxNi4yMjA5IDUuMzg3NjIgMTYuNTU1NCA3LjIwNzM4QzE5LjM1NjcgNy4zNDY0OCAyMS41ODA2IDkuNDM4OTggMjEuNTgwNiAxMkMyMS41ODA2IDEyLjUwNiAyMS40OTM4IDEyLjk5MzggMjEuMzMyOSAxMy40NTE4QzIyLjM1NTcgMTQuMjcyMyAyMyAxNS40NjgzIDIzIDE2LjhDMjMgMTguMDUzNiAyMi40MjkxIDE5LjE4NjkgMjEuNTA4OSAyMEgzLjY2NTQxQzIuMDcyMjEgMTkuMTcwNiAxIDE3LjYxODIgMSAxNS44NEMxIDEzLjc0NTkgMi40ODcwMSAxMS45NjUgNC41NjA3OCAxMS4zMDkyQzQuNTUyNTkgMTEuMjIwNCA0LjU0ODM5IDExLjEzMDcgNC41NDgzOSAxMS4wNEM0LjU0ODM5IDkuMjcyNyA2LjEzNzA2IDcuODQgOC4wOTY3NyA3Ljg0WiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineBush = React.forwardRef<IconLineBushRef, IconLineBushProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-bush" ref={ref}><path d="M9.00011 15.129C9 14 10.194 13.129 11.6668 13.129C12.6711 13.129 13.5457 13.5454 14.0005 14.1605M8.09677 7.84C8.09677 5.71922 10.0032 4 12.3548 4C14.4676 4 16.2209 5.38762 16.5554 7.20738C19.3567 7.34648 21.5806 9.43898 21.5806 12C21.5806 12.506 21.4938 12.9938 21.3329 13.4518C22.3557 14.2723 23 15.4683 23 16.8C23 18.0536 22.4291 19.1869 21.5089 20H3.66541C2.07221 19.1706 1 17.6182 1 15.84C1 13.7459 2.48701 11.965 4.56078 11.3092C4.55259 11.2204 4.54839 11.1307 4.54839 11.04C4.54839 9.2727 6.13706 7.84 8.09677 7.84Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineBush.displayName = definePortfolioDisplayName("IconLineBush")

export { IconLineBush }