/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineAlignMiddleProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineAlignMiddleRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMiAxMkgyMk0xMiAxNi43NUwxNCAxOC41SDEyLjVWMjNIMTEuNVYxOC41SDEwTDEyIDE2Ljc1Wk0xMiA3LjI1TDE0IDUuNUgxMi41VjFIMTEuNVY1LjVIMTBMMTIgNy4yNVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineAlignMiddle = React.forwardRef<IconLineAlignMiddleRef, IconLineAlignMiddleProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-align-middle" ref={ref}><path d="M2 12H22M12 16.75L14 18.5H12.5V23H11.5V18.5H10L12 16.75ZM12 7.25L14 5.5H12.5V1H11.5V5.5H10L12 7.25Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineAlignMiddle.displayName = definePortfolioDisplayName("IconLineAlignMiddle")

export { IconLineAlignMiddle }