/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineAttachProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineAttachRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjUiIHZpZXdCb3g9IjAgMCAyNCAyNSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuOTgwOSAxMC44NDU5TDEyLjA4MTQgMjAuNzQ1NEMxMi4wODE0IDIwLjc0NTQgNy40ODUyMyAyNS4zNDE2IDMuMjQyNTkgMjEuMDk5Qy0xLjAwMDA2IDE2Ljg1NjMgMy41OTYxNCAxMi4yNjAxIDMuNTk2MTQgMTIuMjYwMUwxMy44NDkyIDIuMDA3MDhDMTMuODQ5MiAyLjAwNzA4IDE2LjY3NzYgLTAuODIxMzQ4IDE5LjUwNiAyLjAwNzA4QzIyLjMzNDUgNC44MzU1MSAxOS41MDYgNy42NjM5MyAxOS41MDYgNy42NjM5M0w5LjYwNjU1IDE3LjU2MzRDOS42MDY1NSAxNy41NjM0IDguMTkyMzMgMTguOTc3NiA2Ljc3ODEyIDE3LjU2MzRDNS4zNjM5MSAxNi4xNDkyIDYuNzc4MTIgMTQuNzM1IDYuNzc4MTIgMTQuNzM1TDE1Ljk3MDUgNS41NDI2MSIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineAttach = React.forwardRef<IconLineAttachRef, IconLineAttachProps>((props, ref) => <IconBase {...props} width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-attach" ref={ref}><path d="M21.9809 10.8459L12.0814 20.7454C12.0814 20.7454 7.48523 25.3416 3.24259 21.099C-1.00006 16.8563 3.59614 12.2601 3.59614 12.2601L13.8492 2.00708C13.8492 2.00708 16.6776 -0.821348 19.506 2.00708C22.3345 4.83551 19.506 7.66393 19.506 7.66393L9.60655 17.5634C9.60655 17.5634 8.19233 18.9776 6.77812 17.5634C5.36391 16.1492 6.77812 14.735 6.77812 14.735L15.9705 5.54261" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineAttach.displayName = definePortfolioDisplayName("IconLineAttach")

export { IconLineAttach }