/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineIndentLessProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineIndentLessRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTMgN0gyM00xMyAxN0gyM00xMyAxMkgyM00xIDJIMjNNMSAyMkgyM002LjE4MTgyIDE2Ljg5MDdMMS4yNzI3MyAxMi42OTg3QzAuOTA5MDkxIDEyLjM4ODIgMC45MDkwOTEgMTEuNjExOCAxLjI3MjczIDExLjMwMTNMNi4xODE4MiA3LjEwOTI5QzYuNTQ1NDUgNi43OTg3NyA3IDcuMTg2OTIgNyA3LjgwNzk2VjE2LjE5MkM3IDE2LjgxMzEgNi41NDU0NiAxNy4yMDEyIDYuMTgxODIgMTYuODkwN1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineIndentLess = React.forwardRef<IconLineIndentLessRef, IconLineIndentLessProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-indent-less" ref={ref}><path d="M13 7H23M13 17H23M13 12H23M1 2H23M1 22H23M6.18182 16.8907L1.27273 12.6987C0.909091 12.3882 0.909091 11.6118 1.27273 11.3013L6.18182 7.10929C6.54545 6.79877 7 7.18692 7 7.80796V16.192C7 16.8131 6.54546 17.2012 6.18182 16.8907Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineIndentLess.displayName = definePortfolioDisplayName("IconLineIndentLess")

export { IconLineIndentLess }