/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineHalfStarProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineHalfStarRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNi44MDQ1MiAyMS44NzQ1TDExLjU2OSAxOC41MzA1QzExLjc3NjUgMTguMzg0OCAxMiAxOC4xODg4IDEyIDE3LjkzNTJWMi45NDYzMUMxMiAyLjUzMjE3IDExLjU5MDQgMi4xODk0IDExLjM2OSAyLjUzOTQxQzExLjM0NTkgMi41NzU4OCAxMS4zMjU0IDIuNjE1MjcgMTEuMzA3NyAyLjY1NzU2TDkuMTA2MTQgNy45MzE0NUM5LjAwMzU3IDguMTc3MTQgOC43Nzg0NSA4LjM1MDA0IDguNTE0NjEgOC4zODU3NUwyLjcxMjIyIDkuMTcxMDhDMi4wNjIwNCA5LjI1OTA4IDEuODMwMyAxMC4wODA2IDIuMzM4NjIgMTAuNDk1NEw2LjgxODc3IDE0LjE1MTRDNy4wNDAyNCAxNC4zMzIxIDcuMTM5NzIgMTQuNjIzMSA3LjA3NTI4IDE0LjkwMTZMNS42NDI5NyAyMS4wOTE1QzUuNDg3OSAyMS43NjE3IDYuMjQxNDkgMjIuMjY5NiA2LjgwNDUyIDIxLjg3NDVaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbWl0ZXJsaW1pdD0iMy4zMjkyIiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineHalfStar = React.forwardRef<IconLineHalfStarRef, IconLineHalfStarProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-half-star" ref={ref}><path d="M6.80452 21.8745L11.569 18.5305C11.7765 18.3848 12 18.1888 12 17.9352V2.94631C12 2.53217 11.5904 2.1894 11.369 2.53941C11.3459 2.57588 11.3254 2.61527 11.3077 2.65756L9.10614 7.93145C9.00357 8.17714 8.77845 8.35004 8.51461 8.38575L2.71222 9.17108C2.06204 9.25908 1.8303 10.0806 2.33862 10.4954L6.81877 14.1514C7.04024 14.3321 7.13972 14.6231 7.07528 14.9016L5.64297 21.0915C5.4879 21.7617 6.24149 22.2696 6.80452 21.8745Z" stroke="currentColor" strokeWidth="1.5" strokeMiterlimit="3.3292" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineHalfStar.displayName = definePortfolioDisplayName("IconLineHalfStar")

export { IconLineHalfStar }