/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineSidebarStartProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineSidebarStartRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOSAxVjIzTTMgMjNIMjFDMjIuMTA0NiAyMyAyMyAyMi4xMDQ2IDIzIDIxVjNDMjMgMS44OTU0MyAyMi4xMDQ2IDEgMjEgMUgzQzEuODk1NDMgMSAxIDEuODk1NDMgMSAzVjIxQzEgMjIuMTA0NiAxLjg5NTQzIDIzIDMgMjNaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineSidebarStart = React.forwardRef<IconLineSidebarStartRef, IconLineSidebarStartProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-sidebar-start" ref={ref}><path d="M9 1V23M3 23H21C22.1046 23 23 22.1046 23 21V3C23 1.89543 22.1046 1 21 1H3C1.89543 1 1 1.89543 1 3V21C1 22.1046 1.89543 23 3 23Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineSidebarStart.displayName = definePortfolioDisplayName("IconLineSidebarStart")

export { IconLineSidebarStart }