/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineInboxProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineInboxRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMyAxMlYxSDIxVjEyTTggNkgxNk04IDExSDE2TTEgMTZWMjNIMjNWMTZIMTZWMThIOFYxNkgxWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgLz48L3N2Zz4=) */
const IconLineInbox = React.forwardRef<IconLineInboxRef, IconLineInboxProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-inbox" ref={ref}><path d="M3 12V1H21V12M8 6H16M8 11H16M1 16V23H23V16H16V18H8V16H1Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineInbox.displayName = definePortfolioDisplayName("IconLineInbox")

export { IconLineInbox }