/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledMailProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledMailRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMC4xMDkxODggNS4zNDY1NEMwLjAzODQzMDEgNS41NTEzMiAwIDUuNzcxMTcgMCA2VjE5QzAgMjAuMTA0NiAwLjg5NTQzIDIxIDIgMjFIMjJDMjMuMTA0NiAyMSAyNCAyMC4xMDQ2IDI0IDE5VjZDMjQgNS43NzExOCAyMy45NjE2IDUuNTUxMzMgMjMuODkwOCA1LjM0NjU2TDE0Ljk0MzMgMTMuNTk4NEMxMy4yNzg1IDE1LjEzMzkgMTAuNzIxNiAxNS4xMzM5IDkuMDU2NzEgMTMuNTk4NEwwLjEwOTE4OCA1LjM0NjU0WiIgZmlsbD0iIzFFMjAyOCIgLz48cGF0aCBkPSJNMS4wOTU1NiA0LjIxNTdDMS4zMTI0NSA0LjEwNTU1IDEuNTUyMTEgNC4wMzM3OCAxLjgwNTYgNC4wMDkzM0MxLjg0NSA0LjAwMzIgMS44ODU4NyA0IDEuOTI4MSA0SDIyLjA3MTlDMjIuMTE0MSA0IDIyLjE1NSA0LjAwMzIgMjIuMTk0NCA0LjAwOTMzQzIyLjQ0NzkgNC4wMzM3OCAyMi42ODc2IDQuMTA1NTUgMjIuOTA0NSA0LjIxNTcxTDEzLjkyNjQgMTIuNDk1OEMxMi44MzYgMTMuNTAxNCAxMS4xNjQgMTMuNTAxNCAxMC4wNzM2IDEyLjQ5NThMMS4wOTU1NiA0LjIxNTdaIiBmaWxsPSIjMUUyMDI4IiAvPjwvc3ZnPg==) */
const IconFilledMail = React.forwardRef<IconFilledMailRef, IconFilledMailProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-mail" ref={ref}><path d="M0.109188 5.34654C0.0384301 5.55132 0 5.77117 0 6V19C0 20.1046 0.89543 21 2 21H22C23.1046 21 24 20.1046 24 19V6C24 5.77118 23.9616 5.55133 23.8908 5.34656L14.9433 13.5984C13.2785 15.1339 10.7216 15.1339 9.05671 13.5984L0.109188 5.34654Z" fill="currentColor" /><path d="M1.09556 4.2157C1.31245 4.10555 1.55211 4.03378 1.8056 4.00933C1.845 4.0032 1.88587 4 1.9281 4H22.0719C22.1141 4 22.155 4.0032 22.1944 4.00933C22.4479 4.03378 22.6876 4.10555 22.9045 4.21571L13.9264 12.4958C12.836 13.5014 11.164 13.5014 10.0736 12.4958L1.09556 4.2157Z" fill="currentColor" /></IconBase>)
IconFilledMail.displayName = definePortfolioDisplayName("IconFilledMail")

export { IconFilledMail }