/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledSidebarEndProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledSidebarEndRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTAuMjUgM0MwLjI1IDEuNDgxMjIgMS40ODEyMiAwLjI1IDMgMC4yNUgyMUMyMi41MTg4IDAuMjUgMjMuNzUgMS40ODEyMiAyMy43NSAzVjIxQzIzLjc1IDIyLjUxODggMjIuNTE4OCAyMy43NSAyMSAyMy43NUgzQzEuNDgxMjIgMjMuNzUgMC4yNSAyMi41MTg4IDAuMjUgMjFWM1pNMyAxLjc1QzIuMzA5NjQgMS43NSAxLjc1IDIuMzA5NjQgMS43NSAzVjIxQzEuNzUgMjEuNjkwNCAyLjMwOTY0IDIyLjI1IDMgMjIuMjVIMjFDMjEuNjkwNCAyMi4yNSAyMi4yNSAyMS42OTA0IDIyLjI1IDIxVjNDMjIuMjUgMi4zMDk2NCAyMS42OTA0IDEuNzUgMjEgMS43NUgzWiIgZmlsbD0iIzFFMjAyOCIgLz48cGF0aCBkPSJNMTUgMUgyMUMyMi4xMDQ2IDEgMjMgMS44OTU0MyAyMyAzVjIxQzIzIDIyLjEwNDYgMjIuMTA0NiAyMyAyMSAyM0gxNVYxWiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledSidebarEnd = React.forwardRef<IconFilledSidebarEndRef, IconFilledSidebarEndProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-sidebar-end" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M0.25 3C0.25 1.48122 1.48122 0.25 3 0.25H21C22.5188 0.25 23.75 1.48122 23.75 3V21C23.75 22.5188 22.5188 23.75 21 23.75H3C1.48122 23.75 0.25 22.5188 0.25 21V3ZM3 1.75C2.30964 1.75 1.75 2.30964 1.75 3V21C1.75 21.6904 2.30964 22.25 3 22.25H21C21.6904 22.25 22.25 21.6904 22.25 21V3C22.25 2.30964 21.6904 1.75 21 1.75H3Z" fill="currentColor" /><path d="M15 1H21C22.1046 1 23 1.89543 23 3V21C23 22.1046 22.1046 23 21 23H15V1Z" fill="currentColor" /></IconBase>)
IconFilledSidebarEnd.displayName = definePortfolioDisplayName("IconFilledSidebarEnd")

export { IconFilledSidebarEnd }