/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBackUndoProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBackUndoRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOS40NTAxIDE0LjQ1MzRMMS43NDg3NiAxNC41MDczTTEuNzQ4NzYgMTQuNTA3M0wxLjc0ODU0IDdNMS43NDg3NiAxNC41MDczTDUuMjEyMTYgMTAuODU3NkMxMC4wMDM4IDUuODA4MjMgMTguNDIwMyA3LjQ2MTc4IDIwLjk0NTUgMTMuOTQ4NiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineBackUndo = React.forwardRef<IconLineBackUndoRef, IconLineBackUndoProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-back-undo" ref={ref}><path d="M9.4501 14.4534L1.74876 14.5073M1.74876 14.5073L1.74854 7M1.74876 14.5073L5.21216 10.8576C10.0038 5.80823 18.4203 7.46178 20.9455 13.9486" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineBackUndo.displayName = definePortfolioDisplayName("IconLineBackUndo")

export { IconLineBackUndo }