/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineDeviceMouseProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineDeviceMouseRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIgOVY4TTEyIDIyQzguNjg2MjkgMjIgNiAxOS4zMTM3IDYgMTZWOEM2IDQuNjg2MjkgOC42ODYyOSAyIDEyIDJDMTUuMzEzNyAyIDE4IDQuNjg2MjkgMTggOFYxNkMxOCAxOS4zMTM3IDE1LjMxMzcgMjIgMTIgMjJaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIC8+PC9zdmc+) */
const IconLineDeviceMouse = React.forwardRef<IconLineDeviceMouseRef, IconLineDeviceMouseProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-device-mouse" ref={ref}><path d="M12 9V8M12 22C8.68629 22 6 19.3137 6 16V8C6 4.68629 8.68629 2 12 2C15.3137 2 18 4.68629 18 8V16C18 19.3137 15.3137 22 12 22Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineDeviceMouse.displayName = definePortfolioDisplayName("IconLineDeviceMouse")

export { IconLineDeviceMouse }