/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineDeleteProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineDeleteRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTcgNVY0QzE3IDIuMzQzMTUgMTUuNjU2OSAxIDE0IDFIMTBDOC4zNDMxNSAxIDcgMi4zNDMxNSA3IDRWNU0xIDVIMjNNMTUgMTFWMTZNOSAxMVYxNk0zIDVIMjFMMjAuMzM3NSAxOC4yNDk3QzIwLjIwNDUgMjAuOTEwNyAxOC4wMDgxIDIzIDE1LjM0MzggMjNIOC42NTYyNEM1Ljk5MTg3IDIzIDMuNzk1NTQgMjAuOTEwNyAzLjY2MjQ4IDE4LjI0OTdMMyA1WiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineDelete = React.forwardRef<IconLineDeleteRef, IconLineDeleteProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-delete" ref={ref}><path d="M17 5V4C17 2.34315 15.6569 1 14 1H10C8.34315 1 7 2.34315 7 4V5M1 5H23M15 11V16M9 11V16M3 5H21L20.3375 18.2497C20.2045 20.9107 18.0081 23 15.3438 23H8.65624C5.99187 23 3.79554 20.9107 3.66248 18.2497L3 5Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineDelete.displayName = definePortfolioDisplayName("IconLineDelete")

export { IconLineDelete }