/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineFullScreenExpandResizeProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineFullScreenExpandResizeRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTUuMjE0NCAzLjY0ODU2TDIwLjQ4OSAzLjY0ODU2TTIwLjQ4OSAzLjY0ODU2VjguOTM5NE0yMC40ODkgMy42NDg1NkwxNC41MDA2IDkuNTIzNjNNMjAuMzcxMSAxNC43MTM5TDIwLjM3MDYgMTkuOTg4M00yMC4zNzA2IDE5Ljk4ODNMMTUuMDc5NiAxOS45ODc4TTIwLjM3MDYgMTkuOTg4M0wxNC41MDA2IDE0LjQ5OTdNOC45MTE5OCAyMC4wMTEySDMuNjM3MzVNMy42MzczNSAyMC4wMTEyTDMuNjM3MzUgMTQuNzIwM00zLjYzNzM1IDIwLjAxMTJMOS41MDAzOCAxNC40OTk2TTMuNjI4OTEgOC45MTUwNkwzLjYyOTQgMy42NDA2Mk0zLjYyOTQgMy42NDA2Mkw4LjkyMDQ0IDMuNjQxMTJNMy42Mjk0IDMuNjQwNjJMOS42MTA2IDkuNDk5MzciIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineFullScreenExpandResize = React.forwardRef<IconLineFullScreenExpandResizeRef, IconLineFullScreenExpandResizeProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-full-screen-expand-resize" ref={ref}><path d="M15.2144 3.64856L20.489 3.64856M20.489 3.64856V8.9394M20.489 3.64856L14.5006 9.52363M20.3711 14.7139L20.3706 19.9883M20.3706 19.9883L15.0796 19.9878M20.3706 19.9883L14.5006 14.4997M8.91198 20.0112H3.63735M3.63735 20.0112L3.63735 14.7203M3.63735 20.0112L9.50038 14.4996M3.62891 8.91506L3.6294 3.64062M3.6294 3.64062L8.92044 3.64112M3.6294 3.64062L9.6106 9.49937" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineFullScreenExpandResize.displayName = definePortfolioDisplayName("IconLineFullScreenExpandResize")

export { IconLineFullScreenExpandResize }