/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineEditProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineEditRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTMuNjAwNCA1LjU3ODc0TDE4LjE5MTYgMTAuMTdNMTUuOTI4NCAzLjI1MDc4QzE1LjkyODQgMy4yNTA3OCAxOC4wMzYyIDIuMjkwOCAxOS44NzI3IDQuMTI3MjlDMjEuNzA5MiA1Ljk2Mzc3IDIwLjc0OTIgOC4wNzE1NiAyMC43NDkyIDguMDcxNTZMOC40NzgxNSAyMC4zNDI2TDMgMjFMMy42NTczOCAxNS41MjE4TDE1LjkyODQgMy4yNTA3OFoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineEdit = React.forwardRef<IconLineEditRef, IconLineEditProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-edit" ref={ref}><path d="M13.6004 5.57874L18.1916 10.17M15.9284 3.25078C15.9284 3.25078 18.0362 2.2908 19.8727 4.12729C21.7092 5.96377 20.7492 8.07156 20.7492 8.07156L8.47815 20.3426L3 21L3.65738 15.5218L15.9284 3.25078Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineEdit.displayName = definePortfolioDisplayName("IconLineEdit")

export { IconLineEdit }