/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineLoadingProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineLoadingRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIgMkMxMC4wMjIyIDIgOC4wODg3OSAyLjU4NjQ5IDYuNDQ0MyAzLjY4NTNDNC43OTk4MSA0Ljc4NDEyIDMuNTE4MDkgNi4zNDU5IDIuNzYxMjEgOC4xNzMxNkMyLjAwNDMzIDEwLjAwMDQgMS44MDYzIDEyLjAxMTEgMi4xOTIxNSAxMy45NTA5QzIuNTc4IDE1Ljg5MDcgMy41MzA0MSAxNy42NzI1IDQuOTI4OTQgMTkuMDcxMUM2LjMyNzQ2IDIwLjQ2OTYgOC4xMDkyOSAyMS40MjIgMTAuMDQ5MSAyMS44MDc5QzExLjk4ODkgMjIuMTkzNyAxMy45OTk2IDIxLjk5NTcgMTUuODI2OCAyMS4yMzg4QzE3LjY1NDEgMjAuNDgxOSAxOS4yMTU5IDE5LjIwMDIgMjAuMzE0NyAxNy41NTU3QzIxLjQxMzUgMTUuOTExMiAyMiAxMy45Nzc4IDIyIDEyIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineLoading = React.forwardRef<IconLineLoadingRef, IconLineLoadingProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-loading" ref={ref}><path d="M12 2C10.0222 2 8.08879 2.58649 6.4443 3.6853C4.79981 4.78412 3.51809 6.3459 2.76121 8.17316C2.00433 10.0004 1.8063 12.0111 2.19215 13.9509C2.578 15.8907 3.53041 17.6725 4.92894 19.0711C6.32746 20.4696 8.10929 21.422 10.0491 21.8079C11.9889 22.1937 13.9996 21.9957 15.8268 21.2388C17.6541 20.4819 19.2159 19.2002 20.3147 17.5557C21.4135 15.9112 22 13.9778 22 12" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineLoading.displayName = definePortfolioDisplayName("IconLineLoading")

export { IconLineLoading }