/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineWrenchProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineWrenchRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTYuMjYzNSA1LjM2MzExTDE5LjUwNDggMi4xMjE3OEMxNy43MTA2IDEuNDE4NjcgMTUuNTkxOSAxLjc5MjAyIDE0LjE0MjEgMy4yNDE4MUMxMy4yNjYgNC4xMTc5MiAxMi43ODMgNS4yMzgyNSAxMi42OTMxIDYuMzgzNjZMMTIuNTUxMiA3LjY2MDkzQzEyLjQzNzcgOC42ODIzOSAxMS45MzU0IDkuNjIwOTggMTEuMTQ4NCAxMC4yODJMMy45Mzc5MyAxNi4zMzg4QzMuNzk2NTYgMTYuNDM3OSAzLjY2MTgyIDE2LjU1MDYgMy41MzU1NCAxNi42NzY4QzIuMzYzOTcgMTcuODQ4NCAyLjM2Mzk3IDE5Ljc0NzkgMy41MzU1NCAyMC45MTk1QzQuNzA3MTEgMjIuMDkxMSA2LjYwNjYxIDIyLjA5MTEgNy43NzgxOCAyMC45MTk1QzcuOTA0NDYgMjAuNzkzMiA4LjAxNzEzIDIwLjY1ODUgOC4xMTYxOSAyMC41MTcxTDE0LjE3MyAxMy4zMDY2QzE0LjgzNCAxMi41MTk2IDE1Ljc3MjYgMTIuMDE3MyAxNi43OTQxIDExLjkwMzhMMTguMDcxNCAxMS43NjE5QzE5LjIxNjggMTEuNjcyIDIwLjMzNzEgMTEuMTg5IDIxLjIxMzIgMTAuMzEyOUMyMi42NjMgOC44NjMwOCAyMy4wMzYzIDYuNzQ0NDcgMjIuMzMzMiA0Ljk1MDIxTDE5LjA5MTkgOC4xOTE1NEMxOS4wOTE5IDguMTkxNTQgMTguMzg0OCA4LjE5MTU2IDE3LjMyNDEgNy4xMzA5QzE2LjI2MzUgNi4wNzAyNCAxNi4yNjM1IDUuMzYzMTEgMTYuMjYzNSA1LjM2MzExWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgLz48L3N2Zz4=) */
const IconLineWrench = React.forwardRef<IconLineWrenchRef, IconLineWrenchProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-wrench" ref={ref}><path d="M16.2635 5.36311L19.5048 2.12178C17.7106 1.41867 15.5919 1.79202 14.1421 3.24181C13.266 4.11792 12.783 5.23825 12.6931 6.38366L12.5512 7.66093C12.4377 8.68239 11.9354 9.62098 11.1484 10.282L3.93793 16.3388C3.79656 16.4379 3.66182 16.5506 3.53554 16.6768C2.36397 17.8484 2.36397 19.7479 3.53554 20.9195C4.70711 22.0911 6.60661 22.0911 7.77818 20.9195C7.90446 20.7932 8.01713 20.6585 8.11619 20.5171L14.173 13.3066C14.834 12.5196 15.7726 12.0173 16.7941 11.9038L18.0714 11.7619C19.2168 11.672 20.3371 11.189 21.2132 10.3129C22.663 8.86308 23.0363 6.74447 22.3332 4.95021L19.0919 8.19154C19.0919 8.19154 18.3848 8.19156 17.3241 7.1309C16.2635 6.07024 16.2635 5.36311 16.2635 5.36311Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineWrench.displayName = definePortfolioDisplayName("IconLineWrench")

export { IconLineWrench }