/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLinePaddleboardProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLinePaddleboardRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNS4xNzM4NSAxOC43MjU3TDE4LjYyNTMgNS4yNzQyMU0xNiAxMkMxNiAxOC4wNzUxIDE0LjIwOTEgMjMgMTIgMjNDOS43OTA4NSAyMyA3Ljk5OTk5IDE4LjA3NTEgNy45OTk5OSAxMkM3Ljk5OTk5IDUuOTI0ODcgOS43OTA4NSAxIDEyIDFDMTQuMjA5MSAxIDE2IDUuOTI0ODcgMTYgMTJaTTIuMjM1MzQgMTcuNTM1QzIuMjM1MzQgMTcuNTM1IDEuNTc4NiAxNy45MzY3IDEuMzk0NjIgMTguMzc1N0MwLjk4MzIxNiAxOS4zNTcyIDEuNzE3MDkgMjAuMzc5NiAyLjYxODU2IDIxLjI4MTFDMy41MjAwMyAyMi4xODI1IDQuNTQyNCAyMi45MTY0IDUuNTIzOTQgMjIuNTA1QzUuOTYyOSAyMi4zMjEgNi4zNjQ2NSAyMS42NjQzIDYuMzY0NjUgMjEuNjY0M0M2LjM2NDY1IDIxLjY2NDMgOC44NTMxIDE3Ljk1MzYgNy4zOTk1MyAxNi41QzUuOTQ1OTUgMTUuMDQ2NCAyLjIzNTM0IDE3LjUzNSAyLjIzNTM0IDE3LjUzNVpNMjEuNTMwOCA2LjQ5ODE4QzIxLjUzMDggNi40OTgxOCAyMi4xODc2IDYuMDk2NDIgMjIuMzcxNSA1LjY1NzQ2QzIyLjc4MjkgNC42NzU5MiAyMi4wNDkxIDMuNjUzNTYgMjEuMTQ3NiAyLjc1MjA5QzIwLjI0NjEgMS44NTA2MiAxOS4yMjM4IDEuMTE2NzQgMTguMjQyMiAxLjUyODE0QzE3LjgwMzMgMS43MTIxMyAxNy40MDE1IDIuMzY4ODYgMTcuNDAxNSAyLjM2ODg2QzE3LjQwMTUgMi4zNjg4NiAxNC45NDYgNi4wNDY0MiAxNi4zOTk1IDcuNUMxNy44NTMxIDguOTUzNTggMjEuNTMwOCA2LjQ5ODE4IDIxLjUzMDggNi40OTgxOFoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLinePaddleboard = React.forwardRef<IconLinePaddleboardRef, IconLinePaddleboardProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-paddleboard" ref={ref}><path d="M5.17385 18.7257L18.6253 5.27421M16 12C16 18.0751 14.2091 23 12 23C9.79085 23 7.99999 18.0751 7.99999 12C7.99999 5.92487 9.79085 1 12 1C14.2091 1 16 5.92487 16 12ZM2.23534 17.535C2.23534 17.535 1.5786 17.9367 1.39462 18.3757C0.983216 19.3572 1.71709 20.3796 2.61856 21.2811C3.52003 22.1825 4.5424 22.9164 5.52394 22.505C5.9629 22.321 6.36465 21.6643 6.36465 21.6643C6.36465 21.6643 8.8531 17.9536 7.39953 16.5C5.94595 15.0464 2.23534 17.535 2.23534 17.535ZM21.5308 6.49818C21.5308 6.49818 22.1876 6.09642 22.3715 5.65746C22.7829 4.67592 22.0491 3.65356 21.1476 2.75209C20.2461 1.85062 19.2238 1.11674 18.2422 1.52814C17.8033 1.71213 17.4015 2.36886 17.4015 2.36886C17.4015 2.36886 14.946 6.04642 16.3995 7.5C17.8531 8.95358 21.5308 6.49818 21.5308 6.49818Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLinePaddleboard.displayName = definePortfolioDisplayName("IconLinePaddleboard")

export { IconLinePaddleboard }