/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineDomeProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineDomeRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMSAxOC4zQzEuMTI2MTcgMTcuODk5NiAxLjI3NDg0IDE3LjQ2MyAxLjQ0NDkzIDE3TTEuNDQ0OTMgMTdDMi4wMzI3NSAxNS40MDAxIDIuODc2NDUgMTMuNDg1MyAzLjkzMTQxIDExLjY2TTEuNDQ0OTMgMTdMOS4xMzc5MyAxOU0zLjkzMTQxIDExLjY2QzUuOTUwOTkgOC4xNjU4OCA4Ljc0NDgzIDUgMTIgNUMxMy42OTQ2IDUgMTUuMjY0MiA1LjkwMzE3IDE2LjY2NDYgNy4yODgwOE0zLjkzMTQxIDExLjY2TDkuOTgxMTEgMTIuODg3TTE2LjY2NDYgNy4yODgwOEMxOS4zNzUgOS45Njg0MiAyMS40NTE2IDE0LjQ1MzIgMjIuNTc0NSAxNy42ODczTTE2LjY2NDYgNy4yODgwOEwxMC41Mzg1IDEzTDkuOTgxMTEgMTIuODg3TTIyLjU3NDUgMTcuNjg3M0MyMi43MzY1IDE4LjE1NCAyMi44Nzg3IDE4LjU5NDYgMjMgMTlNMjIuNTc0NSAxNy42ODczTDkuMTM3OTMgMTlNOSAyMEw5LjEzNzkzIDE5TTkuMTM3OTMgMTlMOS45ODExMSAxMi44ODdNOS45ODExMSAxMi44ODdMMTEgNS41TTEyIDE2TDE1IDE1LjVDMTUuNjA2MSAxNS4yNzc4IDE3IDE1LjEgMTcgMTMuNUMxNyAxMS41IDE1LjA5MiA5Ljg2MDQ4IDE0LjYzNzQgOS4xOTM4MSIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineDome = React.forwardRef<IconLineDomeRef, IconLineDomeProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-dome" ref={ref}><path d="M1 18.3C1.12617 17.8996 1.27484 17.463 1.44493 17M1.44493 17C2.03275 15.4001 2.87645 13.4853 3.93141 11.66M1.44493 17L9.13793 19M3.93141 11.66C5.95099 8.16588 8.74483 5 12 5C13.6946 5 15.2642 5.90317 16.6646 7.28808M3.93141 11.66L9.98111 12.887M16.6646 7.28808C19.375 9.96842 21.4516 14.4532 22.5745 17.6873M16.6646 7.28808L10.5385 13L9.98111 12.887M22.5745 17.6873C22.7365 18.154 22.8787 18.5946 23 19M22.5745 17.6873L9.13793 19M9 20L9.13793 19M9.13793 19L9.98111 12.887M9.98111 12.887L11 5.5M12 16L15 15.5C15.6061 15.2778 17 15.1 17 13.5C17 11.5 15.092 9.86048 14.6374 9.19381" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineDome.displayName = definePortfolioDisplayName("IconLineDome")

export { IconLineDome }