/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineArrowGoingUpProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineArrowGoingUpRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOC42NjQxMiA1LjQzNTU1TDE4LjM2MzYgNS42MzU2MU0xOC4zNjM2IDUuNjM1NjFMMTguNTYzNiAxNS4zMzVNMTguMzYzNiA1LjYzNTYxTDYuMzY1MjMgMTcuNjc4OCIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineArrowGoingUp = React.forwardRef<IconLineArrowGoingUpRef, IconLineArrowGoingUpProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-arrow-going-up" ref={ref}><path d="M8.66412 5.43555L18.3636 5.63561M18.3636 5.63561L18.5636 15.335M18.3636 5.63561L6.36523 17.6788" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineArrowGoingUp.displayName = definePortfolioDisplayName("IconLineArrowGoingUp")

export { IconLineArrowGoingUp }