/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineSendProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineSendRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjUiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNSAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMS4zOTEwNCAxMi44MjY3QzAuNTYzMjkxIDEyLjUwODMgMC41Mjg4NDQgMTEuMzUgMS4zMzYyMSAxMC45ODNMMjAuMDcxMSAyLjQ2NzEyQzIwLjkxMjMgMi4wODQ3NiAyMS43Nzc3IDIuOTUwMTEgMjEuMzk1MyAzLjc5MTI5TDEyLjg3OTQgMjIuNTI2MkMxMi41MTI0IDIzLjMzMzYgMTEuMzU0MSAyMy4yOTkxIDExLjAzNTcgMjIuNDcxNEw4LjUxNjE4IDE1LjkyMDZDOC40MTQ2MSAxNS42NTY1IDguMjA1OTEgMTUuNDQ3OCA3Ljk0MTgyIDE1LjM0NjJMMS4zOTEwNCAxMi44MjY3WiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgLz48L3N2Zz4=) */
const IconLineSend = React.forwardRef<IconLineSendRef, IconLineSendProps>((props, ref) => <IconBase {...props} width="25" height="24" viewBox="0 0 25 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-send" ref={ref}><path d="M1.39104 12.8267C0.563291 12.5083 0.528844 11.35 1.33621 10.983L20.0711 2.46712C20.9123 2.08476 21.7777 2.95011 21.3953 3.79129L12.8794 22.5262C12.5124 23.3336 11.3541 23.2991 11.0357 22.4714L8.51618 15.9206C8.41461 15.6565 8.20591 15.4478 7.94182 15.3462L1.39104 12.8267Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineSend.displayName = definePortfolioDisplayName("IconLineSend")

export { IconLineSend }