/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineConfigureProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineConfigureRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMyAxN0gxNE0xNCAxN0MxNCAxOC42NTY5IDE1LjM0MzEgMjAgMTcgMjBDMTguNjU2OSAyMCAyMCAxOC42NTY5IDIwIDE3QzIwIDE1LjM0MzEgMTguNjU2OSAxNCAxNyAxNEMxNS4zNDMxIDE0IDE0IDE1LjM0MzEgMTQgMTdaTTkgN0gyME05IDdDOSA4LjY1Njg1IDcuNjU2ODUgMTAgNiAxMEM0LjM0MzE1IDEwIDMgOC42NTY4NSAzIDdDMyA1LjM0MzE1IDQuMzQzMTUgNCA2IDRDNy42NTY4NSA0IDkgNS4zNDMxNSA5IDdaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIC8+PC9zdmc+) */
const IconLineConfigure = React.forwardRef<IconLineConfigureRef, IconLineConfigureProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-configure" ref={ref}><path d="M3 17H14M14 17C14 18.6569 15.3431 20 17 20C18.6569 20 20 18.6569 20 17C20 15.3431 18.6569 14 17 14C15.3431 14 14 15.3431 14 17ZM9 7H20M9 7C9 8.65685 7.65685 10 6 10C4.34315 10 3 8.65685 3 7C3 5.34315 4.34315 4 6 4C7.65685 4 9 5.34315 9 7Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineConfigure.displayName = definePortfolioDisplayName("IconLineConfigure")

export { IconLineConfigure }