/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineGifProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineGifRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIuNzUyNSA4LjQ5Nzk1VjE1Ljk5OE0xOS4yNTI2IDguNDk3OTVIMTYuMjUyNlYxMi4yNDhNMTYuMjUyNiAxMi4yNDhWMTUuOTk4TTE2LjI1MjYgMTIuMjQ4SDE4Ljc1TTkuMjUyNTIgOS4wOTc5NUM4LjIyMjUyIDcuNjMzOTUgNi41NTI1MiA3LjYzNDA1IDUuNTIyNTIgOS4wOTgwNUM0LjQ5MjUyIDEwLjU2MyA0LjQ5MjQ4IDEzLjQzNiA1LjUyMjQ4IDE0LjlDNi41NTI0OCAxNi4zNjQgOC4yMjM0OCAxNi4zNjQgOS4yNTI0OCAxNC45VjEyLjI0OEg4TTUgMjFIMTlDMjEuMjA5MSAyMSAyMyAxOS4yMDkxIDIzIDE3VjdDMjMgNC43OTA4NiAyMS4yMDkxIDMgMTkgM0g1QzIuNzkwODYgMyAxIDQuNzkwODYgMSA3VjE3QzEgMTkuMjA5MSAyLjc5MDg2IDIxIDUgMjFaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineGif = React.forwardRef<IconLineGifRef, IconLineGifProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-gif" ref={ref}><path d="M12.7525 8.49795V15.998M19.2526 8.49795H16.2526V12.248M16.2526 12.248V15.998M16.2526 12.248H18.75M9.25252 9.09795C8.22252 7.63395 6.55252 7.63405 5.52252 9.09805C4.49252 10.563 4.49248 13.436 5.52248 14.9C6.55248 16.364 8.22348 16.364 9.25248 14.9V12.248H8M5 21H19C21.2091 21 23 19.2091 23 17V7C23 4.79086 21.2091 3 19 3H5C2.79086 3 1 4.79086 1 7V17C1 19.2091 2.79086 21 5 21Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineGif.displayName = definePortfolioDisplayName("IconLineGif")

export { IconLineGif }