/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineCutProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineCutRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOC4xNTEzNyA4LjMwNDA4TDIxIDIxTTguMTUxMzcgMTUuNjUwNkwxMS41MzI2IDEyLjMwOTZNMTQuODQ1NyA5LjAzNTY2TDIwLjkzMTkgMy4wMjE4MU05IDZDOSA3LjY1Njg1IDcuNjU2ODUgOSA2IDlDNC4zNDMxNSA5IDMgNy42NTY4NSAzIDZDMyA0LjM0MzE1IDQuMzQzMTUgMyA2IDNDNy42NTY4NSAzIDkgNC4zNDMxNSA5IDZaTTkgMThDOSAxOS42NTY5IDcuNjU2ODUgMjEgNiAyMUM0LjM0MzE1IDIxIDMgMTkuNjU2OSAzIDE4QzMgMTYuMzQzMSA0LjM0MzE1IDE1IDYgMTVDNy42NTY4NSAxNSA5IDE2LjM0MzEgOSAxOFoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineCut = React.forwardRef<IconLineCutRef, IconLineCutProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-cut" ref={ref}><path d="M8.15137 8.30408L21 21M8.15137 15.6506L11.5326 12.3096M14.8457 9.03566L20.9319 3.02181M9 6C9 7.65685 7.65685 9 6 9C4.34315 9 3 7.65685 3 6C3 4.34315 4.34315 3 6 3C7.65685 3 9 4.34315 9 6ZM9 18C9 19.6569 7.65685 21 6 21C4.34315 21 3 19.6569 3 18C3 16.3431 4.34315 15 6 15C7.65685 15 9 16.3431 9 18Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineCut.displayName = definePortfolioDisplayName("IconLineCut")

export { IconLineCut }