/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBulletsNumberedProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBulletsNumberedRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAgNUgyMk0xMCAxMkgyMk0xMCAxOUgyMk0yIDNIMy41VjdNMiAxN0g0LjVWMTlNNC41IDE5SDNNNC41IDE5VjIxSDJNMiAxMEg0LjVMMi41IDEzLjVINSIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineBulletsNumbered = React.forwardRef<IconLineBulletsNumberedRef, IconLineBulletsNumberedProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-bullets-numbered" ref={ref}><path d="M10 5H22M10 12H22M10 19H22M2 3H3.5V7M2 17H4.5V19M4.5 19H3M4.5 19V21H2M2 10H4.5L2.5 13.5H5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineBulletsNumbered.displayName = definePortfolioDisplayName("IconLineBulletsNumbered")

export { IconLineBulletsNumbered }