/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledFilledThumbsDownProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledFilledThumbsDownRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNCAxNEMyLjM0MzE1IDE0IDEgMTIuNjU2OSAxIDExVjVDMSAzLjM0MzE1IDIuMzQzMTUgMiA0IDJINVYxNEg0WiIgZmlsbD0iIzFFMjAyOCIgLz48cGF0aCBkPSJNNyAxNS4xNzc3VjJIMTcuNzM3MUMxOS4wNzY1IDIgMjAuMjUzNyAyLjg4NzkzIDIwLjYyMTcgNC4xNzU4NEwyMi45MDc0IDEyLjE3NThDMjMuNDU0OSAxNC4wOTIzIDIyLjAxNTkgMTYgMjAuMDIyOCAxNkgxNS42MjM1QzE0LjcyNTkgMTYgMTQuMDI5MyAxNi43ODMxIDE0LjEzMzcgMTcuNjc0NkwxNC41MDQxIDIwLjgzNDZDMTQuNzAxNSAyMi41MTk4IDEzLjM4NDcgMjQgMTEuNjg3OSAyNEMxMS4xMTkyIDI0IDEwLjYwNTYgMjMuNjYwMiAxMC4zODMxIDIzLjEzNjhMNy4wMTc1MyAxNS4yMTc3QzcuMDExODIgMTUuMjA0MyA3LjAwNTk4IDE1LjE5MDkgNyAxNS4xNzc3WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledFilledThumbsDown = React.forwardRef<IconFilledFilledThumbsDownRef, IconFilledFilledThumbsDownProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-filled-thumbs-down" ref={ref}><path d="M4 14C2.34315 14 1 12.6569 1 11V5C1 3.34315 2.34315 2 4 2H5V14H4Z" fill="currentColor" /><path d="M7 15.1777V2H17.7371C19.0765 2 20.2537 2.88793 20.6217 4.17584L22.9074 12.1758C23.4549 14.0923 22.0159 16 20.0228 16H15.6235C14.7259 16 14.0293 16.7831 14.1337 17.6746L14.5041 20.8346C14.7015 22.5198 13.3847 24 11.6879 24C11.1192 24 10.6056 23.6602 10.3831 23.1368L7.01753 15.2177C7.01182 15.2043 7.00598 15.1909 7 15.1777Z" fill="currentColor" /></IconBase>)
IconFilledFilledThumbsDown.displayName = definePortfolioDisplayName("IconFilledFilledThumbsDown")

export { IconFilledFilledThumbsDown }