/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineSearchProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineSearchRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTcuMzM0MiAxNy4zOTM2QzE4Ljk4MDMgMTUuNzYyNiAyMCAxMy41MDA0IDIwIDExQzIwIDYuMDI5NDQgMTUuOTcwNiAyIDExIDJDNi4wMjk0NCAyIDIgNi4wMjk0NCAyIDExQzIgMTUuOTcwNiA2LjAyOTQ0IDIwIDExIDIwQzEzLjQ3MDIgMjAgMTUuNzA3OSAxOS4wMDQ5IDE3LjMzNDIgMTcuMzkzNlpNMTcuMzM0MiAxNy4zOTM2TDIxLjQ0MDYgMjEuNSIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineSearch = React.forwardRef<IconLineSearchRef, IconLineSearchProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-search" ref={ref}><path d="M17.3342 17.3936C18.9803 15.7626 20 13.5004 20 11C20 6.02944 15.9706 2 11 2C6.02944 2 2 6.02944 2 11C2 15.9706 6.02944 20 11 20C13.4702 20 15.7079 19.0049 17.3342 17.3936ZM17.3342 17.3936L21.4406 21.5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineSearch.displayName = definePortfolioDisplayName("IconLineSearch")

export { IconLineSearch }