/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineDryerProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineDryerRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNC41IDQuNUg1LjVNMTEuNTUxMSAxMC4zMjQ2QzExLjU1MTEgMTAuMzI0NiAxMS4zMjc2IDExLjU5NTkgMTMuMDg0IDExLjYyMjlDMTQuODQwNCAxMS42NSAxNC42MTY5IDEyLjkyMTIgMTQuNjE2OSAxMi45MjEyTTkuMzgzMjggMTMuMDc4OEM5LjM4MzI4IDEzLjA3ODggOS4xNTk3MyAxNC4zNSAxMC45MTYyIDE0LjM3NzFDMTIuNjcyNiAxNC40MDQxIDEyLjQ0OTEgMTUuNjc1NCAxMi40NDkxIDE1LjY3NTRNMyAyM0gyMUMyMi4xMDQ2IDIzIDIzIDIyLjEwNDYgMjMgMjFWM0MyMyAxLjg5NTQzIDIyLjEwNDYgMSAyMSAxSDNDMS44OTU0MyAxIDEgMS44OTU0MyAxIDNWMjFDMSAyMi4xMDQ2IDEuODk1NDMgMjMgMyAyM1pNMTggMTNDMTggMTYuMzEzNyAxNS4zMTM3IDE5IDEyIDE5QzguNjg2MjkgMTkgNiAxNi4zMTM3IDYgMTNDNiA5LjY4NjI5IDguNjg2MjkgNyAxMiA3QzE1LjMxMzcgNyAxOCA5LjY4NjI5IDE4IDEzWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineDryer = React.forwardRef<IconLineDryerRef, IconLineDryerProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-dryer" ref={ref}><path d="M4.5 4.5H5.5M11.5511 10.3246C11.5511 10.3246 11.3276 11.5959 13.084 11.6229C14.8404 11.65 14.6169 12.9212 14.6169 12.9212M9.38328 13.0788C9.38328 13.0788 9.15973 14.35 10.9162 14.3771C12.6726 14.4041 12.4491 15.6754 12.4491 15.6754M3 23H21C22.1046 23 23 22.1046 23 21V3C23 1.89543 22.1046 1 21 1H3C1.89543 1 1 1.89543 1 3V21C1 22.1046 1.89543 23 3 23ZM18 13C18 16.3137 15.3137 19 12 19C8.68629 19 6 16.3137 6 13C6 9.68629 8.68629 7 12 7C15.3137 7 18 9.68629 18 13Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineDryer.displayName = definePortfolioDisplayName("IconLineDryer")

export { IconLineDryer }