/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineSaveFavoriteImportantProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineSaveFavoriteImportantRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMyA0SDE1TDIxIDEyTDE1IDIwSDNMOSAxMkwzIDRaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjwvc3ZnPg==) */
const IconLineSaveFavoriteImportant = React.forwardRef<IconLineSaveFavoriteImportantRef, IconLineSaveFavoriteImportantProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-save-favorite-important" ref={ref}><path d="M3 4H15L21 12L15 20H3L9 12L3 4Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineSaveFavoriteImportant.displayName = definePortfolioDisplayName("IconLineSaveFavoriteImportant")

export { IconLineSaveFavoriteImportant }