/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineDeviceDesktopProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineDeviceDesktopRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIgMTZWMjBNMTIgMjBDMTMuNTc0MyAyMCAxNiAyMSAxNiAyMU0xMiAyMEMxMC40MjU3IDIwIDggMjEgOCAyMU0xIDE1LjVWNC41QzEgNC4yMjM4NiAxLjIxNzYxIDQgMS40OTM3NSA0QzQuMjcyNTMgNCAxNy45OTY3IDQgMjIuNTAzNSA0QzIyLjc3OTYgNCAyMyA0LjIyMzg2IDIzIDQuNVYxNS41QzIzIDE1Ljc3NjEgMjIuNzc5NiAxNiAyMi41MDM1IDE2QzE3Ljk5NjcgMTYgNC4yNzI1MyAxNiAxLjQ5Mzc1IDE2QzEuMjE3NjEgMTYgMSAxNS43NzYxIDEgMTUuNVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineDeviceDesktop = React.forwardRef<IconLineDeviceDesktopRef, IconLineDeviceDesktopProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-device-desktop" ref={ref}><path d="M12 16V20M12 20C13.5743 20 16 21 16 21M12 20C10.4257 20 8 21 8 21M1 15.5V4.5C1 4.22386 1.21761 4 1.49375 4C4.27253 4 17.9967 4 22.5035 4C22.7796 4 23 4.22386 23 4.5V15.5C23 15.7761 22.7796 16 22.5035 16C17.9967 16 4.27253 16 1.49375 16C1.21761 16 1 15.7761 1 15.5Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineDeviceDesktop.displayName = definePortfolioDisplayName("IconLineDeviceDesktop")

export { IconLineDeviceDesktop }