/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineAlignRightProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineAlignRightRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjYiIGhlaWdodD0iMjYiIHZpZXdCb3g9IjAgMCAyNiAyNiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMC43NjQ3MDYgMC43NjQ3MDZIMjUuMjM1M003LjQzODUgOC45MjE1N0gyNS4yMzUzTTAuNzY0NzA2IDE3LjA3ODRIMjUuMjM1M003LjQzODUgMjUuMjM1M0gyNS4yMzUzIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineAlignRight = React.forwardRef<IconLineAlignRightRef, IconLineAlignRightProps>((props, ref) => <IconBase {...props} width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-align-right" ref={ref}><path d="M0.764706 0.764706H25.2353M7.4385 8.92157H25.2353M0.764706 17.0784H25.2353M7.4385 25.2353H25.2353" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineAlignRight.displayName = definePortfolioDisplayName("IconLineAlignRight")

export { IconLineAlignRight }