/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineCastProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineCastRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMS4wMDAyMSAyMUwxLjAwMDIxIDIwLjk5TTEuMDAwMjEgOFY2QzEuMDAwMjEgNC4zNDMxNSAyLjM0MzM1IDMgNC4wMDAyMSAzTDIwLjI5MjcgM0MyMS45NDk1IDMgMjMuMDAwMiA0LjM0MzE1IDIzLjAwMDIgNlYxOEMyMy4wMDAyIDE5LjY1NjkgMjEuNjU3MSAyMSAyMC4wMDAyIDIxSDE0LjAwMDJNMS4wMDAxOSAxNi41MDA1QzIuMTc3MjEgMTYuNTM1MyAzLjQzMTY4IDE2Ljk5NzYgNC4yODg0NyAxNy44NTQ0QzUuMTQ1MjcgMTguNzExMiA1LjQ2NTQyIDE5LjgyMzUgNS41MDAxOSAyMS4wMDA1TTEgMTIuNTAwMkM1LjU1MjIzIDEyLjYzMzcgOS4zNjYxIDE2LjQ0NzkgOS41MDAyMiAyMS4wMDA3IiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineCast = React.forwardRef<IconLineCastRef, IconLineCastProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-cast" ref={ref}><path d="M1.00021 21L1.00021 20.99M1.00021 8V6C1.00021 4.34315 2.34335 3 4.00021 3L20.2927 3C21.9495 3 23.0002 4.34315 23.0002 6V18C23.0002 19.6569 21.6571 21 20.0002 21H14.0002M1.00019 16.5005C2.17721 16.5353 3.43168 16.9976 4.28847 17.8544C5.14527 18.7112 5.46542 19.8235 5.50019 21.0005M1 12.5002C5.55223 12.6337 9.3661 16.4479 9.50022 21.0007" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineCast.displayName = definePortfolioDisplayName("IconLineCast")

export { IconLineCast }