/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineLighterProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineLighterRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTAgMTRWNEg0QzQgNCAzIDUuNSAzIDlDMyAxMi41IDQgMTQgNCAxNEgxMFpNMTAgMTRIMjBWMjFDMjAgMjIuMTA0NiAxOS4xMDQ2IDIzIDE4IDIzSDEyQzEwLjg5NTQgMjMgMTAgMjIuMTA0NiAxMCAyMVYxNFpNMTAgMTRIMThNMTAgMTRWOUgxOE0xOCA5VjE0TTE4IDlDMTggOSAyMSA5IDIxIDExLjVDMjEgMTQgMTggMTQgMTggMTRNMTYgNS41QzE2IDYuODgwNzEgMTUuMzI4NCA4IDE0LjUgOEMxMy42NzE2IDggMTMgNi44ODA3MSAxMyA1LjVDMTMgNC4xMTkyOSAxNC41IDMgMTQuNSAzQzE0LjUgMyAxNiA0LjExOTI5IDE2IDUuNVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineLighter = React.forwardRef<IconLineLighterRef, IconLineLighterProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-lighter" ref={ref}><path d="M10 14V4H4C4 4 3 5.5 3 9C3 12.5 4 14 4 14H10ZM10 14H20V21C20 22.1046 19.1046 23 18 23H12C10.8954 23 10 22.1046 10 21V14ZM10 14H18M10 14V9H18M18 9V14M18 9C18 9 21 9 21 11.5C21 14 18 14 18 14M16 5.5C16 6.88071 15.3284 8 14.5 8C13.6716 8 13 6.88071 13 5.5C13 4.11929 14.5 3 14.5 3C14.5 3 16 4.11929 16 5.5Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineLighter.displayName = definePortfolioDisplayName("IconLineLighter")

export { IconLineLighter }