/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBoldProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBoldRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNiAxMlYyMUgxMy41QzE1Ljk4NTMgMjEgMTggMTguOTg1MyAxOCAxNi41QzE4IDE0LjAxNDcgMTUuOTg1MyAxMiAxMy41IDEyQzE1Ljk4NTMgMTIgMTggOS45ODUyOCAxOCA3LjVDMTggNS4wMTQ3MiAxNS45ODUzIDMgMTMuNSAzSDZWMTJaTTYgMTJIMTUiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineBold = React.forwardRef<IconLineBoldRef, IconLineBoldProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-bold" ref={ref}><path d="M6 12V21H13.5C15.9853 21 18 18.9853 18 16.5C18 14.0147 15.9853 12 13.5 12C15.9853 12 18 9.98528 18 7.5C18 5.01472 15.9853 3 13.5 3H6V12ZM6 12H15" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineBold.displayName = definePortfolioDisplayName("IconLineBold")

export { IconLineBold }