/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineCircleCurrencyBangladeshiProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineCircleCurrencyBangladeshiRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOC4yNSA3LjVMOC42NjUgNy4yOTNDOC43NzkyNyA3LjIzNTk1IDguOTA2MjEgNy4yMDkwMyA5LjAzMzggNy4yMTQ3OUM5LjE2MTM5IDcuMjIwNTQgOS4yODUzOSA3LjI1ODc4IDkuMzk0MDYgNy4zMjU4OUM5LjUwMjczIDcuMzkyOTkgOS41OTI0NiA3LjQ4NjczIDkuNjU0NzUgNy41OTgyM0M5LjcxNzA0IDcuNzA5NzMgOS43NDk4MyA3LjgzNTI4IDkuNzUgNy45NjNWMTAuNU05Ljc1IDEwLjVIMTUuNzVNOS43NSAxMC41SDguMjVNOS43NSAxMC41VjE1LjkzOEM5Ljc1IDE2LjI5MiA5LjkxMSAxNi42MzUgMTAuMjIzIDE2LjgwM0MxMC43MzgyIDE3LjA4MDEgMTEuMzExIDE3LjIzMjkgMTEuODk1NyAxNy4yNDkxQzEyLjQ4MDQgMTcuMjY1MyAxMy4wNjA4IDE3LjE0NDYgMTMuNTkwNSAxNi44OTY1QzE0LjEyMDMgMTYuNjQ4NSAxNC41ODQ3IDE2LjI4IDE0Ljk0NjYgMTUuODIwNEMxNS4zMDg1IDE1LjM2MDkgMTUuNTU4IDE0LjgyMzEgMTUuNjc1IDE0LjI1QzE1Ljc1OCAxMy44NDEgMTUuNDEyIDEzLjUgMTQuOTk1IDEzLjVIMTQuMjVNMjIgMTJDMjIgMTcuNTIyOCAxNy41MjI4IDIyIDEyIDIyQzYuNDc3MTUgMjIgMiAxNy41MjI4IDIgMTJDMiA2LjQ3NzE1IDYuNDc3MTUgMiAxMiAyQzE3LjUyMjggMiAyMiA2LjQ3NzE1IDIyIDEyWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineCircleCurrencyBangladeshi = React.forwardRef<IconLineCircleCurrencyBangladeshiRef, IconLineCircleCurrencyBangladeshiProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-circle-currency-bangladeshi" ref={ref}><path d="M8.25 7.5L8.665 7.293C8.77927 7.23595 8.90621 7.20903 9.0338 7.21479C9.16139 7.22054 9.28539 7.25878 9.39406 7.32589C9.50273 7.39299 9.59246 7.48673 9.65475 7.59823C9.71704 7.70973 9.74983 7.83528 9.75 7.963V10.5M9.75 10.5H15.75M9.75 10.5H8.25M9.75 10.5V15.938C9.75 16.292 9.911 16.635 10.223 16.803C10.7382 17.0801 11.311 17.2329 11.8957 17.2491C12.4804 17.2653 13.0608 17.1446 13.5905 16.8965C14.1203 16.6485 14.5847 16.28 14.9466 15.8204C15.3085 15.3609 15.558 14.8231 15.675 14.25C15.758 13.841 15.412 13.5 14.995 13.5H14.25M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineCircleCurrencyBangladeshi.displayName = definePortfolioDisplayName("IconLineCircleCurrencyBangladeshi")

export { IconLineCircleCurrencyBangladeshi }