/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineComponentProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineComponentRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOC4zNjM5NiAxOC4yNjM1TDExLjg5OTUgMTQuNzI3OUwxNS40MzUgMTguMjYzNUwxMS44OTk1IDIxLjc5OUw4LjM2Mzk2IDE4LjI2MzVaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjxwYXRoIGQ9Ik0yIDExLjg5OTVMNS41MzU1MyA4LjM2Mzk2TDkuMDcxMDcgMTEuODk5NUw1LjUzNTUzIDE1LjQzNUwyIDExLjg5OTVaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjxwYXRoIGQ9Ik0xNC43Mjc5IDExLjg5OTVMMTguMjYzNSA4LjM2Mzk2TDIxLjc5OSAxMS44OTk1TDE4LjI2MzUgMTUuNDM1TDE0LjcyNzkgMTEuODk5NVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PHBhdGggZD0iTTguMzYzOTYgNS41MzU1M0wxMS44OTk1IDJMMTUuNDM1IDUuNTM1NTNMMTEuODk5NSA5LjA3MTA3TDguMzYzOTYgNS41MzU1M1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineComponent = React.forwardRef<IconLineComponentRef, IconLineComponentProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-component" ref={ref}><path d="M8.36396 18.2635L11.8995 14.7279L15.435 18.2635L11.8995 21.799L8.36396 18.2635Z" stroke="currentColor" strokeWidth="1.5" /><path d="M2 11.8995L5.53553 8.36396L9.07107 11.8995L5.53553 15.435L2 11.8995Z" stroke="currentColor" strokeWidth="1.5" /><path d="M14.7279 11.8995L18.2635 8.36396L21.799 11.8995L18.2635 15.435L14.7279 11.8995Z" stroke="currentColor" strokeWidth="1.5" /><path d="M8.36396 5.53553L11.8995 2L15.435 5.53553L11.8995 9.07107L8.36396 5.53553Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineComponent.displayName = definePortfolioDisplayName("IconLineComponent")

export { IconLineComponent }