/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledInfoProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledInfoRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTYuNSAyLjVDMTYuNSAzLjg4MDcxIDE1LjM4MDcgNSAxNCA1QzEyLjYxOTMgNSAxMS41IDMuODgwNzEgMTEuNSAyLjVDMTEuNSAxLjExOTI5IDEyLjYxOTMgMCAxNCAwQzE1LjM4MDcgMCAxNi41IDEuMTE5MjkgMTYuNSAyLjVaIiBmaWxsPSIjMUUyMDI4IiAvPjxwYXRoIGQ9Ik0xNS41MDc1IDhINkw1IDEwLjVMMTAgMTFMNi41NzQ3NCAxOC45MzU0QzYuNTc0NzQgMTguOTM1NCA2LjQwNjU3IDIwLjE2NjMgNi41NzQ3NCAyMC45MjQ3QzYuNzYyNzYgMjEuNzcyNSA2Ljk3MDc0IDIyLjI4MzggNy41NjcyNyAyMi45MTM5QzguNjY3MiAyNC4wNzU3IDkuOTUxMTUgMjQuMTAzNyAxMS41Mzc0IDIzLjkwODVDMTQuMjU3NyAyMy41NzM3IDE3IDE5LjUgMTcgMTkuNUwxNS41MDc1IDE3Ljk0MDhDMTUuNTA3NSAxNy45NDA4IDEzLjUyMjMgMTkuOTMgMTIuNTI5OCAxOS45M0MxMS41MzczIDE5LjkzIDExLjUzNzQgMTguOTM1NCAxMS41Mzc0IDE4LjkzNTRMMTUuNTA3NSA4WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledInfo = React.forwardRef<IconFilledInfoRef, IconFilledInfoProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-info" ref={ref}><path d="M16.5 2.5C16.5 3.88071 15.3807 5 14 5C12.6193 5 11.5 3.88071 11.5 2.5C11.5 1.11929 12.6193 0 14 0C15.3807 0 16.5 1.11929 16.5 2.5Z" fill="currentColor" /><path d="M15.5075 8H6L5 10.5L10 11L6.57474 18.9354C6.57474 18.9354 6.40657 20.1663 6.57474 20.9247C6.76276 21.7725 6.97074 22.2838 7.56727 22.9139C8.6672 24.0757 9.95115 24.1037 11.5374 23.9085C14.2577 23.5737 17 19.5 17 19.5L15.5075 17.9408C15.5075 17.9408 13.5223 19.93 12.5298 19.93C11.5373 19.93 11.5374 18.9354 11.5374 18.9354L15.5075 8Z" fill="currentColor" /></IconBase>)
IconFilledInfo.displayName = definePortfolioDisplayName("IconFilledInfo")

export { IconFilledInfo }