/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineBikeProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineBikeRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTkgMTVDMTkgMTUgMTkuMzk2MSAxMi44NzY4IDE5LjUgMTEuNUMxOS42MTc2IDkuOTQyMzMgMTkuNTk2NyA5LjA1OTEgMTkuNSA3LjVDMTkuNDAyNiA1LjkyODc2IDIwIDIuNSAyMCAyLjVMMTQuNSAzLjVNOSA0SDRNNi41IDQuNUw1IDE1QzUgMTUgOCAxMSAxMS41IDlDMTUgNyAxOS41IDcgMTkuNSA3TTIzIDE1QzIzIDE3LjIwOTEgMjEuMjA5MSAxOSAxOSAxOUMxNi43OTA5IDE5IDE1IDE3LjIwOTEgMTUgMTVDMTUgMTIuNzkwOSAxNi43OTA5IDExIDE5IDExQzIxLjIwOTEgMTEgMjMgMTIuNzkwOSAyMyAxNVpNOSAxNUM5IDE3LjIwOTEgNy4yMDkxNCAxOSA1IDE5QzIuNzkwODYgMTkgMSAxNy4yMDkxIDEgMTVDMSAxMi43OTA5IDIuNzkwODYgMTEgNSAxMUM3LjIwOTE0IDExIDkgMTIuNzkwOSA5IDE1WiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineBike = React.forwardRef<IconLineBikeRef, IconLineBikeProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-bike" ref={ref}><path d="M19 15C19 15 19.3961 12.8768 19.5 11.5C19.6176 9.94233 19.5967 9.0591 19.5 7.5C19.4026 5.92876 20 2.5 20 2.5L14.5 3.5M9 4H4M6.5 4.5L5 15C5 15 8 11 11.5 9C15 7 19.5 7 19.5 7M23 15C23 17.2091 21.2091 19 19 19C16.7909 19 15 17.2091 15 15C15 12.7909 16.7909 11 19 11C21.2091 11 23 12.7909 23 15ZM9 15C9 17.2091 7.20914 19 5 19C2.79086 19 1 17.2091 1 15C1 12.7909 2.79086 11 5 11C7.20914 11 9 12.7909 9 15Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineBike.displayName = definePortfolioDisplayName("IconLineBike")

export { IconLineBike }