/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFillSkipBackwardProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFillSkipBackwardRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjAuMjQ4IDUuMjU0NDVDMjEuMjQ0OCA0LjU4OTg5IDIyLjU4IDUuMzA0NDggMjIuNTggNi41MDI1MlYxNi44OTdDMjIuNTggMTguMDk1IDIxLjI0NDggMTguODA5NiAyMC4yNDggMTguMTQ1TDEyLjQ1MjEgMTIuOTQ3OEMxMi4wNjU3IDEyLjY5MDIgMTEuODQ2OSAxMi4yOTc5IDExLjc5NTggMTEuODg3OFYxNi44OTdDMTEuNzk1OCAxOC4wOTUgMTAuNDYwNiAxOC44MDk2IDkuNDYzNzkgMTguMTQ1TDEuNjY3OTUgMTIuOTQ3OEMwLjc3NzM1IDEyLjM1NDEgMC43NzczNSAxMS4wNDU0IDEuNjY3OTUgMTAuNDUxN0w5LjQ2Mzc5IDUuMjU0NDVDMTAuNDYwNiA0LjU4OTg5IDExLjc5NTggNS4zMDQ0OCAxMS43OTU4IDYuNTAyNTJWMTEuNTExN0MxMS44NDY5IDExLjEwMTYgMTIuMDY1NyAxMC43MDkzIDEyLjQ1MjEgMTAuNDUxN0wyMC4yNDggNS4yNTQ0NVoiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFillSkipBackward = React.forwardRef<IconFillSkipBackwardRef, IconFillSkipBackwardProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-fill-skip-backward" ref={ref}><path d="M20.248 5.25445C21.2448 4.58989 22.58 5.30448 22.58 6.50252V16.897C22.58 18.095 21.2448 18.8096 20.248 18.145L12.4521 12.9478C12.0657 12.6902 11.8469 12.2979 11.7958 11.8878V16.897C11.7958 18.095 10.4606 18.8096 9.46379 18.145L1.66795 12.9478C0.77735 12.3541 0.77735 11.0454 1.66795 10.4517L9.46379 5.25445C10.4606 4.58989 11.7958 5.30448 11.7958 6.50252V11.5117C11.8469 11.1016 12.0657 10.7093 12.4521 10.4517L20.248 5.25445Z" fill="currentColor" /></IconBase>)
IconFillSkipBackward.displayName = definePortfolioDisplayName("IconFillSkipBackward")

export { IconFillSkipBackward }