/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineCallProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineCallRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTcuMjc3OSAxLjk3Mzk1TDIwLjc0NTkgMi4zNTkyOEMyMS42NzU2IDIuNDYyNTggMjIuMzkyNiAzLjE5OTk0IDIyLjI5NDkgNC4xMzAyNEMyMi4wNTA5IDYuNDU1OTEgMjAuOTAxNSAxMS4wNDE2IDE1Ljk3MjEgMTUuOTcxQzExLjA0MjggMjAuOTAwMyA2LjQ1NjQ4IDIyLjA1MDQgNC4xMzAzOCAyMi4yOTQ5QzMuMTk5OTEgMjIuMzkyNyAyLjQ2MjMxIDIxLjY3NTYgMi4zNTg5OSAyMC43NDU3TDEuOTczNyAxNy4yNzgxQzEuODg1NjMgMTYuNDg1NSAyLjI3NjkgMTUuNzE2MyAyLjk2OTQgMTUuMzIwN0w1LjQ1MzUgMTMuOTAxNkM2LjIzNjU0IDEzLjQ1NDMgNy4yMjIxIDEzLjU4NjMgNy44NTk3OCAxNC4yMjRMOC40OTcwNiAxNC44NjEzQzguOTY5OTEgMTUuMzM0MSA5LjY1MTM0IDE1LjUzNDIgMTAuMjU1NyAxNS4yNDc5QzEwLjk3MTcgMTQuOTA4NyAxMi4wMDY2IDE0LjI3OTYgMTMuMTQzIDEzLjE0MzNDMTQuMjc5NCAxMi4wMDY5IDE0LjkwODUgMTAuOTcyIDE1LjI0NzcgMTAuMjU1OUMxNS41MzM5IDkuNjUxNTggMTUuMzMzOSA4Ljk3MDE1IDE0Ljg2MSA4LjQ5NzMxTDE0LjIyMzcgNy44NjAwMkMxMy41ODYxIDcuMjIyMzUgMTMuNDU0IDYuMjM2NzkgMTMuOTAxMyA1LjQ1Mzc0TDE1LjMyMDQgMi45Njk2NUMxNS43MTYgMi4yNzcxNSAxNi40ODUzIDEuODg1ODggMTcuMjc3OSAxLjk3Mzk1WiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiAvPjwvc3ZnPg==) */
const IconLineCall = React.forwardRef<IconLineCallRef, IconLineCallProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-call" ref={ref}><path d="M17.2779 1.97395L20.7459 2.35928C21.6756 2.46258 22.3926 3.19994 22.2949 4.13024C22.0509 6.45591 20.9015 11.0416 15.9721 15.971C11.0428 20.9003 6.45648 22.0504 4.13038 22.2949C3.19991 22.3927 2.46231 21.6756 2.35899 20.7457L1.9737 17.2781C1.88563 16.4855 2.2769 15.7163 2.9694 15.3207L5.4535 13.9016C6.23654 13.4543 7.2221 13.5863 7.85978 14.224L8.49706 14.8613C8.96991 15.3341 9.65134 15.5342 10.2557 15.2479C10.9717 14.9087 12.0066 14.2796 13.143 13.1433C14.2794 12.0069 14.9085 10.972 15.2477 10.2559C15.5339 9.65158 15.3339 8.97015 14.861 8.49731L14.2237 7.86002C13.5861 7.22235 13.454 6.23679 13.9013 5.45374L15.3204 2.96965C15.716 2.27715 16.4853 1.88588 17.2779 1.97395Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineCall.displayName = definePortfolioDisplayName("IconLineCall")

export { IconLineCall }