/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledPaypalProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledPaypalRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMjEuODgzNSA2Ljg1ODM2QzIyLjIwMSA0Ljc1ODkxIDIxLjg4MDggMy4zMjk0NiAyMC43ODYyIDIuMDM1MDZDMTkuNTc5MiAwLjYwOTg2NiAxNy40MDExIDAgMTQuNjEzOCAwSDYuNTIxOTFDNS45NTI2MSAwIDUuNDY2OTMgMC40MjkyMTEgNS4zNzg5NyAxLjAxMzUyTDIuMDA4NjMgMjMuMTY2NEMxLjk0MjE4IDIzLjYwNDYgMi4yNjgxNCAyNCAyLjY5NDM5IDI0SDcuNjg5OThMOC45MTI3IDE1Ljk2MzNDOS4wMTgwNyAxNS40MDIzIDkuNDg4ODYgMTQuOTk0MiAxMC4wNDQ5IDE0Ljk5NDJIMTIuNDE5QzE3LjA4MTYgMTQuOTk0MiAyMC43MzI1IDEzLjAzMDYgMjEuNzk5NSA3LjM1MDM2QzIxLjgzMTQgNy4xODIyNCAyMS44NTk1IDcuMDE4NDcgMjEuODgzNSA2Ljg1ODM2WiIgZmlsbD0iIzFFMjAyOCIgLz48L3N2Zz4=) */
const IconFilledPaypal = React.forwardRef<IconFilledPaypalRef, IconFilledPaypalProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-paypal" ref={ref}><path d="M21.8835 6.85836C22.201 4.75891 21.8808 3.32946 20.7862 2.03506C19.5792 0.609866 17.4011 0 14.6138 0H6.52191C5.95261 0 5.46693 0.429211 5.37897 1.01352L2.00863 23.1664C1.94218 23.6046 2.26814 24 2.69439 24H7.68998L8.9127 15.9633C9.01807 15.4023 9.48886 14.9942 10.0449 14.9942H12.419C17.0816 14.9942 20.7325 13.0306 21.7995 7.35036C21.8314 7.18224 21.8595 7.01847 21.8835 6.85836Z" fill="currentColor" /></IconBase>)
IconFilledPaypal.displayName = definePortfolioDisplayName("IconFilledPaypal")

export { IconFilledPaypal }