/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineTagProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineTagRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOC4wMDAwMyA3Ljk5OTY4TDkuMDAwMDMgOC45OTk2OE0xLjYxOTc2IDIuNTc4ODdMMS4yNzQwMSAxMS4yMjI3QzEuMjQwNTQgMTIuMDU5MyAxLjU1ODIzIDEyLjg3MTggMi4xNTAyOSAxMy40NjM5TDEwLjg0OSAyMi4xNjI2QzEyLjAyMDYgMjMuMzM0MiAxMy45MjAxIDIzLjMzNDIgMTUuMDkxNyAyMi4xNjI2TDIyLjE2MjcgMTUuMDkxNkMyMy4zMzQzIDEzLjkyIDIzLjMzNDMgMTIuMDIwNSAyMi4xNjI3IDEwLjg0ODlMMTMuNDY0IDIuMTUwMTdDMTIuODcxOSAxLjU1ODExIDEyLjA1OTQgMS4yNDA0MiAxMS4yMjI4IDEuMjczODhMMi41Nzg5OSAxLjYxOTY0QzIuMDU4MSAxLjY0MDQ3IDEuNjQwNTkgMi4wNTc5NyAxLjYxOTc2IDIuNTc4ODdaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineTag = React.forwardRef<IconLineTagRef, IconLineTagProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-tag" ref={ref}><path d="M8.00003 7.99968L9.00003 8.99968M1.61976 2.57887L1.27401 11.2227C1.24054 12.0593 1.55823 12.8718 2.15029 13.4639L10.849 22.1626C12.0206 23.3342 13.9201 23.3342 15.0917 22.1626L22.1627 15.0916C23.3343 13.92 23.3343 12.0205 22.1627 10.8489L13.464 2.15017C12.8719 1.55811 12.0594 1.24042 11.2228 1.27388L2.57899 1.61964C2.0581 1.64047 1.64059 2.05797 1.61976 2.57887Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineTag.displayName = definePortfolioDisplayName("IconLineTag")

export { IconLineTag }