/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineGridFeedCardsProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineGridFeedCardsRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMSAzQzEgMS44OTU0MyAxLjg5NTQzIDEgMyAxSDdDOC4xMDQ1NyAxIDkgMS44OTU0MyA5IDNWN0M5IDguMTA0NTcgOC4xMDQ1NyA5IDcgOUgzQzEuODk1NDMgOSAxIDguMTA0NTcgMSA3VjNaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiAvPjxwYXRoIGQ9Ik0xNSAzQzE1IDEuODk1NDMgMTUuODk1NCAxIDE3IDFIMjFDMjIuMTA0NiAxIDIzIDEuODk1NDMgMjMgM1Y3QzIzIDguMTA0NTcgMjIuMTA0NiA5IDIxIDlIMTdDMTUuODk1NCA5IDE1IDguMTA0NTcgMTUgN1YzWiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgLz48cGF0aCBkPSJNMSAxN0MxIDE1Ljg5NTQgMS44OTU0MyAxNSAzIDE1SDdDOC4xMDQ1NyAxNSA5IDE1Ljg5NTQgOSAxN1YyMUM5IDIyLjEwNDYgOC4xMDQ1NyAyMyA3IDIzSDNDMS44OTU0MyAyMyAxIDIyLjEwNDYgMSAyMVYxN1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PHBhdGggZD0iTTE1IDE3QzE1IDE1Ljg5NTQgMTUuODk1NCAxNSAxNyAxNUgyMUMyMi4xMDQ2IDE1IDIzIDE1Ljg5NTQgMjMgMTdWMjFDMjMgMjIuMTA0NiAyMi4xMDQ2IDIzIDIxIDIzSDE3QzE1Ljg5NTQgMjMgMTUgMjIuMTA0NiAxNSAyMVYxN1oiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineGridFeedCards = React.forwardRef<IconLineGridFeedCardsRef, IconLineGridFeedCardsProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-grid-feed-cards" ref={ref}><path d="M1 3C1 1.89543 1.89543 1 3 1H7C8.10457 1 9 1.89543 9 3V7C9 8.10457 8.10457 9 7 9H3C1.89543 9 1 8.10457 1 7V3Z" stroke="currentColor" strokeWidth="1.5" /><path d="M15 3C15 1.89543 15.8954 1 17 1H21C22.1046 1 23 1.89543 23 3V7C23 8.10457 22.1046 9 21 9H17C15.8954 9 15 8.10457 15 7V3Z" stroke="currentColor" strokeWidth="1.5" /><path d="M1 17C1 15.8954 1.89543 15 3 15H7C8.10457 15 9 15.8954 9 17V21C9 22.1046 8.10457 23 7 23H3C1.89543 23 1 22.1046 1 21V17Z" stroke="currentColor" strokeWidth="1.5" /><path d="M15 17C15 15.8954 15.8954 15 17 15H21C22.1046 15 23 15.8954 23 17V21C23 22.1046 22.1046 23 21 23H17C15.8954 23 15 22.1046 15 21V17Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineGridFeedCards.displayName = definePortfolioDisplayName("IconLineGridFeedCards")

export { IconLineGridFeedCards }