/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineGiftProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineGiftRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIgMjIuNVY2LjVNNCAxMkgyMFYyMkg0VjEyWk0zIDEySDIxQzIxLjU1MjMgMTIgMjIgMTEuNTUyMyAyMiAxMVY3QzIyIDYuNDQ3NzIgMjEuNTUyMyA2IDIxIDZIM0MyLjQ0NzcyIDYgMiA2LjQ0NzcyIDIgN1YxMUMyIDExLjU1MjMgMi40NDc3MiAxMiAzIDEyWk0xMiA2LjAwMDA2QzEyIDYuMDAwMDYgMTQuMzk1NCA2LjAwMDA2IDE1LjUgNi4wMDAwNkMxNi42MDQ2IDYuMDAwMDYgMTcuNSA1LjEwNDYzIDE3LjUgNC4wMDAwNkMxNy41IDIuODk1NDkgMTYuNjA0NiAyLjAwMDA2IDE1LjUgMi4wMDAwNkMxNS4wMzQ1IDIuMDAwMDYgMTQuNjY0IDEuOTgzNTcgMTQgMi41QzEyLjkxMDUgMy4zNDcyOSAxMiA2LjAwMDA2IDEyIDYuMDAwMDZaTTEyLjUgNi4wMDAwNkMxMi41IDYuMDAwMDYgMTAuMTA0NiA2LjAwMDA2IDkgNi4wMDAwNkM3Ljg5NTQzIDYuMDAwMDYgNyA1LjEwNDYzIDcgNC4wMDAwNkM3IDIuODk1NDkgNy44OTU0MyAyLjAwMDA2IDkgMi4wMDAwNkM5LjQ2NTUxIDIuMDAwMDYgOS44MzU5NiAxLjk4MzU3IDEwLjUgMi41QzExLjU4OTUgMy4zNDcyOSAxMi41IDYuMDAwMDYgMTIuNSA2LjAwMDA2WiIgc3Ryb2tlPSIjMUUyMDI4IiBzdHJva2Utd2lkdGg9IjEuNSIgLz48L3N2Zz4=) */
const IconLineGift = React.forwardRef<IconLineGiftRef, IconLineGiftProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-gift" ref={ref}><path d="M12 22.5V6.5M4 12H20V22H4V12ZM3 12H21C21.5523 12 22 11.5523 22 11V7C22 6.44772 21.5523 6 21 6H3C2.44772 6 2 6.44772 2 7V11C2 11.5523 2.44772 12 3 12ZM12 6.00006C12 6.00006 14.3954 6.00006 15.5 6.00006C16.6046 6.00006 17.5 5.10463 17.5 4.00006C17.5 2.89549 16.6046 2.00006 15.5 2.00006C15.0345 2.00006 14.664 1.98357 14 2.5C12.9105 3.34729 12 6.00006 12 6.00006ZM12.5 6.00006C12.5 6.00006 10.1046 6.00006 9 6.00006C7.89543 6.00006 7 5.10463 7 4.00006C7 2.89549 7.89543 2.00006 9 2.00006C9.46551 2.00006 9.83596 1.98357 10.5 2.5C11.5895 3.34729 12.5 6.00006 12.5 6.00006Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineGift.displayName = definePortfolioDisplayName("IconLineGift")

export { IconLineGift }