/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineHairDryerProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineHairDryerRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMyAyMi40OTk2SDZDOC4yMDkxNCAyMi40OTk2IDEwIDIwLjcwODcgMTAgMTguNDk5Nk02LjUgMTIuOTk5Nkw4LjI2MDYzIDE3Ljg0MTNDOC40MDQzNCAxOC4yMzY1IDguNzc5OTIgMTguNDk5NiA5LjIwMDQzIDE4LjQ5OTZIMTEuNjEyNkMxMi4yOTUxIDE4LjQ5OTYgMTIuNzc3MSAxNy44MzA5IDEyLjU2MTMgMTcuMTgzNEwxMSAxMi40OTk2TTguODgxMTQgMTIuNzE1MUwyMS4xNzMzIDEwLjQyMDZDMjEuNjUyNSAxMC4zMzExIDIyIDkuOTEyOCAyMiA5LjQyNTI0VjQuNTczOTRDMjIgNC4wODYzOSAyMS42NTI1IDMuNjY4MDcgMjEuMTczMyAzLjU3ODZMOC44ODExNCAxLjI4NDA3QzUuMzA0MzEgMC42MTYzOTcgMiAzLjM2MDk4IDIgNi45OTk1OUMyIDEwLjYzODIgNS4zMDQzMSAxMy4zODI4IDguODgxMTQgMTIuNzE1MVpNMTAgNi45OTk1OUMxMCA4LjEwNDE2IDkuMTA0NTcgOC45OTk1OSA4IDguOTk5NTlDNi44OTU0MyA4Ljk5OTU5IDYgOC4xMDQxNiA2IDYuOTk5NTlDNiA1Ljg5NTAyIDYuODk1NDMgNC45OTk1OSA4IDQuOTk5NTlDOS4xMDQ1NyA0Ljk5OTU5IDEwIDUuODk1MDIgMTAgNi45OTk1OVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIgLz48L3N2Zz4=) */
const IconLineHairDryer = React.forwardRef<IconLineHairDryerRef, IconLineHairDryerProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-hair-dryer" ref={ref}><path d="M3 22.4996H6C8.20914 22.4996 10 20.7087 10 18.4996M6.5 12.9996L8.26063 17.8413C8.40434 18.2365 8.77992 18.4996 9.20043 18.4996H11.6126C12.2951 18.4996 12.7771 17.8309 12.5613 17.1834L11 12.4996M8.88114 12.7151L21.1733 10.4206C21.6525 10.3311 22 9.9128 22 9.42524V4.57394C22 4.08639 21.6525 3.66807 21.1733 3.5786L8.88114 1.28407C5.30431 0.616397 2 3.36098 2 6.99959C2 10.6382 5.30431 13.3828 8.88114 12.7151ZM10 6.99959C10 8.10416 9.10457 8.99959 8 8.99959C6.89543 8.99959 6 8.10416 6 6.99959C6 5.89502 6.89543 4.99959 8 4.99959C9.10457 4.99959 10 5.89502 10 6.99959Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineHairDryer.displayName = definePortfolioDisplayName("IconLineHairDryer")

export { IconLineHairDryer }