/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 * Created by Yuri Uliam
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineArrowGoingUpAltProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineArrowGoingUpAltRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTMuNDMyNiA1LjMyNDIyTDIyLjQzMjUgNS4zMjQyNk0yMi40MzI1IDUuMzI0MjZMMjIuNDMyNSAxNC42ODc5TTIyLjQzMjUgNS4zMjQyNkwxMy4zMjUxIDE0LjUwMDFMOC44MjUxIDkuNzE3MjdMMS4wNDIyNCAxNy41MDAxIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiIC8+PC9zdmc+) */
const IconLineArrowGoingUpAlt = React.forwardRef<IconLineArrowGoingUpAltRef, IconLineArrowGoingUpAltProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-arrow-going-up-alt" ref={ref}><path d="M13.4326 5.32422L22.4325 5.32426M22.4325 5.32426L22.4325 14.6879M22.4325 5.32426L13.3251 14.5001L8.8251 9.71727L1.04224 17.5001" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></IconBase>)
IconLineArrowGoingUpAlt.displayName = definePortfolioDisplayName("IconLineArrowGoingUpAlt")

export { IconLineArrowGoingUpAlt }