/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledSkipForwardProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledSkipForwardRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNy4yODg3MiA1LjIyNDgzQzYuMjg5NDIgNC42MDY1NiA0Ljk5OTUxIDUuMzI1MzMgNC45OTk1MSA2LjUwMDQzVjE3LjQ5NTlDNC45OTk1MSAxOC42NzEgNi4yODk0MiAxOS4zODk4IDcuMjg4NzIgMTguNzcxNUwxNi44ODY3IDEyLjgzMzJWMTguMDAwNkMxNi44ODY3IDE4LjU1MjkgMTcuMzM0NCAxOS4wMDA2IDE3Ljg4NjcgMTkuMDAwNkMxOC40MzkgMTkuMDAwNiAxOC44ODY3IDE4LjU1MjkgMTguODg2NyAxOC4wMDA2VjYuMDAwNjVDMTguODg2NyA1LjQ0ODM2IDE4LjQzOSA1LjAwMDY1IDE3Ljg4NjcgNS4wMDA2NUMxNy4zMzQ0IDUuMDAwNjUgMTYuODg2NyA1LjQ0ODM2IDE2Ljg4NjcgNi4wMDA2NVYxMS4xNjMxTDcuMjg4NzIgNS4yMjQ4M1oiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFilledSkipForward = React.forwardRef<IconFilledSkipForwardRef, IconFilledSkipForwardProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-skip-forward" ref={ref}><path d="M7.28872 5.22483C6.28942 4.60656 4.99951 5.32533 4.99951 6.50043V17.4959C4.99951 18.671 6.28942 19.3898 7.28872 18.7715L16.8867 12.8332V18.0006C16.8867 18.5529 17.3344 19.0006 17.8867 19.0006C18.439 19.0006 18.8867 18.5529 18.8867 18.0006V6.00065C18.8867 5.44836 18.439 5.00065 17.8867 5.00065C17.3344 5.00065 16.8867 5.44836 16.8867 6.00065V11.1631L7.28872 5.22483Z" fill="currentColor" /></IconBase>)
IconFilledSkipForward.displayName = definePortfolioDisplayName("IconFilledSkipForward")

export { IconFilledSkipForward }