/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineMultiSelectBoxProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineMultiSelectBoxRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTUgMUg0QzIuMzQzMTUgMSAxIDIuMzQzMTUgMSA0VjE1TTkgMjNIMjFDMjIuMTA0NiAyMyAyMyAyMi4xMDQ2IDIzIDIxVjlDMjMgNy44OTU0MyAyMi4xMDQ2IDcgMjEgN0g5QzcuODk1NDMgNyA3IDcuODk1NDMgNyA5VjIxQzcgMjIuMTA0NiA3Ljg5NTQzIDIzIDkgMjNaIiBzdHJva2U9IiMxRTIwMjgiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIC8+PC9zdmc+) */
const IconLineMultiSelectBox = React.forwardRef<IconLineMultiSelectBoxRef, IconLineMultiSelectBoxProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-multi-select-box" ref={ref}><path d="M15 1H4C2.34315 1 1 2.34315 1 4V15M9 23H21C22.1046 23 23 22.1046 23 21V9C23 7.89543 22.1046 7 21 7H9C7.89543 7 7 7.89543 7 9V21C7 22.1046 7.89543 23 9 23Z" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" /></IconBase>)
IconLineMultiSelectBox.displayName = definePortfolioDisplayName("IconLineMultiSelectBox")

export { IconLineMultiSelectBox }