/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconFilledCryptoDecentralandManaProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconFilledCryptoDecentralandManaRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGNsaXAtcnVsZT0iZXZlbm9kZCIgZD0iTTI0IDEyQzI0IDE4LjYyNzQgMTguNjI3NCAyNCAxMiAyNEM1LjM3MjU4IDI0IDAgMTguNjI3NCAwIDEyQzAgNS4zNzI1OCA1LjM3MjU4IDAgMTIgMEMxOC42Mjc0IDAgMjQgNS4zNzI1OCAyNCAxMlpNOC41MDI3MiA2QzkuMzMxMTQgNiAxMC4wMDI3IDUuMzI4NDMgMTAuMDAyNyA0LjVDMTAuMDAyNyAzLjY3MTU3IDkuMzMxMTQgMyA4LjUwMjcyIDNDNy42NzQyOSAzIDcuMDAyNzIgMy42NzE1NyA3LjAwMjcyIDQuNUM3LjAwMjcyIDUuMzI4NDMgNy42NzQyOSA2IDguNTAyNzIgNlpNMTkuMDk4NyA3LjhDMTkuMDk4NyA5LjQ1Njg1IDE3Ljc1NTUgMTAuOCAxNi4wOTg3IDEwLjhDMTQuNDQxOCAxMC44IDEzLjA5ODcgOS40NTY4NSAxMy4wOTg3IDcuOEMxMy4wOTg3IDYuMTQzMTUgMTQuNDQxOCA0LjggMTYuMDk4NyA0LjhDMTcuNzU1NSA0LjggMTkuMDk4NyA2LjE0MzE1IDE5LjA5ODcgNy44Wk0xLjAwMjcyIDE2LjhIOC41MDI3MlY3LjhMMS4wMDI3MiAxNi44Wk00LjgwMDcxIDIxLjZDMy44OTQ3MSAyMC45MTYgMy4wODQ3MSAyMC4xMDYgMi40MDA3MSAxOS4ySDEwLjYwMjdMMTYuMDk4NyAxMi42VjE5LjJIMjEuNjAwN0MyMC45MTY3IDIwLjEwNiAyMC4xMDY3IDIwLjkxNiAxOS4yMDA3IDIxLjZINC44MDA3MVoiIGZpbGw9IiMxRTIwMjgiIC8+PC9zdmc+) */
const IconFilledCryptoDecentralandMana = React.forwardRef<IconFilledCryptoDecentralandManaRef, IconFilledCryptoDecentralandManaProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-filled-crypto-decentraland-mana" ref={ref}><path fillRule="evenodd" clipRule="evenodd" d="M24 12C24 18.6274 18.6274 24 12 24C5.37258 24 0 18.6274 0 12C0 5.37258 5.37258 0 12 0C18.6274 0 24 5.37258 24 12ZM8.50272 6C9.33114 6 10.0027 5.32843 10.0027 4.5C10.0027 3.67157 9.33114 3 8.50272 3C7.67429 3 7.00272 3.67157 7.00272 4.5C7.00272 5.32843 7.67429 6 8.50272 6ZM19.0987 7.8C19.0987 9.45685 17.7555 10.8 16.0987 10.8C14.4418 10.8 13.0987 9.45685 13.0987 7.8C13.0987 6.14315 14.4418 4.8 16.0987 4.8C17.7555 4.8 19.0987 6.14315 19.0987 7.8ZM1.00272 16.8H8.50272V7.8L1.00272 16.8ZM4.80071 21.6C3.89471 20.916 3.08471 20.106 2.40071 19.2H10.6027L16.0987 12.6V19.2H21.6007C20.9167 20.106 20.1067 20.916 19.2007 21.6H4.80071Z" fill="currentColor" /></IconBase>)
IconFilledCryptoDecentralandMana.displayName = definePortfolioDisplayName("IconFilledCryptoDecentralandMana")

export { IconFilledCryptoDecentralandMana }