/**
 * =============================================================================
 * THIS IS AN AUTOGENERATED FILE FROM "Generate Icons" SCRIPT!
 * =============================================================================
 */
import React from 'react'

import { IconBase } from '~/design/base/icon'
import { definePortfolioDisplayName } from '~/shared/helpers/displayName'

type IconLineRoomUpgradeProps = React.ComponentPropsWithoutRef<typeof IconBase>
type IconLineRoomUpgradeRef = React.ComponentRef<typeof IconBase>

/** @preview ![img](data:image/svg+xml;base64,PHN2ZyBzdHlsZT0iYmFja2dyb3VuZC1jb2xvcjogI2ZmZjsgYm9yZGVyLXJhZGl1czogMnB4IiB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMTIuNDk5NSAxQzE1LjgxMzIgMSAxOC40OTk1IDMuNjg2MjkgMTguNDk5NSA3VjIxQzE4LjQ5OTUgMjIuMTA0NiAxNy42MDQxIDIzIDE2LjQ5OTUgMjNIOC40OTk1MkM3LjM5NDk1IDIzIDYuNDk5NTEgMjIuMTA0NiA2LjQ5OTUxIDIxVjE0QzYuNDk5NTEgMTIuODk1NCA3LjM5NDk1IDEyIDguNDk5NTEgMTJIMTAuOTk5NUMxMi45OTk1IDEyIDE0LjQ5OTUgMTAgMTQuNDk5NSA4QzE0LjQ5OTUgNiAxMy40OTk1IDUgMTEuOTk5NSA1QzExLjExODIgNSAxMC41ODIxIDUuNTE3OCAxMC4xODg0IDYuMjQ5MTdDOS42ODkxMSA3LjE3NjYgOC43MDExMSA3Ljc3MTg4IDcuNjg4MzUgNy40ODI1MkM2LjcyNjI4IDcuMjA3NjUgNi4wOTU4NSA2LjI0NjE5IDYuMzcwMjIgNS4yODM5N0M3LjAzNDc1IDIuOTUzNDEgOC40NjQ4NiAxIDEyLjQ5OTUgMVoiIHN0cm9rZT0iIzFFMjAyOCIgc3Ryb2tlLXdpZHRoPSIxLjUiIC8+PC9zdmc+) */
const IconLineRoomUpgrade = React.forwardRef<IconLineRoomUpgradeRef, IconLineRoomUpgradeProps>((props, ref) => <IconBase {...props} width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" data-portfolio-icon-name="$icon-line-room-upgrade" ref={ref}><path d="M12.4995 1C15.8132 1 18.4995 3.68629 18.4995 7V21C18.4995 22.1046 17.6041 23 16.4995 23H8.49952C7.39495 23 6.49951 22.1046 6.49951 21V14C6.49951 12.8954 7.39495 12 8.49951 12H10.9995C12.9995 12 14.4995 10 14.4995 8C14.4995 6 13.4995 5 11.9995 5C11.1182 5 10.5821 5.5178 10.1884 6.24917C9.68911 7.1766 8.70111 7.77188 7.68835 7.48252C6.72628 7.20765 6.09585 6.24619 6.37022 5.28397C7.03475 2.95341 8.46486 1 12.4995 1Z" stroke="currentColor" strokeWidth="1.5" /></IconBase>)
IconLineRoomUpgrade.displayName = definePortfolioDisplayName("IconLineRoomUpgrade")

export { IconLineRoomUpgrade }